# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiChEsher.ui'
#
# Created: Wed Nov 02 21:46:28 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(556, 680)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/resource/resource/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelModule = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labelModule.setFont(font)
        self.labelModule.setText(_fromUtf8(""))
        self.labelModule.setAlignment(QtCore.Qt.AlignCenter)
        self.labelModule.setObjectName(_fromUtf8("labelModule"))
        self.gridLayout.addWidget(self.labelModule, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageVectorDXF = QtGui.QWidget()
        self.pageVectorDXF.setObjectName(_fromUtf8("pageVectorDXF"))
        self.gridLayout_7 = QtGui.QGridLayout(self.pageVectorDXF)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.doubleSpinBoxVectorDXFScale = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFScale.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxVectorDXFScale.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxVectorDXFScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFScale.setDecimals(3)
        self.doubleSpinBoxVectorDXFScale.setMinimum(0.0)
        self.doubleSpinBoxVectorDXFScale.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFScale.setSingleStep(0.5)
        self.doubleSpinBoxVectorDXFScale.setProperty("value", 10.0)
        self.doubleSpinBoxVectorDXFScale.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFScale"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFScale, 5, 3, 1, 1)
        self.doubleSpinBoxVectorDXFVMax = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFVMax.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxVectorDXFVMax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxVectorDXFVMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFVMax.setDecimals(3)
        self.doubleSpinBoxVectorDXFVMax.setMinimum(0.0)
        self.doubleSpinBoxVectorDXFVMax.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFVMax.setSingleStep(1.0)
        self.doubleSpinBoxVectorDXFVMax.setProperty("value", 100.0)
        self.doubleSpinBoxVectorDXFVMax.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFVMax"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFVMax, 4, 4, 1, 1)
        self.doubleSpinBoxVectorDXFDY = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFDY.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxVectorDXFDY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxVectorDXFDY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFDY.setDecimals(3)
        self.doubleSpinBoxVectorDXFDY.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFDY.setSingleStep(1.0)
        self.doubleSpinBoxVectorDXFDY.setProperty("value", 100.0)
        self.doubleSpinBoxVectorDXFDY.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFDY"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFDY, 3, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.pageVectorDXF)
        self.label_41.setIndent(18)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_7.addWidget(self.label_41, 4, 0, 1, 3)
        self.label_37 = QtGui.QLabel(self.pageVectorDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_7.addWidget(self.label_37, 8, 0, 1, 1)
        self.doubleSpinBoxVectorDXFVMin = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFVMin.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxVectorDXFVMin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxVectorDXFVMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFVMin.setDecimals(3)
        self.doubleSpinBoxVectorDXFVMin.setMinimum(0.0)
        self.doubleSpinBoxVectorDXFVMin.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFVMin.setSingleStep(1.0)
        self.doubleSpinBoxVectorDXFVMin.setProperty("value", 0.0)
        self.doubleSpinBoxVectorDXFVMin.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFVMin"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFVMin, 4, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.pageVectorDXF)
        self.label_36.setIndent(18)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_7.addWidget(self.label_36, 5, 0, 1, 1)
        self.pushButtonVectorDXFOutput = QtGui.QPushButton(self.pageVectorDXF)
        self.pushButtonVectorDXFOutput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonVectorDXFOutput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonVectorDXFOutput.setObjectName(_fromUtf8("pushButtonVectorDXFOutput"))
        self.gridLayout_7.addWidget(self.pushButtonVectorDXFOutput, 9, 1, 1, 1)
        self.label_38 = QtGui.QLabel(self.pageVectorDXF)
        self.label_38.setIndent(18)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_7.addWidget(self.label_38, 9, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 7, 0, 1, 5)
        self.pushButtonVectorDXFCreate = QtGui.QPushButton(self.pageVectorDXF)
        self.pushButtonVectorDXFCreate.setObjectName(_fromUtf8("pushButtonVectorDXFCreate"))
        self.gridLayout_7.addWidget(self.pushButtonVectorDXFCreate, 11, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 10, 0, 1, 5)
        self.lineEditVectorDXFOutput = QtGui.QLineEdit(self.pageVectorDXF)
        self.lineEditVectorDXFOutput.setObjectName(_fromUtf8("lineEditVectorDXFOutput"))
        self.gridLayout_7.addWidget(self.lineEditVectorDXFOutput, 9, 2, 1, 3)
        self.lineEditVectorDXFInput = QtGui.QLineEdit(self.pageVectorDXF)
        self.lineEditVectorDXFInput.setObjectName(_fromUtf8("lineEditVectorDXFInput"))
        self.gridLayout_7.addWidget(self.lineEditVectorDXFInput, 1, 2, 1, 3)
        self.pushButtonVectorDXFInput = QtGui.QPushButton(self.pageVectorDXF)
        self.pushButtonVectorDXFInput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonVectorDXFInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonVectorDXFInput.setObjectName(_fromUtf8("pushButtonVectorDXFInput"))
        self.gridLayout_7.addWidget(self.pushButtonVectorDXFInput, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.pageVectorDXF)
        self.label_43.setIndent(18)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.pageVectorDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_42.setFont(font)
        self.label_42.setIndent(-4)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_7.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.pageVectorDXF)
        self.label_35.setIndent(18)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_7.addWidget(self.label_35, 2, 0, 1, 1)
        self.doubleSpinBoxVectorDXFDX = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFDX.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxVectorDXFDX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxVectorDXFDX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFDX.setDecimals(3)
        self.doubleSpinBoxVectorDXFDX.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFDX.setSingleStep(1.0)
        self.doubleSpinBoxVectorDXFDX.setProperty("value", 100.0)
        self.doubleSpinBoxVectorDXFDX.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFDX"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFDX, 2, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.pageVectorDXF)
        self.label_39.setIndent(18)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_7.addWidget(self.label_39, 3, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.pageVectorDXF)
        self.label_27.setIndent(18)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 6, 0, 1, 1)
        self.doubleSpinBoxVectorDXFLessThan = QtGui.QDoubleSpinBox(self.pageVectorDXF)
        self.doubleSpinBoxVectorDXFLessThan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxVectorDXFLessThan.setDecimals(4)
        self.doubleSpinBoxVectorDXFLessThan.setMaximum(99999999.0)
        self.doubleSpinBoxVectorDXFLessThan.setSingleStep(0.005)
        self.doubleSpinBoxVectorDXFLessThan.setProperty("value", 0.005)
        self.doubleSpinBoxVectorDXFLessThan.setObjectName(_fromUtf8("doubleSpinBoxVectorDXFLessThan"))
        self.gridLayout_7.addWidget(self.doubleSpinBoxVectorDXFLessThan, 6, 3, 1, 1)
        self.stackedWidget.addWidget(self.pageVectorDXF)
        self.pageCS = QtGui.QWidget()
        self.pageCS.setObjectName(_fromUtf8("pageCS"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pageCS)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.spinBoxCSTime = QtGui.QSpinBox(self.pageCS)
        self.spinBoxCSTime.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxCSTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxCSTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxCSTime.setMaximum(12)
        self.spinBoxCSTime.setProperty("value", 1)
        self.spinBoxCSTime.setObjectName(_fromUtf8("spinBoxCSTime"))
        self.gridLayout_8.addWidget(self.spinBoxCSTime, 4, 2, 1, 1)
        self.checkBoxCSOutputCS = QtGui.QCheckBox(self.pageCS)
        self.checkBoxCSOutputCS.setObjectName(_fromUtf8("checkBoxCSOutputCS"))
        self.gridLayout_8.addWidget(self.checkBoxCSOutputCS, 12, 0, 1, 1)
        self.checkBoxCSOutputFormatted = QtGui.QCheckBox(self.pageCS)
        self.checkBoxCSOutputFormatted.setObjectName(_fromUtf8("checkBoxCSOutputFormatted"))
        self.gridLayout_8.addWidget(self.checkBoxCSOutputFormatted, 11, 0, 1, 1)
        self.lineEditCSInputDefinition = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSInputDefinition.setObjectName(_fromUtf8("lineEditCSInputDefinition"))
        self.gridLayout_8.addWidget(self.lineEditCSInputDefinition, 2, 2, 1, 1)
        self.lineEditCSOutputCS = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSOutputCS.setEnabled(False)
        self.lineEditCSOutputCS.setObjectName(_fromUtf8("lineEditCSOutputCS"))
        self.gridLayout_8.addWidget(self.lineEditCSOutputCS, 12, 2, 1, 1)
        self.pushButtonCSInputResults = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSInputResults.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCSInputResults.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCSInputResults.setObjectName(_fromUtf8("pushButtonCSInputResults"))
        self.gridLayout_8.addWidget(self.pushButtonCSInputResults, 3, 1, 1, 1)
        self.pushButtonCSOutputFormatted = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSOutputFormatted.setEnabled(False)
        self.pushButtonCSOutputFormatted.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCSOutputFormatted.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCSOutputFormatted.setObjectName(_fromUtf8("pushButtonCSOutputFormatted"))
        self.gridLayout_8.addWidget(self.pushButtonCSOutputFormatted, 11, 1, 1, 1)
        self.lineEditCSInputResults = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSInputResults.setObjectName(_fromUtf8("lineEditCSInputResults"))
        self.gridLayout_8.addWidget(self.lineEditCSInputResults, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem2, 9, 0, 1, 3)
        self.label_49 = QtGui.QLabel(self.pageCS)
        self.label_49.setIndent(18)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_8.addWidget(self.label_49, 3, 0, 1, 1)
        self.label_50 = QtGui.QLabel(self.pageCS)
        self.label_50.setIndent(18)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_8.addWidget(self.label_50, 4, 0, 1, 1)
        self.pushButtonCSOutputCS = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSOutputCS.setEnabled(False)
        self.pushButtonCSOutputCS.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCSOutputCS.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCSOutputCS.setObjectName(_fromUtf8("pushButtonCSOutputCS"))
        self.gridLayout_8.addWidget(self.pushButtonCSOutputCS, 12, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.pageCS)
        self.label_44.setIndent(18)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_51 = QtGui.QLabel(self.pageCS)
        self.label_51.setIndent(18)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_8.addWidget(self.label_51, 5, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.pageCS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 10, 0, 1, 1)
        self.spinBoxCSFlow = QtGui.QSpinBox(self.pageCS)
        self.spinBoxCSFlow.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxCSFlow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxCSFlow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxCSFlow.setMaximum(12)
        self.spinBoxCSFlow.setProperty("value", 2)
        self.spinBoxCSFlow.setObjectName(_fromUtf8("spinBoxCSFlow"))
        self.gridLayout_8.addWidget(self.spinBoxCSFlow, 5, 2, 1, 1)
        self.lineEditCSOutputFormatted = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSOutputFormatted.setEnabled(False)
        self.lineEditCSOutputFormatted.setObjectName(_fromUtf8("lineEditCSOutputFormatted"))
        self.gridLayout_8.addWidget(self.lineEditCSOutputFormatted, 11, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.pageCS)
        self.label_45.setIndent(18)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 1, 0, 1, 1)
        self.label_47 = QtGui.QLabel(self.pageCS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_47.setFont(font)
        self.label_47.setIndent(-4)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_8.addWidget(self.label_47, 0, 0, 1, 1)
        self.lineEditCSInputMesh = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSInputMesh.setObjectName(_fromUtf8("lineEditCSInputMesh"))
        self.gridLayout_8.addWidget(self.lineEditCSInputMesh, 1, 2, 1, 1)
        self.pushButtonCSInputDefinition = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSInputDefinition.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCSInputDefinition.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCSInputDefinition.setObjectName(_fromUtf8("pushButtonCSInputDefinition"))
        self.gridLayout_8.addWidget(self.pushButtonCSInputDefinition, 2, 1, 1, 1)
        self.pushButtonCSInputMesh = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSInputMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCSInputMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCSInputMesh.setObjectName(_fromUtf8("pushButtonCSInputMesh"))
        self.gridLayout_8.addWidget(self.pushButtonCSInputMesh, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem3, 13, 0, 1, 3)
        self.pushButtonCSCreate = QtGui.QPushButton(self.pageCS)
        self.pushButtonCSCreate.setObjectName(_fromUtf8("pushButtonCSCreate"))
        self.gridLayout_8.addWidget(self.pushButtonCSCreate, 14, 0, 1, 3)
        self.lineEditCSInputPrefix = QtGui.QLineEdit(self.pageCS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCSInputPrefix.sizePolicy().hasHeightForWidth())
        self.lineEditCSInputPrefix.setSizePolicy(sizePolicy)
        self.lineEditCSInputPrefix.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditCSInputPrefix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditCSInputPrefix.setObjectName(_fromUtf8("lineEditCSInputPrefix"))
        self.gridLayout_8.addWidget(self.lineEditCSInputPrefix, 7, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.pageCS)
        self.label_28.setIndent(18)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 7, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.pageCS)
        self.label_31.setIndent(18)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_8.addWidget(self.label_31, 6, 0, 1, 1)
        self.doubleSpinBoxCSSizeFactor = QtGui.QDoubleSpinBox(self.pageCS)
        self.doubleSpinBoxCSSizeFactor.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxCSSizeFactor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCSSizeFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxCSSizeFactor.setDecimals(3)
        self.doubleSpinBoxCSSizeFactor.setMaximum(99999999.0)
        self.doubleSpinBoxCSSizeFactor.setSingleStep(0.5)
        self.doubleSpinBoxCSSizeFactor.setProperty("value", 7.5)
        self.doubleSpinBoxCSSizeFactor.setObjectName(_fromUtf8("doubleSpinBoxCSSizeFactor"))
        self.gridLayout_8.addWidget(self.doubleSpinBoxCSSizeFactor, 6, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.pageCS)
        self.label_40.setIndent(18)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 8, 0, 1, 1)
        self.lineEditCSInputSuffix = QtGui.QLineEdit(self.pageCS)
        self.lineEditCSInputSuffix.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditCSInputSuffix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditCSInputSuffix.setObjectName(_fromUtf8("lineEditCSInputSuffix"))
        self.gridLayout_8.addWidget(self.lineEditCSInputSuffix, 8, 2, 1, 1)
        self.stackedWidget.addWidget(self.pageCS)
        self.page2DM = QtGui.QWidget()
        self.page2DM.setObjectName(_fromUtf8("page2DM"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page2DM)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBox2dmNS6 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS6.setObjectName(_fromUtf8("checkBox2dmNS6"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS6, 17, 0, 1, 1)
        self.checkBox2dmNS1 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS1.setObjectName(_fromUtf8("checkBox2dmNS1"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS1, 12, 0, 1, 1)
        self.checkBox2dmNS2 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS2.setObjectName(_fromUtf8("checkBox2dmNS2"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS2, 13, 0, 1, 1)
        self.pushButton2dmNS5 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS5.setEnabled(False)
        self.pushButton2dmNS5.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS5.setObjectName(_fromUtf8("pushButton2dmNS5"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS5, 16, 1, 1, 1)
        self.checkBox2dmBottomFriction = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmBottomFriction.setObjectName(_fromUtf8("checkBox2dmBottomFriction"))
        self.gridLayout_5.addWidget(self.checkBox2dmBottomFriction, 8, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.page2DM)
        self.label_19.setIndent(18)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page2DM)
        self.label_17.setIndent(18)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.pushButton2dmCulvertHeight = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmCulvertHeight.setEnabled(False)
        self.pushButton2dmCulvertHeight.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmCulvertHeight.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmCulvertHeight.setObjectName(_fromUtf8("pushButton2dmCulvertHeight"))
        self.gridLayout_5.addWidget(self.pushButton2dmCulvertHeight, 11, 1, 1, 1)
        self.pushButton2dmBottom = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmBottom.setEnabled(False)
        self.pushButton2dmBottom.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmBottom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmBottom.setObjectName(_fromUtf8("pushButton2dmBottom"))
        self.gridLayout_5.addWidget(self.pushButton2dmBottom, 7, 1, 1, 1)
        self.pushButton2dmWaterSurface = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmWaterSurface.setEnabled(False)
        self.pushButton2dmWaterSurface.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmWaterSurface.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmWaterSurface.setObjectName(_fromUtf8("pushButton2dmWaterSurface"))
        self.gridLayout_5.addWidget(self.pushButton2dmWaterSurface, 9, 1, 1, 1)
        self.pushButton2dmNS4 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS4.setEnabled(False)
        self.pushButton2dmNS4.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS4.setObjectName(_fromUtf8("pushButton2dmNS4"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS4, 15, 1, 1, 1)
        self.pushButton2dmInputData = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmInputData.setEnabled(True)
        self.pushButton2dmInputData.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmInputData.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmInputData.setObjectName(_fromUtf8("pushButton2dmInputData"))
        self.gridLayout_5.addWidget(self.pushButton2dmInputData, 3, 1, 1, 1)
        self.pushButton2dmInput = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmInput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmInput.setObjectName(_fromUtf8("pushButton2dmInput"))
        self.gridLayout_5.addWidget(self.pushButton2dmInput, 1, 1, 1, 1)
        self.checkBox2dmNS5 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS5.setObjectName(_fromUtf8("checkBox2dmNS5"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS5, 16, 0, 1, 1)
        self.checkBox2dmWaterDepth = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmWaterDepth.setObjectName(_fromUtf8("checkBox2dmWaterDepth"))
        self.gridLayout_5.addWidget(self.checkBox2dmWaterDepth, 10, 0, 1, 1)
        self.checkBox2dmCulvertHeight = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmCulvertHeight.setObjectName(_fromUtf8("checkBox2dmCulvertHeight"))
        self.gridLayout_5.addWidget(self.checkBox2dmCulvertHeight, 11, 0, 1, 1)
        self.pushButton2dmNS1 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS1.setEnabled(False)
        self.pushButton2dmNS1.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS1.setObjectName(_fromUtf8("pushButton2dmNS1"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS1, 12, 1, 1, 1)
        self.checkBox2dmNS4 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS4.setObjectName(_fromUtf8("checkBox2dmNS4"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS4, 15, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.page2DM)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_16.setFont(font)
        self.label_16.setIndent(-4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.pushButton2dmNS2 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS2.setEnabled(False)
        self.pushButton2dmNS2.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS2.setObjectName(_fromUtf8("pushButton2dmNS2"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS2, 13, 1, 1, 1)
        self.pushButton2dmBottomFriction = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmBottomFriction.setEnabled(False)
        self.pushButton2dmBottomFriction.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmBottomFriction.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmBottomFriction.setObjectName(_fromUtf8("pushButton2dmBottomFriction"))
        self.gridLayout_5.addWidget(self.pushButton2dmBottomFriction, 8, 1, 1, 1)
        self.checkBox2dmWaterSurface = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmWaterSurface.setObjectName(_fromUtf8("checkBox2dmWaterSurface"))
        self.gridLayout_5.addWidget(self.checkBox2dmWaterSurface, 9, 0, 1, 1)
        self.checkBox2dmBottom = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmBottom.setObjectName(_fromUtf8("checkBox2dmBottom"))
        self.gridLayout_5.addWidget(self.checkBox2dmBottom, 7, 0, 1, 1)
        self.checkBox2dmNS3 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS3.setObjectName(_fromUtf8("checkBox2dmNS3"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS3, 14, 0, 1, 1)
        self.pushButton2dmNS3 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS3.setEnabled(False)
        self.pushButton2dmNS3.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS3.setObjectName(_fromUtf8("pushButton2dmNS3"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS3, 14, 1, 1, 1)
        self.pushButton2dmWaterDepth = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmWaterDepth.setEnabled(False)
        self.pushButton2dmWaterDepth.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmWaterDepth.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmWaterDepth.setObjectName(_fromUtf8("pushButton2dmWaterDepth"))
        self.gridLayout_5.addWidget(self.pushButton2dmWaterDepth, 10, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page2DM)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 6, 0, 1, 1)
        self.pushButton2dmNS7 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS7.setEnabled(False)
        self.pushButton2dmNS7.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS7.setObjectName(_fromUtf8("pushButton2dmNS7"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS7, 18, 1, 1, 1)
        self.pushButton2dmNS6 = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmNS6.setEnabled(False)
        self.pushButton2dmNS6.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton2dmNS6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton2dmNS6.setObjectName(_fromUtf8("pushButton2dmNS6"))
        self.gridLayout_5.addWidget(self.pushButton2dmNS6, 17, 1, 1, 1)
        self.checkBox2dmNS7 = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmNS7.setObjectName(_fromUtf8("checkBox2dmNS7"))
        self.gridLayout_5.addWidget(self.checkBox2dmNS7, 18, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page2DM)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 2, 2, 1, 1)
        self.checkBox2dmImpermeable = QtGui.QCheckBox(self.page2DM)
        self.checkBox2dmImpermeable.setObjectName(_fromUtf8("checkBox2dmImpermeable"))
        self.gridLayout_5.addWidget(self.checkBox2dmImpermeable, 2, 0, 1, 2)
        self.spinBox2dmImpermeable = QtGui.QSpinBox(self.page2DM)
        self.spinBox2dmImpermeable.setEnabled(False)
        self.spinBox2dmImpermeable.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBox2dmImpermeable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox2dmImpermeable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox2dmImpermeable.setMinimum(-999999999)
        self.spinBox2dmImpermeable.setMaximum(999999999)
        self.spinBox2dmImpermeable.setObjectName(_fromUtf8("spinBox2dmImpermeable"))
        self.gridLayout_5.addWidget(self.spinBox2dmImpermeable, 2, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 2, 4, 1, 1)
        self.lineEdit2dmInput = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmInput.setObjectName(_fromUtf8("lineEdit2dmInput"))
        self.gridLayout_5.addWidget(self.lineEdit2dmInput, 1, 2, 1, 3)
        self.lineEdit2dmBottom = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmBottom.setEnabled(False)
        self.lineEdit2dmBottom.setObjectName(_fromUtf8("lineEdit2dmBottom"))
        self.gridLayout_5.addWidget(self.lineEdit2dmBottom, 7, 2, 1, 3)
        self.lineEdit2dmInputData = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmInputData.setEnabled(True)
        self.lineEdit2dmInputData.setObjectName(_fromUtf8("lineEdit2dmInputData"))
        self.gridLayout_5.addWidget(self.lineEdit2dmInputData, 3, 2, 1, 3)
        self.lineEdit2dmBottomFriction = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmBottomFriction.setEnabled(False)
        self.lineEdit2dmBottomFriction.setObjectName(_fromUtf8("lineEdit2dmBottomFriction"))
        self.gridLayout_5.addWidget(self.lineEdit2dmBottomFriction, 8, 2, 1, 3)
        self.lineEdit2dmWaterSurface = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmWaterSurface.setEnabled(False)
        self.lineEdit2dmWaterSurface.setObjectName(_fromUtf8("lineEdit2dmWaterSurface"))
        self.gridLayout_5.addWidget(self.lineEdit2dmWaterSurface, 9, 2, 1, 3)
        self.lineEdit2dmWaterDepth = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmWaterDepth.setEnabled(False)
        self.lineEdit2dmWaterDepth.setObjectName(_fromUtf8("lineEdit2dmWaterDepth"))
        self.gridLayout_5.addWidget(self.lineEdit2dmWaterDepth, 10, 2, 1, 3)
        self.lineEdit2dmCulvertHeight = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmCulvertHeight.setEnabled(False)
        self.lineEdit2dmCulvertHeight.setObjectName(_fromUtf8("lineEdit2dmCulvertHeight"))
        self.gridLayout_5.addWidget(self.lineEdit2dmCulvertHeight, 11, 2, 1, 3)
        self.lineEdit2dmNS1 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS1.setEnabled(False)
        self.lineEdit2dmNS1.setObjectName(_fromUtf8("lineEdit2dmNS1"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS1, 12, 2, 1, 3)
        self.lineEdit2dmNS2 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS2.setEnabled(False)
        self.lineEdit2dmNS2.setObjectName(_fromUtf8("lineEdit2dmNS2"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS2, 13, 2, 1, 3)
        self.lineEdit2dmNS3 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS3.setEnabled(False)
        self.lineEdit2dmNS3.setObjectName(_fromUtf8("lineEdit2dmNS3"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS3, 14, 2, 1, 3)
        self.lineEdit2dmNS4 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS4.setEnabled(False)
        self.lineEdit2dmNS4.setObjectName(_fromUtf8("lineEdit2dmNS4"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS4, 15, 2, 1, 3)
        self.lineEdit2dmNS5 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS5.setEnabled(False)
        self.lineEdit2dmNS5.setObjectName(_fromUtf8("lineEdit2dmNS5"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS5, 16, 2, 1, 3)
        self.lineEdit2dmNS6 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS6.setEnabled(False)
        self.lineEdit2dmNS6.setObjectName(_fromUtf8("lineEdit2dmNS6"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS6, 17, 2, 1, 3)
        self.lineEdit2dmNS7 = QtGui.QLineEdit(self.page2DM)
        self.lineEdit2dmNS7.setEnabled(False)
        self.lineEdit2dmNS7.setObjectName(_fromUtf8("lineEdit2dmNS7"))
        self.gridLayout_5.addWidget(self.lineEdit2dmNS7, 18, 2, 1, 3)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 19, 0, 1, 5)
        self.pushButton2dmConvert = QtGui.QPushButton(self.page2DM)
        self.pushButton2dmConvert.setObjectName(_fromUtf8("pushButton2dmConvert"))
        self.gridLayout_5.addWidget(self.pushButton2dmConvert, 20, 0, 1, 5)
        spacerItem6 = QtGui.QSpacerItem(100, 81, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 4, 0, 1, 5)
        self.stackedWidget.addWidget(self.page2DM)
        self.pageCont2DXF = QtGui.QWidget()
        self.pageCont2DXF.setObjectName(_fromUtf8("pageCont2DXF"))
        self.gridLayout_12 = QtGui.QGridLayout(self.pageCont2DXF)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.checkBoxCont2DXFOutputLine = QtGui.QCheckBox(self.pageCont2DXF)
        self.checkBoxCont2DXFOutputLine.setObjectName(_fromUtf8("checkBoxCont2DXFOutputLine"))
        self.gridLayout_12.addWidget(self.checkBoxCont2DXFOutputLine, 11, 0, 1, 1)
        self.checkBoxCont2DXFOutputSolid = QtGui.QCheckBox(self.pageCont2DXF)
        self.checkBoxCont2DXFOutputSolid.setObjectName(_fromUtf8("checkBoxCont2DXFOutputSolid"))
        self.gridLayout_12.addWidget(self.checkBoxCont2DXFOutputSolid, 10, 0, 1, 1)
        self.checkBoxCont2DXFOutputLegend = QtGui.QCheckBox(self.pageCont2DXF)
        self.checkBoxCont2DXFOutputLegend.setObjectName(_fromUtf8("checkBoxCont2DXFOutputLegend"))
        self.gridLayout_12.addWidget(self.checkBoxCont2DXFOutputLegend, 12, 0, 1, 1)
        self.lineEditCont2DXFOutputSolid = QtGui.QLineEdit(self.pageCont2DXF)
        self.lineEditCont2DXFOutputSolid.setObjectName(_fromUtf8("lineEditCont2DXFOutputSolid"))
        self.gridLayout_12.addWidget(self.lineEditCont2DXFOutputSolid, 10, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.pageCont2DXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_57.setFont(font)
        self.label_57.setIndent(-4)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_12.addWidget(self.label_57, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.pageCont2DXF)
        self.label_20.setIndent(18)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_12.addWidget(self.label_20, 1, 0, 1, 1)
        self.pushButtonCont2DXFInput = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFInput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCont2DXFInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCont2DXFInput.setObjectName(_fromUtf8("pushButtonCont2DXFInput"))
        self.gridLayout_12.addWidget(self.pushButtonCont2DXFInput, 1, 1, 1, 1)
        self.lineEditCont2DXFInput = QtGui.QLineEdit(self.pageCont2DXF)
        self.lineEditCont2DXFInput.setObjectName(_fromUtf8("lineEditCont2DXFInput"))
        self.gridLayout_12.addWidget(self.lineEditCont2DXFInput, 1, 2, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem7, 2, 0, 1, 4)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButtonCont2DXFAdd = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFAdd.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFAdd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFAdd.setObjectName(_fromUtf8("pushButtonCont2DXFAdd"))
        self.gridLayout_10.addWidget(self.pushButtonCont2DXFAdd, 0, 1, 1, 1)
        self.pushButtonCont2DXFDelete = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFDelete.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFDelete.setObjectName(_fromUtf8("pushButtonCont2DXFDelete"))
        self.gridLayout_10.addWidget(self.pushButtonCont2DXFDelete, 0, 2, 1, 1)
        self.pushButtonCont2DXFColour = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFColour.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFColour.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFColour.setObjectName(_fromUtf8("pushButtonCont2DXFColour"))
        self.gridLayout_10.addWidget(self.pushButtonCont2DXFColour, 0, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 0, 4, 1, 1)
        self.label_60 = QtGui.QLabel(self.pageCont2DXF)
        self.label_60.setMinimumSize(QtCore.QSize(70, 0))
        self.label_60.setIndent(18)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_10.addWidget(self.label_60, 0, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_10, 3, 0, 1, 4)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_59 = QtGui.QLabel(self.pageCont2DXF)
        self.label_59.setMinimumSize(QtCore.QSize(70, 0))
        self.label_59.setIndent(18)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_11.addWidget(self.label_59, 0, 0, 1, 1)
        self.pushButtonCont2DXFLoad = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFLoad.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFLoad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFLoad.setObjectName(_fromUtf8("pushButtonCont2DXFLoad"))
        self.gridLayout_11.addWidget(self.pushButtonCont2DXFLoad, 0, 1, 1, 1)
        self.pushButtonCont2DXFSave = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFSave.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFSave.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFSave.setObjectName(_fromUtf8("pushButtonCont2DXFSave"))
        self.gridLayout_11.addWidget(self.pushButtonCont2DXFSave, 0, 2, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 0, 3, 1, 1)
        self.comboBoxCont2DXF = QtGui.QComboBox(self.pageCont2DXF)
        self.comboBoxCont2DXF.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBoxCont2DXF.setObjectName(_fromUtf8("comboBoxCont2DXF"))
        self.gridLayout_11.addWidget(self.comboBoxCont2DXF, 0, 4, 1, 1)
        self.pushButtonCont2DXFDefault = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFDefault.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonCont2DXFDefault.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonCont2DXFDefault.setObjectName(_fromUtf8("pushButtonCont2DXFDefault"))
        self.gridLayout_11.addWidget(self.pushButtonCont2DXFDefault, 0, 5, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 5, 0, 1, 4)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem10, 6, 0, 1, 4)
        self.label_58 = QtGui.QLabel(self.pageCont2DXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_12.addWidget(self.label_58, 7, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.pageCont2DXF)
        self.label_61.setIndent(18)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_12.addWidget(self.label_61, 9, 0, 1, 1)
        self.lineEditCont2DXFOutputLayer = QtGui.QLineEdit(self.pageCont2DXF)
        self.lineEditCont2DXFOutputLayer.setObjectName(_fromUtf8("lineEditCont2DXFOutputLayer"))
        self.gridLayout_12.addWidget(self.lineEditCont2DXFOutputLayer, 9, 2, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem11, 18, 0, 1, 4)
        self.tableWidgetCont2DXF = QtGui.QTableWidget(self.pageCont2DXF)
        self.tableWidgetCont2DXF.setMinimumSize(QtCore.QSize(0, 160))
        self.tableWidgetCont2DXF.setObjectName(_fromUtf8("tableWidgetCont2DXF"))
        self.tableWidgetCont2DXF.setColumnCount(3)
        self.tableWidgetCont2DXF.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCont2DXF.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCont2DXF.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetCont2DXF.setHorizontalHeaderItem(2, item)
        self.gridLayout_12.addWidget(self.tableWidgetCont2DXF, 4, 0, 1, 4)
        self.pushButtonCont2DXFCreate = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFCreate.setObjectName(_fromUtf8("pushButtonCont2DXFCreate"))
        self.gridLayout_12.addWidget(self.pushButtonCont2DXFCreate, 19, 0, 1, 4)
        self.pushButtonCont2DXFOutputLine = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFOutputLine.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCont2DXFOutputLine.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCont2DXFOutputLine.setObjectName(_fromUtf8("pushButtonCont2DXFOutputLine"))
        self.gridLayout_12.addWidget(self.pushButtonCont2DXFOutputLine, 11, 1, 1, 1)
        self.lineEditCont2DXFOutputLine = QtGui.QLineEdit(self.pageCont2DXF)
        self.lineEditCont2DXFOutputLine.setObjectName(_fromUtf8("lineEditCont2DXFOutputLine"))
        self.gridLayout_12.addWidget(self.lineEditCont2DXFOutputLine, 11, 2, 1, 1)
        self.pushButtonCont2DXFOutputSolid = QtGui.QPushButton(self.pageCont2DXF)
        self.pushButtonCont2DXFOutputSolid.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCont2DXFOutputSolid.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCont2DXFOutputSolid.setObjectName(_fromUtf8("pushButtonCont2DXFOutputSolid"))
        self.gridLayout_12.addWidget(self.pushButtonCont2DXFOutputSolid, 10, 1, 1, 1)
        self.widgetCont2DXFLegend = QtGui.QWidget(self.pageCont2DXF)
        self.widgetCont2DXFLegend.setEnabled(False)
        self.widgetCont2DXFLegend.setObjectName(_fromUtf8("widgetCont2DXFLegend"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widgetCont2DXFLegend)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_48 = QtGui.QLabel(self.widgetCont2DXFLegend)
        self.label_48.setIndent(18)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_13.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_62 = QtGui.QLabel(self.widgetCont2DXFLegend)
        self.label_62.setIndent(18)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_13.addWidget(self.label_62, 1, 0, 1, 1)
        self.lineEditCont2DXFOutputLegendTitle = QtGui.QLineEdit(self.widgetCont2DXFLegend)
        self.lineEditCont2DXFOutputLegendTitle.setObjectName(_fromUtf8("lineEditCont2DXFOutputLegendTitle"))
        self.gridLayout_13.addWidget(self.lineEditCont2DXFOutputLegendTitle, 0, 1, 1, 1)
        self.lineEditCont2DXFOutputLegendSubtitle = QtGui.QLineEdit(self.widgetCont2DXFLegend)
        self.lineEditCont2DXFOutputLegendSubtitle.setObjectName(_fromUtf8("lineEditCont2DXFOutputLegendSubtitle"))
        self.gridLayout_13.addWidget(self.lineEditCont2DXFOutputLegendSubtitle, 1, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.widgetCont2DXFLegend)
        self.label_63.setIndent(18)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_13.addWidget(self.label_63, 2, 0, 1, 1)
        self.lineEditCont2DXFOutputLegendSeparator = QtGui.QLineEdit(self.widgetCont2DXFLegend)
        self.lineEditCont2DXFOutputLegendSeparator.setObjectName(_fromUtf8("lineEditCont2DXFOutputLegendSeparator"))
        self.gridLayout_13.addWidget(self.lineEditCont2DXFOutputLegendSeparator, 2, 1, 1, 1)
        self.checkBoxCont2DXFOutputLegendReverse = QtGui.QCheckBox(self.widgetCont2DXFLegend)
        self.checkBoxCont2DXFOutputLegendReverse.setObjectName(_fromUtf8("checkBoxCont2DXFOutputLegendReverse"))
        self.gridLayout_13.addWidget(self.checkBoxCont2DXFOutputLegendReverse, 3, 0, 1, 2)
        self.gridLayout_12.addWidget(self.widgetCont2DXFLegend, 13, 0, 4, 3)
        self.stackedWidget.addWidget(self.pageCont2DXF)
        self.pageTube = QtGui.QWidget()
        self.pageTube.setObjectName(_fromUtf8("pageTube"))
        self.gridLayout_14 = QtGui.QGridLayout(self.pageTube)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_67 = QtGui.QLabel(self.pageTube)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_67.setFont(font)
        self.label_67.setIndent(-4)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_14.addWidget(self.label_67, 0, 0, 1, 1)
        self.label_64 = QtGui.QLabel(self.pageTube)
        self.label_64.setIndent(18)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_14.addWidget(self.label_64, 1, 0, 1, 1)
        self.pushButtonTubeInputMesh = QtGui.QPushButton(self.pageTube)
        self.pushButtonTubeInputMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonTubeInputMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonTubeInputMesh.setObjectName(_fromUtf8("pushButtonTubeInputMesh"))
        self.gridLayout_14.addWidget(self.pushButtonTubeInputMesh, 1, 1, 1, 1)
        self.lineEditTubeInputMesh = QtGui.QLineEdit(self.pageTube)
        self.lineEditTubeInputMesh.setObjectName(_fromUtf8("lineEditTubeInputMesh"))
        self.gridLayout_14.addWidget(self.lineEditTubeInputMesh, 1, 2, 1, 2)
        self.label_68 = QtGui.QLabel(self.pageTube)
        self.label_68.setIndent(18)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_14.addWidget(self.label_68, 2, 0, 1, 1)
        self.pushButtonTubeInputLineSet = QtGui.QPushButton(self.pageTube)
        self.pushButtonTubeInputLineSet.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonTubeInputLineSet.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonTubeInputLineSet.setObjectName(_fromUtf8("pushButtonTubeInputLineSet"))
        self.gridLayout_14.addWidget(self.pushButtonTubeInputLineSet, 2, 1, 1, 1)
        self.lineEditTubeInputLineSet = QtGui.QLineEdit(self.pageTube)
        self.lineEditTubeInputLineSet.setObjectName(_fromUtf8("lineEditTubeInputLineSet"))
        self.gridLayout_14.addWidget(self.lineEditTubeInputLineSet, 2, 2, 1, 2)
        self.label_69 = QtGui.QLabel(self.pageTube)
        self.label_69.setIndent(18)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_14.addWidget(self.label_69, 3, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(517, 216, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem12, 12, 0, 1, 4)
        self.label_65 = QtGui.QLabel(self.pageTube)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_14.addWidget(self.label_65, 13, 0, 1, 1)
        self.label_66 = QtGui.QLabel(self.pageTube)
        self.label_66.setIndent(18)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_14.addWidget(self.label_66, 14, 0, 1, 1)
        self.pushButtonTubeOutput = QtGui.QPushButton(self.pageTube)
        self.pushButtonTubeOutput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonTubeOutput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonTubeOutput.setObjectName(_fromUtf8("pushButtonTubeOutput"))
        self.gridLayout_14.addWidget(self.pushButtonTubeOutput, 14, 1, 1, 1)
        self.lineEditTubeOutput = QtGui.QLineEdit(self.pageTube)
        self.lineEditTubeOutput.setObjectName(_fromUtf8("lineEditTubeOutput"))
        self.gridLayout_14.addWidget(self.lineEditTubeOutput, 14, 2, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(517, 216, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem13, 15, 0, 1, 4)
        self.label_78 = QtGui.QLabel(self.pageTube)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_14.addWidget(self.label_78, 3, 1, 1, 1)
        self.label_70 = QtGui.QLabel(self.pageTube)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_14.addWidget(self.label_70, 4, 1, 1, 1)
        self.label_71 = QtGui.QLabel(self.pageTube)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_14.addWidget(self.label_71, 5, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.pageTube)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_14.addWidget(self.label_72, 6, 1, 1, 1)
        self.label_73 = QtGui.QLabel(self.pageTube)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_14.addWidget(self.label_73, 7, 1, 1, 1)
        self.label_74 = QtGui.QLabel(self.pageTube)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_14.addWidget(self.label_74, 8, 1, 1, 1)
        self.label_75 = QtGui.QLabel(self.pageTube)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_14.addWidget(self.label_75, 9, 1, 1, 1)
        self.label_76 = QtGui.QLabel(self.pageTube)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_14.addWidget(self.label_76, 10, 1, 1, 1)
        self.label_77 = QtGui.QLabel(self.pageTube)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_14.addWidget(self.label_77, 11, 1, 1, 1)
        self.doubleSpinBoxTubeRel = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeRel.setMaximum(1.0)
        self.doubleSpinBoxTubeRel.setSingleStep(0.01)
        self.doubleSpinBoxTubeRel.setProperty("value", 0.05)
        self.doubleSpinBoxTubeRel.setObjectName(_fromUtf8("doubleSpinBoxTubeRel"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeRel, 3, 2, 1, 1)
        self.doubleSpinBoxTubeCe1 = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeCe1.setMaximum(999999.0)
        self.doubleSpinBoxTubeCe1.setSingleStep(0.01)
        self.doubleSpinBoxTubeCe1.setProperty("value", 0.5)
        self.doubleSpinBoxTubeCe1.setObjectName(_fromUtf8("doubleSpinBoxTubeCe1"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeCe1, 4, 2, 1, 1)
        self.doubleSpinBoxTubeCe2 = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeCe2.setMaximum(999999.0)
        self.doubleSpinBoxTubeCe2.setSingleStep(0.01)
        self.doubleSpinBoxTubeCe2.setProperty("value", 0.5)
        self.doubleSpinBoxTubeCe2.setObjectName(_fromUtf8("doubleSpinBoxTubeCe2"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeCe2, 5, 2, 1, 1)
        self.doubleSpinBoxTubeCs1 = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeCs1.setMaximum(999999.0)
        self.doubleSpinBoxTubeCs1.setSingleStep(0.01)
        self.doubleSpinBoxTubeCs1.setProperty("value", 1.0)
        self.doubleSpinBoxTubeCs1.setObjectName(_fromUtf8("doubleSpinBoxTubeCs1"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeCs1, 6, 2, 1, 1)
        self.doubleSpinBoxTubeCs2 = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeCs2.setMaximum(999999.0)
        self.doubleSpinBoxTubeCs2.setSingleStep(0.01)
        self.doubleSpinBoxTubeCs2.setProperty("value", 1.0)
        self.doubleSpinBoxTubeCs2.setObjectName(_fromUtf8("doubleSpinBoxTubeCs2"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeCs2, 7, 2, 1, 1)
        self.doubleSpinBoxTubeLrg = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeLrg.setMaximum(999999.0)
        self.doubleSpinBoxTubeLrg.setSingleStep(0.01)
        self.doubleSpinBoxTubeLrg.setProperty("value", 2.0)
        self.doubleSpinBoxTubeLrg.setObjectName(_fromUtf8("doubleSpinBoxTubeLrg"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeLrg, 8, 2, 1, 1)
        self.doubleSpinBoxTubeHau = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeHau.setMaximum(999999.0)
        self.doubleSpinBoxTubeHau.setSingleStep(0.01)
        self.doubleSpinBoxTubeHau.setProperty("value", 1.5)
        self.doubleSpinBoxTubeHau.setObjectName(_fromUtf8("doubleSpinBoxTubeHau"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeHau, 9, 2, 1, 1)
        self.spinBoxTubeClp = QtGui.QSpinBox(self.pageTube)
        self.spinBoxTubeClp.setMaximum(3)
        self.spinBoxTubeClp.setObjectName(_fromUtf8("spinBoxTubeClp"))
        self.gridLayout_14.addWidget(self.spinBoxTubeClp, 10, 2, 1, 1)
        self.doubleSpinBoxTubeL12 = QtGui.QDoubleSpinBox(self.pageTube)
        self.doubleSpinBoxTubeL12.setMaximum(999999.0)
        self.doubleSpinBoxTubeL12.setSingleStep(0.01)
        self.doubleSpinBoxTubeL12.setProperty("value", 0.2)
        self.doubleSpinBoxTubeL12.setObjectName(_fromUtf8("doubleSpinBoxTubeL12"))
        self.gridLayout_14.addWidget(self.doubleSpinBoxTubeL12, 11, 2, 1, 1)
        self.pushButtonTubeCreate = QtGui.QPushButton(self.pageTube)
        self.pushButtonTubeCreate.setObjectName(_fromUtf8("pushButtonTubeCreate"))
        self.gridLayout_14.addWidget(self.pushButtonTubeCreate, 16, 0, 1, 4)
        self.stackedWidget.addWidget(self.pageTube)
        self.gridLayout.addWidget(self.stackedWidget, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 556, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionChEsher = QtGui.QAction(MainWindow)
        self.actionChEsher.setObjectName(_fromUtf8("actionChEsher"))
        self.actionAbout_ChEsher = QtGui.QAction(MainWindow)
        self.actionAbout_ChEsher.setObjectName(_fromUtf8("actionAbout_ChEsher"))

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButtonCont2DXFInput, self.lineEditCont2DXFInput)
        MainWindow.setTabOrder(self.lineEditCont2DXFInput, self.pushButtonCont2DXFAdd)
        MainWindow.setTabOrder(self.pushButtonCont2DXFAdd, self.pushButtonCont2DXFDelete)
        MainWindow.setTabOrder(self.pushButtonCont2DXFDelete, self.pushButtonCont2DXFColour)
        MainWindow.setTabOrder(self.pushButtonCont2DXFColour, self.tableWidgetCont2DXF)
        MainWindow.setTabOrder(self.tableWidgetCont2DXF, self.pushButtonCont2DXFLoad)
        MainWindow.setTabOrder(self.pushButtonCont2DXFLoad, self.pushButtonCont2DXFSave)
        MainWindow.setTabOrder(self.pushButtonCont2DXFSave, self.comboBoxCont2DXF)
        MainWindow.setTabOrder(self.comboBoxCont2DXF, self.pushButtonCont2DXFDefault)
        MainWindow.setTabOrder(self.pushButtonCont2DXFDefault, self.lineEditCont2DXFOutputLayer)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputLayer, self.checkBoxCont2DXFOutputSolid)
        MainWindow.setTabOrder(self.checkBoxCont2DXFOutputSolid, self.pushButtonCont2DXFOutputSolid)
        MainWindow.setTabOrder(self.pushButtonCont2DXFOutputSolid, self.lineEditCont2DXFOutputSolid)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputSolid, self.checkBoxCont2DXFOutputLine)
        MainWindow.setTabOrder(self.checkBoxCont2DXFOutputLine, self.pushButtonCont2DXFOutputLine)
        MainWindow.setTabOrder(self.pushButtonCont2DXFOutputLine, self.lineEditCont2DXFOutputLine)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputLine, self.checkBoxCont2DXFOutputLegend)
        MainWindow.setTabOrder(self.checkBoxCont2DXFOutputLegend, self.lineEditCont2DXFOutputLegendTitle)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputLegendTitle, self.lineEditCont2DXFOutputLegendSubtitle)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputLegendSubtitle, self.lineEditCont2DXFOutputLegendSeparator)
        MainWindow.setTabOrder(self.lineEditCont2DXFOutputLegendSeparator, self.checkBoxCont2DXFOutputLegendReverse)
        MainWindow.setTabOrder(self.checkBoxCont2DXFOutputLegendReverse, self.pushButtonCont2DXFCreate)
        MainWindow.setTabOrder(self.pushButtonCont2DXFCreate, self.pushButtonTubeInputMesh)
        MainWindow.setTabOrder(self.pushButtonTubeInputMesh, self.lineEditTubeInputMesh)
        MainWindow.setTabOrder(self.lineEditTubeInputMesh, self.pushButtonTubeInputLineSet)
        MainWindow.setTabOrder(self.pushButtonTubeInputLineSet, self.lineEditTubeInputLineSet)
        MainWindow.setTabOrder(self.lineEditTubeInputLineSet, self.doubleSpinBoxTubeRel)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeRel, self.doubleSpinBoxTubeCe1)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeCe1, self.doubleSpinBoxTubeCe2)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeCe2, self.doubleSpinBoxTubeCs1)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeCs1, self.doubleSpinBoxTubeCs2)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeCs2, self.doubleSpinBoxTubeLrg)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeLrg, self.doubleSpinBoxTubeHau)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeHau, self.spinBoxTubeClp)
        MainWindow.setTabOrder(self.spinBoxTubeClp, self.doubleSpinBoxTubeL12)
        MainWindow.setTabOrder(self.doubleSpinBoxTubeL12, self.pushButtonTubeOutput)
        MainWindow.setTabOrder(self.pushButtonTubeOutput, self.lineEditTubeOutput)
        MainWindow.setTabOrder(self.lineEditTubeOutput, self.pushButtonTubeCreate)
        MainWindow.setTabOrder(self.pushButtonTubeCreate, self.pushButtonVectorDXFInput)
        MainWindow.setTabOrder(self.pushButtonVectorDXFInput, self.lineEditVectorDXFInput)
        MainWindow.setTabOrder(self.lineEditVectorDXFInput, self.doubleSpinBoxVectorDXFDX)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFDX, self.doubleSpinBoxVectorDXFDY)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFDY, self.doubleSpinBoxVectorDXFVMin)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFVMin, self.doubleSpinBoxVectorDXFVMax)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFVMax, self.doubleSpinBoxVectorDXFScale)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFScale, self.doubleSpinBoxVectorDXFLessThan)
        MainWindow.setTabOrder(self.doubleSpinBoxVectorDXFLessThan, self.pushButtonVectorDXFOutput)
        MainWindow.setTabOrder(self.pushButtonVectorDXFOutput, self.lineEditVectorDXFOutput)
        MainWindow.setTabOrder(self.lineEditVectorDXFOutput, self.pushButtonVectorDXFCreate)
        MainWindow.setTabOrder(self.pushButtonVectorDXFCreate, self.pushButtonCSInputMesh)
        MainWindow.setTabOrder(self.pushButtonCSInputMesh, self.lineEditCSInputMesh)
        MainWindow.setTabOrder(self.lineEditCSInputMesh, self.pushButtonCSInputDefinition)
        MainWindow.setTabOrder(self.pushButtonCSInputDefinition, self.lineEditCSInputDefinition)
        MainWindow.setTabOrder(self.lineEditCSInputDefinition, self.pushButtonCSInputResults)
        MainWindow.setTabOrder(self.pushButtonCSInputResults, self.lineEditCSInputResults)
        MainWindow.setTabOrder(self.lineEditCSInputResults, self.spinBoxCSTime)
        MainWindow.setTabOrder(self.spinBoxCSTime, self.spinBoxCSFlow)
        MainWindow.setTabOrder(self.spinBoxCSFlow, self.doubleSpinBoxCSSizeFactor)
        MainWindow.setTabOrder(self.doubleSpinBoxCSSizeFactor, self.lineEditCSInputPrefix)
        MainWindow.setTabOrder(self.lineEditCSInputPrefix, self.lineEditCSInputSuffix)
        MainWindow.setTabOrder(self.lineEditCSInputSuffix, self.checkBoxCSOutputFormatted)
        MainWindow.setTabOrder(self.checkBoxCSOutputFormatted, self.pushButtonCSOutputFormatted)
        MainWindow.setTabOrder(self.pushButtonCSOutputFormatted, self.lineEditCSOutputFormatted)
        MainWindow.setTabOrder(self.lineEditCSOutputFormatted, self.checkBoxCSOutputCS)
        MainWindow.setTabOrder(self.checkBoxCSOutputCS, self.pushButtonCSOutputCS)
        MainWindow.setTabOrder(self.pushButtonCSOutputCS, self.lineEditCSOutputCS)
        MainWindow.setTabOrder(self.lineEditCSOutputCS, self.pushButtonCSCreate)
        MainWindow.setTabOrder(self.pushButtonCSCreate, self.pushButton2dmInput)
        MainWindow.setTabOrder(self.pushButton2dmInput, self.lineEdit2dmInput)
        MainWindow.setTabOrder(self.lineEdit2dmInput, self.checkBox2dmImpermeable)
        MainWindow.setTabOrder(self.checkBox2dmImpermeable, self.spinBox2dmImpermeable)
        MainWindow.setTabOrder(self.spinBox2dmImpermeable, self.pushButton2dmInputData)
        MainWindow.setTabOrder(self.pushButton2dmInputData, self.lineEdit2dmInputData)
        MainWindow.setTabOrder(self.lineEdit2dmInputData, self.checkBox2dmBottom)
        MainWindow.setTabOrder(self.checkBox2dmBottom, self.pushButton2dmBottom)
        MainWindow.setTabOrder(self.pushButton2dmBottom, self.lineEdit2dmBottom)
        MainWindow.setTabOrder(self.lineEdit2dmBottom, self.checkBox2dmBottomFriction)
        MainWindow.setTabOrder(self.checkBox2dmBottomFriction, self.pushButton2dmBottomFriction)
        MainWindow.setTabOrder(self.pushButton2dmBottomFriction, self.lineEdit2dmBottomFriction)
        MainWindow.setTabOrder(self.lineEdit2dmBottomFriction, self.checkBox2dmWaterSurface)
        MainWindow.setTabOrder(self.checkBox2dmWaterSurface, self.pushButton2dmWaterSurface)
        MainWindow.setTabOrder(self.pushButton2dmWaterSurface, self.lineEdit2dmWaterSurface)
        MainWindow.setTabOrder(self.lineEdit2dmWaterSurface, self.checkBox2dmWaterDepth)
        MainWindow.setTabOrder(self.checkBox2dmWaterDepth, self.pushButton2dmWaterDepth)
        MainWindow.setTabOrder(self.pushButton2dmWaterDepth, self.lineEdit2dmWaterDepth)
        MainWindow.setTabOrder(self.lineEdit2dmWaterDepth, self.checkBox2dmCulvertHeight)
        MainWindow.setTabOrder(self.checkBox2dmCulvertHeight, self.pushButton2dmCulvertHeight)
        MainWindow.setTabOrder(self.pushButton2dmCulvertHeight, self.lineEdit2dmCulvertHeight)
        MainWindow.setTabOrder(self.lineEdit2dmCulvertHeight, self.checkBox2dmNS1)
        MainWindow.setTabOrder(self.checkBox2dmNS1, self.pushButton2dmNS1)
        MainWindow.setTabOrder(self.pushButton2dmNS1, self.lineEdit2dmNS1)
        MainWindow.setTabOrder(self.lineEdit2dmNS1, self.checkBox2dmNS2)
        MainWindow.setTabOrder(self.checkBox2dmNS2, self.pushButton2dmNS2)
        MainWindow.setTabOrder(self.pushButton2dmNS2, self.lineEdit2dmNS2)
        MainWindow.setTabOrder(self.lineEdit2dmNS2, self.checkBox2dmNS3)
        MainWindow.setTabOrder(self.checkBox2dmNS3, self.pushButton2dmNS3)
        MainWindow.setTabOrder(self.pushButton2dmNS3, self.lineEdit2dmNS3)
        MainWindow.setTabOrder(self.lineEdit2dmNS3, self.checkBox2dmNS4)
        MainWindow.setTabOrder(self.checkBox2dmNS4, self.pushButton2dmNS4)
        MainWindow.setTabOrder(self.pushButton2dmNS4, self.lineEdit2dmNS4)
        MainWindow.setTabOrder(self.lineEdit2dmNS4, self.checkBox2dmNS5)
        MainWindow.setTabOrder(self.checkBox2dmNS5, self.pushButton2dmNS5)
        MainWindow.setTabOrder(self.pushButton2dmNS5, self.lineEdit2dmNS5)
        MainWindow.setTabOrder(self.lineEdit2dmNS5, self.checkBox2dmNS6)
        MainWindow.setTabOrder(self.checkBox2dmNS6, self.pushButton2dmNS6)
        MainWindow.setTabOrder(self.pushButton2dmNS6, self.lineEdit2dmNS6)
        MainWindow.setTabOrder(self.lineEdit2dmNS6, self.checkBox2dmNS7)
        MainWindow.setTabOrder(self.checkBox2dmNS7, self.pushButton2dmNS7)
        MainWindow.setTabOrder(self.pushButton2dmNS7, self.lineEdit2dmNS7)
        MainWindow.setTabOrder(self.lineEdit2dmNS7, self.pushButton2dmConvert)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ChEsher 1.0", None))
        self.doubleSpinBoxVectorDXFScale.setToolTip(_translate("MainWindow", "factor from amplitude to vector length", None))
        self.doubleSpinBoxVectorDXFVMax.setToolTip(_translate("MainWindow", "higher values are ignored", None))
        self.doubleSpinBoxVectorDXFDY.setToolTip(_translate("MainWindow", "grid interval in y-direction", None))
        self.label_41.setText(_translate("MainWindow", "Minimum and maximum value of magnitude:", None))
        self.label_37.setText(_translate("MainWindow", "Outputs:", None))
        self.doubleSpinBoxVectorDXFVMin.setToolTip(_translate("MainWindow", "lower values are ignored", None))
        self.label_36.setText(_translate("MainWindow", "Size factor:", None))
        self.pushButtonVectorDXFOutput.setText(_translate("MainWindow", "...", None))
        self.label_38.setText(_translate("MainWindow", "DXF grid file:", None))
        self.pushButtonVectorDXFCreate.setText(_translate("MainWindow", "Let\'s go!", None))
        self.pushButtonVectorDXFInput.setText(_translate("MainWindow", "...", None))
        self.label_43.setText(_translate("MainWindow", "2D T3 Vector Mesh:", None))
        self.label_42.setText(_translate("MainWindow", "Inputs:", None))
        self.label_35.setText(_translate("MainWindow", "X-Spacing:", None))
        self.doubleSpinBoxVectorDXFDX.setToolTip(_translate("MainWindow", "grid interval in x-direction", None))
        self.label_39.setText(_translate("MainWindow", "Y-Spacing:", None))
        self.label_27.setText(_translate("MainWindow", "Ignore values less than (±):", None))
        self.doubleSpinBoxVectorDXFLessThan.setToolTip(_translate("MainWindow", "ignore values less than given difference from zero", None))
        self.checkBoxCSOutputCS.setText(_translate("MainWindow", "Control section file:", None))
        self.checkBoxCSOutputFormatted.setText(_translate("MainWindow", "Formatted data file:", None))
        self.pushButtonCSInputResults.setText(_translate("MainWindow", "...", None))
        self.pushButtonCSOutputFormatted.setText(_translate("MainWindow", "...", None))
        self.label_49.setText(_translate("MainWindow", "Control sections results file:", None))
        self.label_50.setText(_translate("MainWindow", "Decimal points for time steps:", None))
        self.pushButtonCSOutputCS.setText(_translate("MainWindow", "...", None))
        self.label_44.setText(_translate("MainWindow", "Control sections definition file:", None))
        self.label_51.setText(_translate("MainWindow", "Decimal points for flow:", None))
        self.label_46.setText(_translate("MainWindow", "Outputs:", None))
        self.label_45.setText(_translate("MainWindow", "2D T3 Mesh:", None))
        self.label_47.setText(_translate("MainWindow", "Inputs:", None))
        self.pushButtonCSInputDefinition.setText(_translate("MainWindow", "...", None))
        self.pushButtonCSInputMesh.setText(_translate("MainWindow", "...", None))
        self.pushButtonCSCreate.setText(_translate("MainWindow", "Let\'s go!", None))
        self.lineEditCSInputPrefix.setText(_translate("MainWindow", "Q = ", None))
        self.label_28.setText(_translate("MainWindow", "Flow prefix:", None))
        self.label_31.setText(_translate("MainWindow", "Size factor:", None))
        self.doubleSpinBoxCSSizeFactor.setToolTip(_translate("MainWindow", "text size", None))
        self.label_40.setText(_translate("MainWindow", "Flow suffix:", None))
        self.lineEditCSInputSuffix.setText(_translate("MainWindow", " m3/s", None))
        self.checkBox2dmNS6.setText(_translate("MainWindow", "Node string 6:", None))
        self.checkBox2dmNS1.setText(_translate("MainWindow", "Node string 1:", None))
        self.checkBox2dmNS2.setText(_translate("MainWindow", "Node string 2:", None))
        self.pushButton2dmNS5.setText(_translate("MainWindow", "...", None))
        self.checkBox2dmBottomFriction.setText(_translate("MainWindow", "Bottom friction:", None))
        self.label_19.setText(_translate("MainWindow", "Water surface data file:", None))
        self.label_17.setText(_translate("MainWindow", "2D mesh file:", None))
        self.pushButton2dmCulvertHeight.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmBottom.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmWaterSurface.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmNS4.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmInputData.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmInput.setText(_translate("MainWindow", "...", None))
        self.checkBox2dmNS5.setText(_translate("MainWindow", "Node string 5:", None))
        self.checkBox2dmWaterDepth.setText(_translate("MainWindow", "Water depth:", None))
        self.checkBox2dmCulvertHeight.setText(_translate("MainWindow", "Culvert height:", None))
        self.pushButton2dmNS1.setText(_translate("MainWindow", "...", None))
        self.checkBox2dmNS4.setText(_translate("MainWindow", "Node string 4:", None))
        self.label_16.setText(_translate("MainWindow", "Inputs:", None))
        self.pushButton2dmNS2.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmBottomFriction.setText(_translate("MainWindow", "...", None))
        self.checkBox2dmWaterSurface.setText(_translate("MainWindow", "Water surface:", None))
        self.checkBox2dmBottom.setText(_translate("MainWindow", "Bottom:", None))
        self.checkBox2dmNS3.setText(_translate("MainWindow", "Node string 3:", None))
        self.pushButton2dmNS3.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmWaterDepth.setText(_translate("MainWindow", "...", None))
        self.label_18.setText(_translate("MainWindow", "Outputs:", None))
        self.pushButton2dmNS7.setText(_translate("MainWindow", "...", None))
        self.pushButton2dmNS6.setText(_translate("MainWindow", "...", None))
        self.checkBox2dmNS7.setText(_translate("MainWindow", "Node string 7:", None))
        self.label_10.setText(_translate("MainWindow", "Material-ID: ", None))
        self.checkBox2dmImpermeable.setText(_translate("MainWindow", "Impermeable elements", None))
        self.pushButton2dmConvert.setText(_translate("MainWindow", "Let\'s go!", None))
        self.checkBoxCont2DXFOutputLine.setText(_translate("MainWindow", "DXF file isolines:", None))
        self.checkBoxCont2DXFOutputSolid.setText(_translate("MainWindow", "DXF file filled contours:", None))
        self.checkBoxCont2DXFOutputLegend.setText(_translate("MainWindow", "create legend", None))
        self.label_57.setText(_translate("MainWindow", "Inputs:", None))
        self.label_20.setText(_translate("MainWindow", "2D T3 Mesh:", None))
        self.pushButtonCont2DXFInput.setText(_translate("MainWindow", "...", None))
        self.pushButtonCont2DXFAdd.setToolTip(_translate("MainWindow", "add layer to table", None))
        self.pushButtonCont2DXFAdd.setText(_translate("MainWindow", "add", None))
        self.pushButtonCont2DXFDelete.setToolTip(_translate("MainWindow", "delete selected layer from table", None))
        self.pushButtonCont2DXFDelete.setText(_translate("MainWindow", "delete", None))
        self.pushButtonCont2DXFColour.setToolTip(_translate("MainWindow", "set colour for selected level", None))
        self.pushButtonCont2DXFColour.setText(_translate("MainWindow", "colour", None))
        self.label_60.setText(_translate("MainWindow", "Level:", None))
        self.label_59.setText(_translate("MainWindow", "Levels:", None))
        self.pushButtonCont2DXFLoad.setToolTip(_translate("MainWindow", "load legend from EnSim ColourScale definition file (*.cs1)", None))
        self.pushButtonCont2DXFLoad.setText(_translate("MainWindow", "load", None))
        self.pushButtonCont2DXFSave.setToolTip(_translate("MainWindow", "save legend as EnSim ColourScale definition file (*.cs1)", None))
        self.pushButtonCont2DXFSave.setText(_translate("MainWindow", "save", None))
        self.pushButtonCont2DXFDefault.setToolTip(_translate("MainWindow", "set default legend", None))
        self.pushButtonCont2DXFDefault.setText(_translate("MainWindow", "set default", None))
        self.label_58.setText(_translate("MainWindow", "Outputs:", None))
        self.label_61.setText(_translate("MainWindow", "DXF layer name:", None))
        item = self.tableWidgetCont2DXF.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetCont2DXF.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetCont2DXF.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Colour", None))
        self.pushButtonCont2DXFCreate.setText(_translate("MainWindow", "Let\'s go!", None))
        self.pushButtonCont2DXFOutputLine.setText(_translate("MainWindow", "...", None))
        self.pushButtonCont2DXFOutputSolid.setText(_translate("MainWindow", "...", None))
        self.label_48.setText(_translate("MainWindow", "Legend title:", None))
        self.label_62.setText(_translate("MainWindow", "Legend subtitle:", None))
        self.label_63.setText(_translate("MainWindow", "Separator:", None))
        self.lineEditCont2DXFOutputLegendSeparator.setText(_translate("MainWindow", " - ", None))
        self.checkBoxCont2DXFOutputLegendReverse.setText(_translate("MainWindow", "create legend in reverse order", None))
        self.label_67.setText(_translate("MainWindow", "Inputs:", None))
        self.label_64.setText(_translate("MainWindow", "2D T3 Scalar Mesh:", None))
        self.pushButtonTubeInputMesh.setText(_translate("MainWindow", "...", None))
        self.label_68.setText(_translate("MainWindow", "Line Set:", None))
        self.pushButtonTubeInputLineSet.setText(_translate("MainWindow", "...", None))
        self.label_69.setText(_translate("MainWindow", "Default values:", None))
        self.label_65.setText(_translate("MainWindow", "Outputs:", None))
        self.label_66.setText(_translate("MainWindow", "Textfile:", None))
        self.pushButtonTubeOutput.setText(_translate("MainWindow", "...", None))
        self.label_78.setText(_translate("MainWindow", "Rel =", None))
        self.label_70.setText(_translate("MainWindow", "Ce1 =", None))
        self.label_71.setText(_translate("MainWindow", "Ce2 =", None))
        self.label_72.setText(_translate("MainWindow", "Cs1 =", None))
        self.label_73.setText(_translate("MainWindow", "Cs2 =", None))
        self.label_74.setText(_translate("MainWindow", "Lrg =", None))
        self.label_75.setText(_translate("MainWindow", "Hau =", None))
        self.label_76.setText(_translate("MainWindow", "Clp =", None))
        self.label_77.setText(_translate("MainWindow", "L12 =", None))
        self.pushButtonTubeCreate.setText(_translate("MainWindow", "Let\'s go!", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionChEsher.setText(_translate("MainWindow", "ChEsher ", None))
        self.actionAbout_ChEsher.setText(_translate("MainWindow", "About ChEsher", None))

import resource_rc
