# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiProfilesDXF.ui'
#
# Created: Sun Jul 24 18:53:59 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProfilesDXF(object):
    def setupUi(self, ProfilesDXF):
        ProfilesDXF.setObjectName(_fromUtf8("ProfilesDXF"))
        ProfilesDXF.resize(627, 759)
        self.gridLayout = QtGui.QGridLayout(ProfilesDXF)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButtonAdd = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.gridLayout_10.addWidget(self.pushButtonAdd, 0, 1, 1, 1)
        self.pushButtonDelete = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.gridLayout_10.addWidget(self.pushButtonDelete, 0, 2, 1, 1)
        self.pushButtonColour = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonColour.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonColour.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonColour.setObjectName(_fromUtf8("pushButtonColour"))
        self.gridLayout_10.addWidget(self.pushButtonColour, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 4, 1, 1)
        self.label_60 = QtGui.QLabel(ProfilesDXF)
        self.label_60.setMinimumSize(QtCore.QSize(70, 0))
        self.label_60.setIndent(18)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_10.addWidget(self.label_60, 0, 0, 1, 1)
        self.pushButtonInputWaterSurface = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonInputWaterSurface.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputWaterSurface.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputWaterSurface.setObjectName(_fromUtf8("pushButtonInputWaterSurface"))
        self.gridLayout_10.addWidget(self.pushButtonInputWaterSurface, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 8, 0, 1, 5)
        self.label_103 = QtGui.QLabel(ProfilesDXF)
        self.label_103.setIndent(18)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 2, 0, 1, 2)
        self.label_105 = QtGui.QLabel(ProfilesDXF)
        self.label_105.setIndent(18)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout.addWidget(self.label_105, 1, 0, 1, 2)
        self.pushButtonInputReach = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonInputReach.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputReach.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputReach.setObjectName(_fromUtf8("pushButtonInputReach"))
        self.gridLayout.addWidget(self.pushButtonInputReach, 2, 2, 1, 1)
        self.label_106 = QtGui.QLabel(ProfilesDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_106.setFont(font)
        self.label_106.setIndent(-4)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout.addWidget(self.label_106, 0, 0, 1, 1)
        self.label_110 = QtGui.QLabel(ProfilesDXF)
        self.label_110.setIndent(18)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout.addWidget(self.label_110, 6, 0, 1, 2)
        self.tableWidget = QtGui.QTableWidget(ProfilesDXF)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 9, 0, 1, 5)
        self.spinBoxDecimal = QtGui.QSpinBox(ProfilesDXF)
        self.spinBoxDecimal.setMaximumSize(QtCore.QSize(50, 16777215))
        self.spinBoxDecimal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxDecimal.setMaximum(12)
        self.spinBoxDecimal.setProperty("value", 3)
        self.spinBoxDecimal.setObjectName(_fromUtf8("spinBoxDecimal"))
        self.gridLayout.addWidget(self.spinBoxDecimal, 6, 4, 1, 1)
        self.lineEditInputReach = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditInputReach.setObjectName(_fromUtf8("lineEditInputReach"))
        self.gridLayout.addWidget(self.lineEditInputReach, 2, 4, 1, 1)
        self.lineEditOutputProfiles = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditOutputProfiles.setEnabled(False)
        self.lineEditOutputProfiles.setObjectName(_fromUtf8("lineEditOutputProfiles"))
        self.gridLayout.addWidget(self.lineEditOutputProfiles, 12, 3, 1, 2)
        self.lineEditOutputPlan = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditOutputPlan.setEnabled(False)
        self.lineEditOutputPlan.setObjectName(_fromUtf8("lineEditOutputPlan"))
        self.gridLayout.addWidget(self.lineEditOutputPlan, 15, 3, 1, 2)
        self.checkBoxOutputPlan = QtGui.QCheckBox(ProfilesDXF)
        self.checkBoxOutputPlan.setObjectName(_fromUtf8("checkBoxOutputPlan"))
        self.gridLayout.addWidget(self.checkBoxOutputPlan, 15, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(500, 227, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 10, 0, 1, 5)
        self.label_107 = QtGui.QLabel(ProfilesDXF)
        self.label_107.setIndent(18)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout.addWidget(self.label_107, 3, 0, 1, 2)
        self.label_108 = QtGui.QLabel(ProfilesDXF)
        self.label_108.setIndent(18)
        self.label_108.setObjectName(_fromUtf8("label_108"))
        self.gridLayout.addWidget(self.label_108, 4, 0, 1, 2)
        self.checkBoxOutputProfiles = QtGui.QCheckBox(ProfilesDXF)
        self.checkBoxOutputProfiles.setObjectName(_fromUtf8("checkBoxOutputProfiles"))
        self.gridLayout.addWidget(self.checkBoxOutputProfiles, 12, 0, 1, 2)
        self.pushButtonOutputPlan = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonOutputPlan.setEnabled(False)
        self.pushButtonOutputPlan.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputPlan.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputPlan.setObjectName(_fromUtf8("pushButtonOutputPlan"))
        self.gridLayout.addWidget(self.pushButtonOutputPlan, 15, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(609, 255, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 16, 0, 1, 5)
        self.pushButtonInputProfiles = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonInputProfiles.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputProfiles.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputProfiles.setObjectName(_fromUtf8("pushButtonInputProfiles"))
        self.gridLayout.addWidget(self.pushButtonInputProfiles, 1, 2, 1, 1)
        self.pushButtonInputBottom = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonInputBottom.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputBottom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputBottom.setObjectName(_fromUtf8("pushButtonInputBottom"))
        self.gridLayout.addWidget(self.pushButtonInputBottom, 3, 2, 1, 1)
        self.pushButtonOutputProfiles = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonOutputProfiles.setEnabled(False)
        self.pushButtonOutputProfiles.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputProfiles.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputProfiles.setObjectName(_fromUtf8("pushButtonOutputProfiles"))
        self.gridLayout.addWidget(self.pushButtonOutputProfiles, 12, 2, 1, 1)
        self.lineEditInputProfiles = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditInputProfiles.setObjectName(_fromUtf8("lineEditInputProfiles"))
        self.gridLayout.addWidget(self.lineEditInputProfiles, 1, 4, 1, 1)
        self.label_104 = QtGui.QLabel(ProfilesDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_104.setFont(font)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout.addWidget(self.label_104, 11, 0, 1, 1)
        self.lineEditInputBottom = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditInputBottom.setObjectName(_fromUtf8("lineEditInputBottom"))
        self.gridLayout.addWidget(self.lineEditInputBottom, 3, 4, 1, 1)
        self.pushButtonCreate = QtGui.QPushButton(ProfilesDXF)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 17, 0, 1, 5)
        self.lineEditInputReachName = QtGui.QLineEdit(ProfilesDXF)
        self.lineEditInputReachName.setObjectName(_fromUtf8("lineEditInputReachName"))
        self.gridLayout.addWidget(self.lineEditInputReachName, 4, 4, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 7, 0, 1, 5)

        self.retranslateUi(ProfilesDXF)
        QtCore.QMetaObject.connectSlotsByName(ProfilesDXF)

    def retranslateUi(self, ProfilesDXF):
        ProfilesDXF.setWindowTitle(_translate("ProfilesDXF", "Form", None))
        self.pushButtonAdd.setToolTip(_translate("ProfilesDXF", "add layer to table", None))
        self.pushButtonAdd.setText(_translate("ProfilesDXF", "add", None))
        self.pushButtonDelete.setToolTip(_translate("ProfilesDXF", "delete selected layer from table", None))
        self.pushButtonDelete.setText(_translate("ProfilesDXF", "delete", None))
        self.pushButtonColour.setToolTip(_translate("ProfilesDXF", "set colour for selected level", None))
        self.pushButtonColour.setText(_translate("ProfilesDXF", "colour", None))
        self.label_60.setText(_translate("ProfilesDXF", "Water Surface mesh files:", None))
        self.pushButtonInputWaterSurface.setText(_translate("ProfilesDXF", "...", None))
        self.label_103.setText(_translate("ProfilesDXF", "Channel reach file:", None))
        self.label_105.setText(_translate("ProfilesDXF", "Channel profiles file:", None))
        self.pushButtonInputReach.setText(_translate("ProfilesDXF", "...", None))
        self.label_106.setText(_translate("ProfilesDXF", "Inputs:", None))
        self.label_110.setText(_translate("ProfilesDXF", "Decimal places:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ProfilesDXF", "Water Surface Mesh", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ProfilesDXF", "Name", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ProfilesDXF", "Colour", None))
        self.checkBoxOutputPlan.setText(_translate("ProfilesDXF", "DXF file plan view:", None))
        self.label_107.setText(_translate("ProfilesDXF", "Bottom mesh file:", None))
        self.label_108.setText(_translate("ProfilesDXF", "Reach name:", None))
        self.checkBoxOutputProfiles.setText(_translate("ProfilesDXF", "DXF file profiles:", None))
        self.pushButtonOutputPlan.setText(_translate("ProfilesDXF", "...", None))
        self.pushButtonInputProfiles.setText(_translate("ProfilesDXF", "...", None))
        self.pushButtonInputBottom.setText(_translate("ProfilesDXF", "...", None))
        self.pushButtonOutputProfiles.setText(_translate("ProfilesDXF", "...", None))
        self.label_104.setText(_translate("ProfilesDXF", "Outputs:", None))
        self.pushButtonCreate.setText(_translate("ProfilesDXF", "Let\'s go!", None))

