# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2DM2BK.ui'
#
# Created: Sat Nov 05 21:28:55 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TwoDM2BK(object):
    def setupUi(self, TwoDM2BK):
        TwoDM2BK.setObjectName(_fromUtf8("TwoDM2BK"))
        TwoDM2BK.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(TwoDM2BK)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_16 = QtGui.QLabel(TwoDM2BK)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_16.setFont(font)
        self.label_16.setIndent(-4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(TwoDM2BK)
        self.label_17.setIndent(18)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.pushButtonInput = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonInput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayout.addWidget(self.pushButtonInput, 1, 1, 1, 1)
        self.lineEditInput = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayout.addWidget(self.lineEditInput, 1, 2, 1, 3)
        self.checkBoxImpermeable = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxImpermeable.setObjectName(_fromUtf8("checkBoxImpermeable"))
        self.gridLayout.addWidget(self.checkBoxImpermeable, 2, 0, 1, 2)
        self.label_10 = QtGui.QLabel(TwoDM2BK)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.spinBoxImpermeable = QtGui.QSpinBox(TwoDM2BK)
        self.spinBoxImpermeable.setEnabled(False)
        self.spinBoxImpermeable.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxImpermeable.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxImpermeable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxImpermeable.setMinimum(-999999999)
        self.spinBoxImpermeable.setMaximum(999999999)
        self.spinBoxImpermeable.setObjectName(_fromUtf8("spinBoxImpermeable"))
        self.gridLayout.addWidget(self.spinBoxImpermeable, 2, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(261, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(TwoDM2BK)
        self.label_19.setIndent(18)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.pushButtonInputData = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonInputData.setEnabled(True)
        self.pushButtonInputData.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputData.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputData.setObjectName(_fromUtf8("pushButtonInputData"))
        self.gridLayout.addWidget(self.pushButtonInputData, 3, 1, 1, 1)
        self.lineEditInputData = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditInputData.setEnabled(True)
        self.lineEditInputData.setObjectName(_fromUtf8("lineEditInputData"))
        self.gridLayout.addWidget(self.lineEditInputData, 3, 2, 1, 3)
        self.label_18 = QtGui.QLabel(TwoDM2BK)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.checkBoxBottom = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxBottom.setObjectName(_fromUtf8("checkBoxBottom"))
        self.gridLayout.addWidget(self.checkBoxBottom, 6, 0, 1, 1)
        self.pushButtonBottom = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonBottom.setEnabled(False)
        self.pushButtonBottom.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonBottom.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonBottom.setObjectName(_fromUtf8("pushButtonBottom"))
        self.gridLayout.addWidget(self.pushButtonBottom, 6, 1, 1, 1)
        self.lineEditBottom = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditBottom.setEnabled(False)
        self.lineEditBottom.setObjectName(_fromUtf8("lineEditBottom"))
        self.gridLayout.addWidget(self.lineEditBottom, 6, 2, 1, 3)
        self.checkBoxBottomFriction = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxBottomFriction.setObjectName(_fromUtf8("checkBoxBottomFriction"))
        self.gridLayout.addWidget(self.checkBoxBottomFriction, 7, 0, 1, 1)
        self.pushButtonBottomFriction = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonBottomFriction.setEnabled(False)
        self.pushButtonBottomFriction.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonBottomFriction.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonBottomFriction.setObjectName(_fromUtf8("pushButtonBottomFriction"))
        self.gridLayout.addWidget(self.pushButtonBottomFriction, 7, 1, 1, 1)
        self.lineEditBottomFriction = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditBottomFriction.setEnabled(False)
        self.lineEditBottomFriction.setObjectName(_fromUtf8("lineEditBottomFriction"))
        self.gridLayout.addWidget(self.lineEditBottomFriction, 7, 2, 1, 3)
        self.checkBoxWaterSurface = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxWaterSurface.setObjectName(_fromUtf8("checkBoxWaterSurface"))
        self.gridLayout.addWidget(self.checkBoxWaterSurface, 8, 0, 1, 1)
        self.pushButtonWaterSurface = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonWaterSurface.setEnabled(False)
        self.pushButtonWaterSurface.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonWaterSurface.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonWaterSurface.setObjectName(_fromUtf8("pushButtonWaterSurface"))
        self.gridLayout.addWidget(self.pushButtonWaterSurface, 8, 1, 1, 1)
        self.lineEditWaterSurface = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditWaterSurface.setEnabled(False)
        self.lineEditWaterSurface.setObjectName(_fromUtf8("lineEditWaterSurface"))
        self.gridLayout.addWidget(self.lineEditWaterSurface, 8, 2, 1, 3)
        self.checkBoxWaterDepth = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxWaterDepth.setObjectName(_fromUtf8("checkBoxWaterDepth"))
        self.gridLayout.addWidget(self.checkBoxWaterDepth, 9, 0, 1, 1)
        self.pushButtonWaterDepth = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonWaterDepth.setEnabled(False)
        self.pushButtonWaterDepth.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonWaterDepth.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonWaterDepth.setObjectName(_fromUtf8("pushButtonWaterDepth"))
        self.gridLayout.addWidget(self.pushButtonWaterDepth, 9, 1, 1, 1)
        self.lineEditWaterDepth = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditWaterDepth.setEnabled(False)
        self.lineEditWaterDepth.setObjectName(_fromUtf8("lineEditWaterDepth"))
        self.gridLayout.addWidget(self.lineEditWaterDepth, 9, 2, 1, 3)
        self.checkBoxCulvertHeight = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxCulvertHeight.setObjectName(_fromUtf8("checkBoxCulvertHeight"))
        self.gridLayout.addWidget(self.checkBoxCulvertHeight, 10, 0, 1, 1)
        self.pushButtonCulvertHeight = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonCulvertHeight.setEnabled(False)
        self.pushButtonCulvertHeight.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonCulvertHeight.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonCulvertHeight.setObjectName(_fromUtf8("pushButtonCulvertHeight"))
        self.gridLayout.addWidget(self.pushButtonCulvertHeight, 10, 1, 1, 1)
        self.lineEditCulvertHeight = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditCulvertHeight.setEnabled(False)
        self.lineEditCulvertHeight.setObjectName(_fromUtf8("lineEditCulvertHeight"))
        self.gridLayout.addWidget(self.lineEditCulvertHeight, 10, 2, 1, 3)
        self.checkBoxNS1 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS1.setObjectName(_fromUtf8("checkBoxNS1"))
        self.gridLayout.addWidget(self.checkBoxNS1, 11, 0, 1, 1)
        self.pushButtonNS1 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS1.setEnabled(False)
        self.pushButtonNS1.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS1.setObjectName(_fromUtf8("pushButtonNS1"))
        self.gridLayout.addWidget(self.pushButtonNS1, 11, 1, 1, 1)
        self.lineEditNS1 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS1.setEnabled(False)
        self.lineEditNS1.setObjectName(_fromUtf8("lineEditNS1"))
        self.gridLayout.addWidget(self.lineEditNS1, 11, 2, 1, 3)
        self.checkBoxNS2 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS2.setObjectName(_fromUtf8("checkBoxNS2"))
        self.gridLayout.addWidget(self.checkBoxNS2, 12, 0, 1, 1)
        self.pushButtonNS2 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS2.setEnabled(False)
        self.pushButtonNS2.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS2.setObjectName(_fromUtf8("pushButtonNS2"))
        self.gridLayout.addWidget(self.pushButtonNS2, 12, 1, 1, 1)
        self.lineEditNS2 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS2.setEnabled(False)
        self.lineEditNS2.setObjectName(_fromUtf8("lineEditNS2"))
        self.gridLayout.addWidget(self.lineEditNS2, 12, 2, 1, 3)
        self.checkBoxNS3 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS3.setObjectName(_fromUtf8("checkBoxNS3"))
        self.gridLayout.addWidget(self.checkBoxNS3, 13, 0, 1, 1)
        self.pushButtonNS3 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS3.setEnabled(False)
        self.pushButtonNS3.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS3.setObjectName(_fromUtf8("pushButtonNS3"))
        self.gridLayout.addWidget(self.pushButtonNS3, 13, 1, 1, 1)
        self.lineEditNS3 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS3.setEnabled(False)
        self.lineEditNS3.setObjectName(_fromUtf8("lineEditNS3"))
        self.gridLayout.addWidget(self.lineEditNS3, 13, 2, 1, 3)
        self.checkBoxNS4 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS4.setObjectName(_fromUtf8("checkBoxNS4"))
        self.gridLayout.addWidget(self.checkBoxNS4, 14, 0, 1, 1)
        self.pushButtonNS4 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS4.setEnabled(False)
        self.pushButtonNS4.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS4.setObjectName(_fromUtf8("pushButtonNS4"))
        self.gridLayout.addWidget(self.pushButtonNS4, 14, 1, 1, 1)
        self.lineEditNS4 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS4.setEnabled(False)
        self.lineEditNS4.setObjectName(_fromUtf8("lineEditNS4"))
        self.gridLayout.addWidget(self.lineEditNS4, 14, 2, 1, 3)
        self.checkBoxNS5 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS5.setObjectName(_fromUtf8("checkBoxNS5"))
        self.gridLayout.addWidget(self.checkBoxNS5, 15, 0, 1, 1)
        self.pushButtonNS5 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS5.setEnabled(False)
        self.pushButtonNS5.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS5.setObjectName(_fromUtf8("pushButtonNS5"))
        self.gridLayout.addWidget(self.pushButtonNS5, 15, 1, 1, 1)
        self.lineEditNS5 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS5.setEnabled(False)
        self.lineEditNS5.setObjectName(_fromUtf8("lineEditNS5"))
        self.gridLayout.addWidget(self.lineEditNS5, 15, 2, 1, 3)
        self.checkBoxNS6 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS6.setObjectName(_fromUtf8("checkBoxNS6"))
        self.gridLayout.addWidget(self.checkBoxNS6, 16, 0, 1, 1)
        self.pushButtonNS6 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS6.setEnabled(False)
        self.pushButtonNS6.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS6.setObjectName(_fromUtf8("pushButtonNS6"))
        self.gridLayout.addWidget(self.pushButtonNS6, 16, 1, 1, 1)
        self.lineEditNS6 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS6.setEnabled(False)
        self.lineEditNS6.setObjectName(_fromUtf8("lineEditNS6"))
        self.gridLayout.addWidget(self.lineEditNS6, 16, 2, 1, 3)
        self.checkBoxNS7 = QtGui.QCheckBox(TwoDM2BK)
        self.checkBoxNS7.setObjectName(_fromUtf8("checkBoxNS7"))
        self.gridLayout.addWidget(self.checkBoxNS7, 17, 0, 1, 1)
        self.pushButtonNS7 = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonNS7.setEnabled(False)
        self.pushButtonNS7.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonNS7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonNS7.setObjectName(_fromUtf8("pushButtonNS7"))
        self.gridLayout.addWidget(self.pushButtonNS7, 17, 1, 1, 1)
        self.lineEditNS7 = QtGui.QLineEdit(TwoDM2BK)
        self.lineEditNS7.setEnabled(False)
        self.lineEditNS7.setObjectName(_fromUtf8("lineEditNS7"))
        self.gridLayout.addWidget(self.lineEditNS7, 17, 2, 1, 3)
        self.pushButtonCreate = QtGui.QPushButton(TwoDM2BK)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 19, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(618, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 18, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(618, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 5)

        self.retranslateUi(TwoDM2BK)
        QtCore.QMetaObject.connectSlotsByName(TwoDM2BK)

    def retranslateUi(self, TwoDM2BK):
        TwoDM2BK.setWindowTitle(_translate("TwoDM2BK", "Form", None))
        self.label_16.setText(_translate("TwoDM2BK", "Inputs:", None))
        self.label_17.setText(_translate("TwoDM2BK", "2D mesh file:", None))
        self.pushButtonInput.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxImpermeable.setText(_translate("TwoDM2BK", "Impermeable elements", None))
        self.label_10.setText(_translate("TwoDM2BK", "Material-ID: ", None))
        self.label_19.setText(_translate("TwoDM2BK", "Water surface data file:", None))
        self.pushButtonInputData.setText(_translate("TwoDM2BK", "...", None))
        self.label_18.setText(_translate("TwoDM2BK", "Outputs:", None))
        self.checkBoxBottom.setText(_translate("TwoDM2BK", "Bottom:", None))
        self.pushButtonBottom.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxBottomFriction.setText(_translate("TwoDM2BK", "Bottom friction:", None))
        self.pushButtonBottomFriction.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxWaterSurface.setText(_translate("TwoDM2BK", "Water surface:", None))
        self.pushButtonWaterSurface.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxWaterDepth.setText(_translate("TwoDM2BK", "Water depth:", None))
        self.pushButtonWaterDepth.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxCulvertHeight.setText(_translate("TwoDM2BK", "Culvert height:", None))
        self.pushButtonCulvertHeight.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS1.setText(_translate("TwoDM2BK", "Node string 1:", None))
        self.pushButtonNS1.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS2.setText(_translate("TwoDM2BK", "Node string 2:", None))
        self.pushButtonNS2.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS3.setText(_translate("TwoDM2BK", "Node string 3:", None))
        self.pushButtonNS3.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS4.setText(_translate("TwoDM2BK", "Node string 4:", None))
        self.pushButtonNS4.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS5.setText(_translate("TwoDM2BK", "Node string 5:", None))
        self.pushButtonNS5.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS6.setText(_translate("TwoDM2BK", "Node string 6:", None))
        self.pushButtonNS6.setText(_translate("TwoDM2BK", "...", None))
        self.checkBoxNS7.setText(_translate("TwoDM2BK", "Node string 7:", None))
        self.pushButtonNS7.setText(_translate("TwoDM2BK", "...", None))
        self.pushButtonCreate.setText(_translate("TwoDM2BK", "Let\'s go!", None))

