# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiCont2DXF.ui'
#
# Created: Sat Nov 05 22:44:11 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Cont2DXF(object):
    def setupUi(self, Cont2DXF):
        Cont2DXF.setObjectName(_fromUtf8("Cont2DXF"))
        Cont2DXF.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(Cont2DXF)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_57 = QtGui.QLabel(Cont2DXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_57.setFont(font)
        self.label_57.setIndent(-4)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout.addWidget(self.label_57, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(Cont2DXF)
        self.label_20.setIndent(18)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.pushButtonInput = QtGui.QPushButton(Cont2DXF)
        self.pushButtonInput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInput.setObjectName(_fromUtf8("pushButtonInput"))
        self.gridLayout.addWidget(self.pushButtonInput, 1, 1, 1, 1)
        self.lineEditInput = QtGui.QLineEdit(Cont2DXF)
        self.lineEditInput.setObjectName(_fromUtf8("lineEditInput"))
        self.gridLayout.addWidget(self.lineEditInput, 1, 2, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.pushButtonAdd = QtGui.QPushButton(Cont2DXF)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.gridLayout_10.addWidget(self.pushButtonAdd, 0, 1, 1, 1)
        self.pushButtonDelete = QtGui.QPushButton(Cont2DXF)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.gridLayout_10.addWidget(self.pushButtonDelete, 0, 2, 1, 1)
        self.pushButtonColour = QtGui.QPushButton(Cont2DXF)
        self.pushButtonColour.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonColour.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonColour.setObjectName(_fromUtf8("pushButtonColour"))
        self.gridLayout_10.addWidget(self.pushButtonColour, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 4, 1, 1)
        self.label_60 = QtGui.QLabel(Cont2DXF)
        self.label_60.setMinimumSize(QtCore.QSize(70, 0))
        self.label_60.setIndent(18)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_10.addWidget(self.label_60, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 3, 0, 1, 3)
        self.tableWidget = QtGui.QTableWidget(Cont2DXF)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 160))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 4, 0, 1, 3)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_59 = QtGui.QLabel(Cont2DXF)
        self.label_59.setMinimumSize(QtCore.QSize(70, 0))
        self.label_59.setIndent(18)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_11.addWidget(self.label_59, 0, 0, 1, 1)
        self.pushButtonLoad = QtGui.QPushButton(Cont2DXF)
        self.pushButtonLoad.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonLoad.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonLoad.setObjectName(_fromUtf8("pushButtonLoad"))
        self.gridLayout_11.addWidget(self.pushButtonLoad, 0, 1, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(Cont2DXF)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonSave.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout_11.addWidget(self.pushButtonSave, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 3, 1, 1)
        self.comboBox = QtGui.QComboBox(Cont2DXF)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_11.addWidget(self.comboBox, 0, 4, 1, 1)
        self.pushButtonDefault = QtGui.QPushButton(Cont2DXF)
        self.pushButtonDefault.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDefault.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDefault.setObjectName(_fromUtf8("pushButtonDefault"))
        self.gridLayout_11.addWidget(self.pushButtonDefault, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 5, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_58 = QtGui.QLabel(Cont2DXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout.addWidget(self.label_58, 7, 0, 1, 1)
        self.label_61 = QtGui.QLabel(Cont2DXF)
        self.label_61.setIndent(18)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout.addWidget(self.label_61, 8, 0, 1, 1)
        self.lineEditOutputLayer = QtGui.QLineEdit(Cont2DXF)
        self.lineEditOutputLayer.setObjectName(_fromUtf8("lineEditOutputLayer"))
        self.gridLayout.addWidget(self.lineEditOutputLayer, 8, 2, 1, 1)
        self.checkBoxOutputSolid = QtGui.QCheckBox(Cont2DXF)
        self.checkBoxOutputSolid.setObjectName(_fromUtf8("checkBoxOutputSolid"))
        self.gridLayout.addWidget(self.checkBoxOutputSolid, 9, 0, 1, 1)
        self.pushButtonOutputSolid = QtGui.QPushButton(Cont2DXF)
        self.pushButtonOutputSolid.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputSolid.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputSolid.setObjectName(_fromUtf8("pushButtonOutputSolid"))
        self.gridLayout.addWidget(self.pushButtonOutputSolid, 9, 1, 1, 1)
        self.lineEditOutputSolid = QtGui.QLineEdit(Cont2DXF)
        self.lineEditOutputSolid.setObjectName(_fromUtf8("lineEditOutputSolid"))
        self.gridLayout.addWidget(self.lineEditOutputSolid, 9, 2, 1, 1)
        self.checkBoxOutputLine = QtGui.QCheckBox(Cont2DXF)
        self.checkBoxOutputLine.setObjectName(_fromUtf8("checkBoxOutputLine"))
        self.gridLayout.addWidget(self.checkBoxOutputLine, 10, 0, 1, 1)
        self.pushButtonOutputLine = QtGui.QPushButton(Cont2DXF)
        self.pushButtonOutputLine.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputLine.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputLine.setObjectName(_fromUtf8("pushButtonOutputLine"))
        self.gridLayout.addWidget(self.pushButtonOutputLine, 10, 1, 1, 1)
        self.lineEditOutputLine = QtGui.QLineEdit(Cont2DXF)
        self.lineEditOutputLine.setObjectName(_fromUtf8("lineEditOutputLine"))
        self.gridLayout.addWidget(self.lineEditOutputLine, 10, 2, 1, 1)
        self.checkBoxOutputLegend = QtGui.QCheckBox(Cont2DXF)
        self.checkBoxOutputLegend.setObjectName(_fromUtf8("checkBoxOutputLegend"))
        self.gridLayout.addWidget(self.checkBoxOutputLegend, 11, 0, 1, 1)
        self.widgetLegend = QtGui.QWidget(Cont2DXF)
        self.widgetLegend.setEnabled(False)
        self.widgetLegend.setObjectName(_fromUtf8("widgetLegend"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widgetLegend)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_48 = QtGui.QLabel(self.widgetLegend)
        self.label_48.setIndent(18)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_13.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_62 = QtGui.QLabel(self.widgetLegend)
        self.label_62.setIndent(18)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_13.addWidget(self.label_62, 1, 0, 1, 1)
        self.lineEditOutputLegendTitle = QtGui.QLineEdit(self.widgetLegend)
        self.lineEditOutputLegendTitle.setObjectName(_fromUtf8("lineEditOutputLegendTitle"))
        self.gridLayout_13.addWidget(self.lineEditOutputLegendTitle, 0, 1, 1, 1)
        self.lineEditOutputLegendSubtitle = QtGui.QLineEdit(self.widgetLegend)
        self.lineEditOutputLegendSubtitle.setObjectName(_fromUtf8("lineEditOutputLegendSubtitle"))
        self.gridLayout_13.addWidget(self.lineEditOutputLegendSubtitle, 1, 1, 1, 1)
        self.label_63 = QtGui.QLabel(self.widgetLegend)
        self.label_63.setIndent(18)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_13.addWidget(self.label_63, 2, 0, 1, 1)
        self.lineEditOutputLegendSeparator = QtGui.QLineEdit(self.widgetLegend)
        self.lineEditOutputLegendSeparator.setObjectName(_fromUtf8("lineEditOutputLegendSeparator"))
        self.gridLayout_13.addWidget(self.lineEditOutputLegendSeparator, 2, 1, 1, 1)
        self.checkBoxOutputLegendReverse = QtGui.QCheckBox(self.widgetLegend)
        self.checkBoxOutputLegendReverse.setObjectName(_fromUtf8("checkBoxOutputLegendReverse"))
        self.gridLayout_13.addWidget(self.checkBoxOutputLegendReverse, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.widgetLegend, 12, 0, 1, 3)
        self.pushButtonCreate = QtGui.QPushButton(Cont2DXF)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 14, 0, 1, 3)
        spacerItem3 = QtGui.QSpacerItem(618, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 3)
        spacerItem4 = QtGui.QSpacerItem(618, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 13, 0, 1, 3)

        self.retranslateUi(Cont2DXF)
        QtCore.QMetaObject.connectSlotsByName(Cont2DXF)

    def retranslateUi(self, Cont2DXF):
        Cont2DXF.setWindowTitle(_translate("Cont2DXF", "Form", None))
        self.label_57.setText(_translate("Cont2DXF", "Inputs:", None))
        self.label_20.setText(_translate("Cont2DXF", "2D T3 Mesh:", None))
        self.pushButtonInput.setText(_translate("Cont2DXF", "...", None))
        self.pushButtonAdd.setToolTip(_translate("Cont2DXF", "add layer to table", None))
        self.pushButtonAdd.setText(_translate("Cont2DXF", "add", None))
        self.pushButtonDelete.setToolTip(_translate("Cont2DXF", "delete selected layer from table", None))
        self.pushButtonDelete.setText(_translate("Cont2DXF", "delete", None))
        self.pushButtonColour.setToolTip(_translate("Cont2DXF", "set colour for selected level", None))
        self.pushButtonColour.setText(_translate("Cont2DXF", "colour", None))
        self.label_60.setText(_translate("Cont2DXF", "Level:", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Cont2DXF", "From", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Cont2DXF", "To", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Cont2DXF", "Colour", None))
        self.label_59.setText(_translate("Cont2DXF", "Levels:", None))
        self.pushButtonLoad.setToolTip(_translate("Cont2DXF", "load legend from EnSim ColourScale definition file (*.cs1)", None))
        self.pushButtonLoad.setText(_translate("Cont2DXF", "load", None))
        self.pushButtonSave.setToolTip(_translate("Cont2DXF", "save legend as EnSim ColourScale definition file (*.cs1)", None))
        self.pushButtonSave.setText(_translate("Cont2DXF", "save", None))
        self.pushButtonDefault.setToolTip(_translate("Cont2DXF", "set default legend", None))
        self.pushButtonDefault.setText(_translate("Cont2DXF", "set default", None))
        self.label_58.setText(_translate("Cont2DXF", "Outputs:", None))
        self.label_61.setText(_translate("Cont2DXF", "DXF layer name:", None))
        self.checkBoxOutputSolid.setText(_translate("Cont2DXF", "DXF file filled contours:", None))
        self.pushButtonOutputSolid.setText(_translate("Cont2DXF", "...", None))
        self.checkBoxOutputLine.setText(_translate("Cont2DXF", "DXF file isolines:", None))
        self.pushButtonOutputLine.setText(_translate("Cont2DXF", "...", None))
        self.checkBoxOutputLegend.setText(_translate("Cont2DXF", "create legend", None))
        self.label_48.setText(_translate("Cont2DXF", "Legend title:", None))
        self.label_62.setText(_translate("Cont2DXF", "Legend subtitle:", None))
        self.label_63.setText(_translate("Cont2DXF", "Separator:", None))
        self.lineEditOutputLegendSeparator.setText(_translate("Cont2DXF", " - ", None))
        self.checkBoxOutputLegendReverse.setText(_translate("Cont2DXF", "create legend in reverse order", None))
        self.pushButtonCreate.setText(_translate("Cont2DXF", "Let\'s go!", None))

