# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiCS.ui'
#
# Created: Sat Nov 05 21:12:20 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CS(object):
    def setupUi(self, CS):
        CS.setObjectName(_fromUtf8("CS"))
        CS.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(CS)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_47 = QtGui.QLabel(CS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_47.setFont(font)
        self.label_47.setIndent(-4)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout.addWidget(self.label_47, 0, 0, 1, 1)
        self.label_45 = QtGui.QLabel(CS)
        self.label_45.setIndent(18)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 1, 0, 1, 1)
        self.pushButtonInputMesh = QtGui.QPushButton(CS)
        self.pushButtonInputMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputMesh.setObjectName(_fromUtf8("pushButtonInputMesh"))
        self.gridLayout.addWidget(self.pushButtonInputMesh, 1, 1, 1, 1)
        self.lineEditInputMesh = QtGui.QLineEdit(CS)
        self.lineEditInputMesh.setObjectName(_fromUtf8("lineEditInputMesh"))
        self.gridLayout.addWidget(self.lineEditInputMesh, 1, 2, 1, 1)
        self.label_44 = QtGui.QLabel(CS)
        self.label_44.setIndent(18)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 2, 0, 1, 1)
        self.pushButtonInputDefinition = QtGui.QPushButton(CS)
        self.pushButtonInputDefinition.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputDefinition.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputDefinition.setObjectName(_fromUtf8("pushButtonInputDefinition"))
        self.gridLayout.addWidget(self.pushButtonInputDefinition, 2, 1, 1, 1)
        self.lineEditInputDefinition = QtGui.QLineEdit(CS)
        self.lineEditInputDefinition.setObjectName(_fromUtf8("lineEditInputDefinition"))
        self.gridLayout.addWidget(self.lineEditInputDefinition, 2, 2, 1, 1)
        self.label_49 = QtGui.QLabel(CS)
        self.label_49.setIndent(18)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 3, 0, 1, 1)
        self.pushButtonInputResults = QtGui.QPushButton(CS)
        self.pushButtonInputResults.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputResults.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputResults.setObjectName(_fromUtf8("pushButtonInputResults"))
        self.gridLayout.addWidget(self.pushButtonInputResults, 3, 1, 1, 1)
        self.lineEditInputResults = QtGui.QLineEdit(CS)
        self.lineEditInputResults.setObjectName(_fromUtf8("lineEditInputResults"))
        self.gridLayout.addWidget(self.lineEditInputResults, 3, 2, 1, 1)
        self.label_50 = QtGui.QLabel(CS)
        self.label_50.setIndent(18)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout.addWidget(self.label_50, 4, 0, 1, 1)
        self.spinBoxTime = QtGui.QSpinBox(CS)
        self.spinBoxTime.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxTime.setMaximum(12)
        self.spinBoxTime.setProperty("value", 1)
        self.spinBoxTime.setObjectName(_fromUtf8("spinBoxTime"))
        self.gridLayout.addWidget(self.spinBoxTime, 4, 2, 1, 1)
        self.label_51 = QtGui.QLabel(CS)
        self.label_51.setIndent(18)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout.addWidget(self.label_51, 5, 0, 1, 1)
        self.spinBoxFlow = QtGui.QSpinBox(CS)
        self.spinBoxFlow.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxFlow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxFlow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxFlow.setMaximum(12)
        self.spinBoxFlow.setProperty("value", 2)
        self.spinBoxFlow.setObjectName(_fromUtf8("spinBoxFlow"))
        self.gridLayout.addWidget(self.spinBoxFlow, 5, 2, 1, 1)
        self.label_31 = QtGui.QLabel(CS)
        self.label_31.setIndent(18)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 6, 0, 1, 1)
        self.doubleSpinBoxSizeFactor = QtGui.QDoubleSpinBox(CS)
        self.doubleSpinBoxSizeFactor.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSizeFactor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSizeFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSizeFactor.setDecimals(3)
        self.doubleSpinBoxSizeFactor.setMaximum(99999999.0)
        self.doubleSpinBoxSizeFactor.setSingleStep(0.5)
        self.doubleSpinBoxSizeFactor.setProperty("value", 7.5)
        self.doubleSpinBoxSizeFactor.setObjectName(_fromUtf8("doubleSpinBoxSizeFactor"))
        self.gridLayout.addWidget(self.doubleSpinBoxSizeFactor, 6, 2, 1, 1)
        self.label_28 = QtGui.QLabel(CS)
        self.label_28.setIndent(18)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 7, 0, 1, 1)
        self.lineEditInputPrefix = QtGui.QLineEdit(CS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditInputPrefix.sizePolicy().hasHeightForWidth())
        self.lineEditInputPrefix.setSizePolicy(sizePolicy)
        self.lineEditInputPrefix.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditInputPrefix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditInputPrefix.setObjectName(_fromUtf8("lineEditInputPrefix"))
        self.gridLayout.addWidget(self.lineEditInputPrefix, 7, 2, 1, 1)
        self.label_40 = QtGui.QLabel(CS)
        self.label_40.setIndent(18)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 8, 0, 1, 1)
        self.lineEditInputSuffix = QtGui.QLineEdit(CS)
        self.lineEditInputSuffix.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEditInputSuffix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditInputSuffix.setObjectName(_fromUtf8("lineEditInputSuffix"))
        self.gridLayout.addWidget(self.lineEditInputSuffix, 8, 2, 1, 1)
        self.label_46 = QtGui.QLabel(CS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout.addWidget(self.label_46, 10, 0, 1, 1)
        self.checkBoxOutputFormatted = QtGui.QCheckBox(CS)
        self.checkBoxOutputFormatted.setObjectName(_fromUtf8("checkBoxOutputFormatted"))
        self.gridLayout.addWidget(self.checkBoxOutputFormatted, 11, 0, 1, 1)
        self.pushButtonOutputFormatted = QtGui.QPushButton(CS)
        self.pushButtonOutputFormatted.setEnabled(False)
        self.pushButtonOutputFormatted.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputFormatted.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputFormatted.setObjectName(_fromUtf8("pushButtonOutputFormatted"))
        self.gridLayout.addWidget(self.pushButtonOutputFormatted, 11, 1, 1, 1)
        self.lineEditOutputFormatted = QtGui.QLineEdit(CS)
        self.lineEditOutputFormatted.setEnabled(False)
        self.lineEditOutputFormatted.setObjectName(_fromUtf8("lineEditOutputFormatted"))
        self.gridLayout.addWidget(self.lineEditOutputFormatted, 11, 2, 1, 1)
        self.checkBoxOutputCS = QtGui.QCheckBox(CS)
        self.checkBoxOutputCS.setObjectName(_fromUtf8("checkBoxOutputCS"))
        self.gridLayout.addWidget(self.checkBoxOutputCS, 12, 0, 1, 1)
        self.pushButtonOutputCS = QtGui.QPushButton(CS)
        self.pushButtonOutputCS.setEnabled(False)
        self.pushButtonOutputCS.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputCS.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputCS.setObjectName(_fromUtf8("pushButtonOutputCS"))
        self.gridLayout.addWidget(self.pushButtonOutputCS, 12, 1, 1, 1)
        self.lineEditOutputCS = QtGui.QLineEdit(CS)
        self.lineEditOutputCS.setEnabled(False)
        self.lineEditOutputCS.setObjectName(_fromUtf8("lineEditOutputCS"))
        self.gridLayout.addWidget(self.lineEditOutputCS, 12, 2, 1, 1)
        self.pushButtonCreate = QtGui.QPushButton(CS)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 14, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(618, 111, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(618, 111, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 13, 0, 1, 3)

        self.retranslateUi(CS)
        QtCore.QMetaObject.connectSlotsByName(CS)

    def retranslateUi(self, CS):
        CS.setWindowTitle(_translate("CS", "Form", None))
        self.label_47.setText(_translate("CS", "Inputs:", None))
        self.label_45.setText(_translate("CS", "2D T3 Mesh:", None))
        self.pushButtonInputMesh.setText(_translate("CS", "...", None))
        self.label_44.setText(_translate("CS", "Control sections definition file:", None))
        self.pushButtonInputDefinition.setText(_translate("CS", "...", None))
        self.label_49.setText(_translate("CS", "Control sections results file:", None))
        self.pushButtonInputResults.setText(_translate("CS", "...", None))
        self.label_50.setText(_translate("CS", "Decimal points for time steps:", None))
        self.label_51.setText(_translate("CS", "Decimal points for flow:", None))
        self.label_31.setText(_translate("CS", "Size factor:", None))
        self.doubleSpinBoxSizeFactor.setToolTip(_translate("CS", "text size", None))
        self.label_28.setText(_translate("CS", "Flow prefix:", None))
        self.lineEditInputPrefix.setText(_translate("CS", "Q = ", None))
        self.label_40.setText(_translate("CS", "Flow suffix:", None))
        self.lineEditInputSuffix.setText(_translate("CS", " m3/s", None))
        self.label_46.setText(_translate("CS", "Outputs:", None))
        self.checkBoxOutputFormatted.setText(_translate("CS", "Formatted data file:", None))
        self.pushButtonOutputFormatted.setText(_translate("CS", "...", None))
        self.checkBoxOutputCS.setText(_translate("CS", "Control section file:", None))
        self.pushButtonOutputCS.setText(_translate("CS", "...", None))
        self.pushButtonCreate.setText(_translate("CS", "Let\'s go!", None))

