# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiHyDesign.ui'
#
# Created: Wed May 18 22:52:50 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HyDesign(object):
    def setupUi(self, HyDesign):
        HyDesign.setObjectName(_fromUtf8("HyDesign"))
        HyDesign.resize(585, 468)
        self.gridLayout_4 = QtGui.QGridLayout(HyDesign)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.widget_2 = QtGui.QWidget(HyDesign)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_85 = QtGui.QLabel(self.widget_2)
        self.label_85.setMinimumSize(QtCore.QSize(150, 0))
        self.label_85.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_85.setIndent(10)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_3.addWidget(self.label_85, 0, 0, 1, 1)
        self.labelDischarge_2 = QtGui.QLabel(self.widget_2)
        self.labelDischarge_2.setMinimumSize(QtCore.QSize(80, 0))
        self.labelDischarge_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelDischarge_2.setFont(font)
        self.labelDischarge_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDischarge_2.setObjectName(_fromUtf8("labelDischarge_2"))
        self.gridLayout_3.addWidget(self.labelDischarge_2, 0, 1, 1, 1)
        self.labelDischarge = QtGui.QLabel(self.widget_2)
        self.labelDischarge.setMinimumSize(QtCore.QSize(80, 0))
        self.labelDischarge.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelDischarge.setFont(font)
        self.labelDischarge.setText(_fromUtf8(""))
        self.labelDischarge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDischarge.setObjectName(_fromUtf8("labelDischarge"))
        self.gridLayout_3.addWidget(self.labelDischarge, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(218, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 7, 0, 1, 2)
        self.widget = QtGui.QWidget(HyDesign)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_83 = QtGui.QLabel(self.widget)
        self.label_83.setMinimumSize(QtCore.QSize(150, 0))
        self.label_83.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_83.setIndent(10)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout.addWidget(self.label_83, 0, 0, 1, 1)
        self.label_156 = QtGui.QLabel(self.widget)
        self.label_156.setMinimumSize(QtCore.QSize(50, 0))
        self.label_156.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_156.setObjectName(_fromUtf8("label_156"))
        self.gridLayout.addWidget(self.label_156, 0, 1, 1, 1)
        self.doubleSpinBoxStrickler = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxStrickler.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxStrickler.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxStrickler.setMaximum(99999999.0)
        self.doubleSpinBoxStrickler.setSingleStep(0.5)
        self.doubleSpinBoxStrickler.setProperty("value", 24.0)
        self.doubleSpinBoxStrickler.setObjectName(_fromUtf8("doubleSpinBoxStrickler"))
        self.gridLayout.addWidget(self.doubleSpinBoxStrickler, 0, 2, 1, 1)
        self.label_155 = QtGui.QLabel(self.widget)
        self.label_155.setMinimumSize(QtCore.QSize(60, 0))
        self.label_155.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.gridLayout.addWidget(self.label_155, 0, 3, 1, 1)
        self.label_84 = QtGui.QLabel(self.widget)
        self.label_84.setMinimumSize(QtCore.QSize(150, 0))
        self.label_84.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_84.setIndent(10)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout.addWidget(self.label_84, 1, 0, 1, 1)
        self.label_158 = QtGui.QLabel(self.widget)
        self.label_158.setMinimumSize(QtCore.QSize(50, 0))
        self.label_158.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_158.setObjectName(_fromUtf8("label_158"))
        self.gridLayout.addWidget(self.label_158, 1, 1, 1, 1)
        self.doubleSpinBoxSlope = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSlope.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSlope.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSlope.setMaximum(99999999.0)
        self.doubleSpinBoxSlope.setSingleStep(0.05)
        self.doubleSpinBoxSlope.setProperty("value", 1.0)
        self.doubleSpinBoxSlope.setObjectName(_fromUtf8("doubleSpinBoxSlope"))
        self.gridLayout.addWidget(self.doubleSpinBoxSlope, 1, 2, 1, 1)
        self.label_157 = QtGui.QLabel(self.widget)
        self.label_157.setMinimumSize(QtCore.QSize(60, 0))
        self.label_157.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_157.setObjectName(_fromUtf8("label_157"))
        self.gridLayout.addWidget(self.label_157, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(162, 43, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 2, 1)
        self.gridLayout_4.addWidget(self.widget, 4, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(564, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 8, 0, 1, 2)
        self.label_149 = QtGui.QLabel(HyDesign)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_149.setFont(font)
        self.label_149.setIndent(-4)
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self.gridLayout_4.addWidget(self.label_149, 0, 0, 2, 2)
        self.stackedWidgetType = QtGui.QStackedWidget(HyDesign)
        self.stackedWidgetType.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidgetType.setObjectName(_fromUtf8("stackedWidgetType"))
        self.pageRectangle = QtGui.QWidget()
        self.pageRectangle.setObjectName(_fromUtf8("pageRectangle"))
        self.gridLayout_21 = QtGui.QGridLayout(self.pageRectangle)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_80 = QtGui.QLabel(self.pageRectangle)
        self.label_80.setMinimumSize(QtCore.QSize(150, 0))
        self.label_80.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_80.setIndent(10)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_21.addWidget(self.label_80, 0, 0, 1, 1)
        self.label_143 = QtGui.QLabel(self.pageRectangle)
        self.label_143.setMinimumSize(QtCore.QSize(50, 0))
        self.label_143.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_143.setObjectName(_fromUtf8("label_143"))
        self.gridLayout_21.addWidget(self.label_143, 0, 1, 1, 1)
        self.doubleSpinBoxRectWidth = QtGui.QDoubleSpinBox(self.pageRectangle)
        self.doubleSpinBoxRectWidth.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxRectWidth.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxRectWidth.setDecimals(3)
        self.doubleSpinBoxRectWidth.setMaximum(99999999.0)
        self.doubleSpinBoxRectWidth.setSingleStep(0.5)
        self.doubleSpinBoxRectWidth.setProperty("value", 1.0)
        self.doubleSpinBoxRectWidth.setObjectName(_fromUtf8("doubleSpinBoxRectWidth"))
        self.gridLayout_21.addWidget(self.doubleSpinBoxRectWidth, 0, 2, 1, 1)
        self.label_147 = QtGui.QLabel(self.pageRectangle)
        self.label_147.setMinimumSize(QtCore.QSize(30, 0))
        self.label_147.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.gridLayout_21.addWidget(self.label_147, 0, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.pageRectangle)
        self.label_81.setMinimumSize(QtCore.QSize(150, 0))
        self.label_81.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_81.setIndent(10)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_21.addWidget(self.label_81, 1, 0, 1, 1)
        self.label_151 = QtGui.QLabel(self.pageRectangle)
        self.label_151.setMinimumSize(QtCore.QSize(50, 0))
        self.label_151.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.gridLayout_21.addWidget(self.label_151, 1, 1, 1, 1)
        self.doubleSpinBoxRectHeight = QtGui.QDoubleSpinBox(self.pageRectangle)
        self.doubleSpinBoxRectHeight.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxRectHeight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxRectHeight.setDecimals(3)
        self.doubleSpinBoxRectHeight.setMaximum(99999999.0)
        self.doubleSpinBoxRectHeight.setSingleStep(0.1)
        self.doubleSpinBoxRectHeight.setProperty("value", 1.0)
        self.doubleSpinBoxRectHeight.setObjectName(_fromUtf8("doubleSpinBoxRectHeight"))
        self.gridLayout_21.addWidget(self.doubleSpinBoxRectHeight, 1, 2, 1, 1)
        self.label_152 = QtGui.QLabel(self.pageRectangle)
        self.label_152.setMinimumSize(QtCore.QSize(30, 0))
        self.label_152.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.gridLayout_21.addWidget(self.label_152, 1, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem3, 3, 0, 1, 5)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem4, 0, 4, 3, 1)
        self.stackedWidgetType.addWidget(self.pageRectangle)
        self.pageTrapezoid = QtGui.QWidget()
        self.pageTrapezoid.setObjectName(_fromUtf8("pageTrapezoid"))
        self.gridLayout_16 = QtGui.QGridLayout(self.pageTrapezoid)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.doubleSpinBoxTrapRightSl = QtGui.QDoubleSpinBox(self.pageTrapezoid)
        self.doubleSpinBoxTrapRightSl.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTrapRightSl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTrapRightSl.setDecimals(3)
        self.doubleSpinBoxTrapRightSl.setMaximum(99999999.0)
        self.doubleSpinBoxTrapRightSl.setSingleStep(0.1)
        self.doubleSpinBoxTrapRightSl.setProperty("value", 1.0)
        self.doubleSpinBoxTrapRightSl.setObjectName(_fromUtf8("doubleSpinBoxTrapRightSl"))
        self.gridLayout_16.addWidget(self.doubleSpinBoxTrapRightSl, 3, 2, 1, 1)
        self.label_163 = QtGui.QLabel(self.pageTrapezoid)
        self.label_163.setMinimumSize(QtCore.QSize(30, 0))
        self.label_163.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_163.setObjectName(_fromUtf8("label_163"))
        self.gridLayout_16.addWidget(self.label_163, 3, 3, 1, 1)
        self.label_145 = QtGui.QLabel(self.pageTrapezoid)
        self.label_145.setMinimumSize(QtCore.QSize(50, 0))
        self.label_145.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_145.setObjectName(_fromUtf8("label_145"))
        self.gridLayout_16.addWidget(self.label_145, 1, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_16.addItem(spacerItem5, 0, 4, 4, 1)
        self.label_87 = QtGui.QLabel(self.pageTrapezoid)
        self.label_87.setMinimumSize(QtCore.QSize(150, 0))
        self.label_87.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_87.setIndent(10)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_16.addWidget(self.label_87, 1, 0, 1, 1)
        self.label_148 = QtGui.QLabel(self.pageTrapezoid)
        self.label_148.setMinimumSize(QtCore.QSize(30, 0))
        self.label_148.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_148.setObjectName(_fromUtf8("label_148"))
        self.gridLayout_16.addWidget(self.label_148, 0, 3, 1, 1)
        self.doubleSpinBoxTrapWidth = QtGui.QDoubleSpinBox(self.pageTrapezoid)
        self.doubleSpinBoxTrapWidth.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTrapWidth.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTrapWidth.setDecimals(3)
        self.doubleSpinBoxTrapWidth.setMaximum(99999999.0)
        self.doubleSpinBoxTrapWidth.setSingleStep(0.5)
        self.doubleSpinBoxTrapWidth.setProperty("value", 1.0)
        self.doubleSpinBoxTrapWidth.setObjectName(_fromUtf8("doubleSpinBoxTrapWidth"))
        self.gridLayout_16.addWidget(self.doubleSpinBoxTrapWidth, 0, 2, 1, 1)
        self.label_144 = QtGui.QLabel(self.pageTrapezoid)
        self.label_144.setMinimumSize(QtCore.QSize(50, 0))
        self.label_144.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_144.setObjectName(_fromUtf8("label_144"))
        self.gridLayout_16.addWidget(self.label_144, 0, 1, 1, 1)
        self.label_86 = QtGui.QLabel(self.pageTrapezoid)
        self.label_86.setMinimumSize(QtCore.QSize(150, 0))
        self.label_86.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_86.setIndent(10)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_16.addWidget(self.label_86, 0, 0, 1, 1)
        self.doubleSpinBoxTrapHeight = QtGui.QDoubleSpinBox(self.pageTrapezoid)
        self.doubleSpinBoxTrapHeight.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTrapHeight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTrapHeight.setDecimals(3)
        self.doubleSpinBoxTrapHeight.setMaximum(99999999.0)
        self.doubleSpinBoxTrapHeight.setSingleStep(0.1)
        self.doubleSpinBoxTrapHeight.setProperty("value", 1.0)
        self.doubleSpinBoxTrapHeight.setObjectName(_fromUtf8("doubleSpinBoxTrapHeight"))
        self.gridLayout_16.addWidget(self.doubleSpinBoxTrapHeight, 1, 2, 1, 1)
        self.label_159 = QtGui.QLabel(self.pageTrapezoid)
        self.label_159.setMinimumSize(QtCore.QSize(30, 0))
        self.label_159.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_159.setObjectName(_fromUtf8("label_159"))
        self.gridLayout_16.addWidget(self.label_159, 1, 3, 1, 1)
        self.label_89 = QtGui.QLabel(self.pageTrapezoid)
        self.label_89.setMinimumSize(QtCore.QSize(150, 0))
        self.label_89.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_89.setIndent(10)
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.gridLayout_16.addWidget(self.label_89, 2, 0, 1, 1)
        self.label_162 = QtGui.QLabel(self.pageTrapezoid)
        self.label_162.setMinimumSize(QtCore.QSize(50, 0))
        self.label_162.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_162.setObjectName(_fromUtf8("label_162"))
        self.gridLayout_16.addWidget(self.label_162, 2, 1, 1, 1)
        self.doubleSpinBoxTrapLeftSl = QtGui.QDoubleSpinBox(self.pageTrapezoid)
        self.doubleSpinBoxTrapLeftSl.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTrapLeftSl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTrapLeftSl.setDecimals(3)
        self.doubleSpinBoxTrapLeftSl.setMaximum(99999999.0)
        self.doubleSpinBoxTrapLeftSl.setSingleStep(0.1)
        self.doubleSpinBoxTrapLeftSl.setProperty("value", 1.0)
        self.doubleSpinBoxTrapLeftSl.setObjectName(_fromUtf8("doubleSpinBoxTrapLeftSl"))
        self.gridLayout_16.addWidget(self.doubleSpinBoxTrapLeftSl, 2, 2, 1, 1)
        self.label_161 = QtGui.QLabel(self.pageTrapezoid)
        self.label_161.setMinimumSize(QtCore.QSize(30, 0))
        self.label_161.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_161.setObjectName(_fromUtf8("label_161"))
        self.gridLayout_16.addWidget(self.label_161, 2, 3, 1, 1)
        self.label_91 = QtGui.QLabel(self.pageTrapezoid)
        self.label_91.setMinimumSize(QtCore.QSize(150, 0))
        self.label_91.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_91.setIndent(10)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.gridLayout_16.addWidget(self.label_91, 3, 0, 1, 1)
        self.label_164 = QtGui.QLabel(self.pageTrapezoid)
        self.label_164.setMinimumSize(QtCore.QSize(50, 0))
        self.label_164.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_164.setObjectName(_fromUtf8("label_164"))
        self.gridLayout_16.addWidget(self.label_164, 3, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem6, 4, 0, 1, 5)
        self.stackedWidgetType.addWidget(self.pageTrapezoid)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_17 = QtGui.QGridLayout(self.page)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.doubleSpinBoxTriaLeftSl = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBoxTriaLeftSl.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTriaLeftSl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTriaLeftSl.setDecimals(3)
        self.doubleSpinBoxTriaLeftSl.setMaximum(99999999.0)
        self.doubleSpinBoxTriaLeftSl.setSingleStep(0.1)
        self.doubleSpinBoxTriaLeftSl.setProperty("value", 1.0)
        self.doubleSpinBoxTriaLeftSl.setObjectName(_fromUtf8("doubleSpinBoxTriaLeftSl"))
        self.gridLayout_17.addWidget(self.doubleSpinBoxTriaLeftSl, 1, 2, 1, 1)
        self.label_165 = QtGui.QLabel(self.page)
        self.label_165.setMinimumSize(QtCore.QSize(30, 0))
        self.label_165.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_165.setObjectName(_fromUtf8("label_165"))
        self.gridLayout_17.addWidget(self.label_165, 1, 3, 1, 1)
        self.label_94 = QtGui.QLabel(self.page)
        self.label_94.setMinimumSize(QtCore.QSize(150, 0))
        self.label_94.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_94.setIndent(10)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.gridLayout_17.addWidget(self.label_94, 2, 0, 1, 1)
        self.label_167 = QtGui.QLabel(self.page)
        self.label_167.setMinimumSize(QtCore.QSize(50, 0))
        self.label_167.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_167.setObjectName(_fromUtf8("label_167"))
        self.gridLayout_17.addWidget(self.label_167, 2, 1, 1, 1)
        self.doubleSpinBoxTriaRightSl = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBoxTriaRightSl.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTriaRightSl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTriaRightSl.setDecimals(3)
        self.doubleSpinBoxTriaRightSl.setMaximum(99999999.0)
        self.doubleSpinBoxTriaRightSl.setSingleStep(0.1)
        self.doubleSpinBoxTriaRightSl.setProperty("value", 1.0)
        self.doubleSpinBoxTriaRightSl.setObjectName(_fromUtf8("doubleSpinBoxTriaRightSl"))
        self.gridLayout_17.addWidget(self.doubleSpinBoxTriaRightSl, 2, 2, 1, 1)
        self.label_166 = QtGui.QLabel(self.page)
        self.label_166.setMinimumSize(QtCore.QSize(30, 0))
        self.label_166.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_166.setObjectName(_fromUtf8("label_166"))
        self.gridLayout_17.addWidget(self.label_166, 2, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem7, 3, 0, 1, 5)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem8, 0, 4, 3, 1)
        self.label_93 = QtGui.QLabel(self.page)
        self.label_93.setMinimumSize(QtCore.QSize(150, 0))
        self.label_93.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_93.setIndent(10)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.gridLayout_17.addWidget(self.label_93, 0, 0, 1, 1)
        self.label_169 = QtGui.QLabel(self.page)
        self.label_169.setMinimumSize(QtCore.QSize(50, 0))
        self.label_169.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_169.setObjectName(_fromUtf8("label_169"))
        self.gridLayout_17.addWidget(self.label_169, 0, 1, 1, 1)
        self.doubleSpinBoxTriaHeight = QtGui.QDoubleSpinBox(self.page)
        self.doubleSpinBoxTriaHeight.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxTriaHeight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxTriaHeight.setDecimals(3)
        self.doubleSpinBoxTriaHeight.setMaximum(99999999.0)
        self.doubleSpinBoxTriaHeight.setSingleStep(0.1)
        self.doubleSpinBoxTriaHeight.setProperty("value", 1.0)
        self.doubleSpinBoxTriaHeight.setObjectName(_fromUtf8("doubleSpinBoxTriaHeight"))
        self.gridLayout_17.addWidget(self.doubleSpinBoxTriaHeight, 0, 2, 1, 1)
        self.label_168 = QtGui.QLabel(self.page)
        self.label_168.setMinimumSize(QtCore.QSize(30, 0))
        self.label_168.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_168.setObjectName(_fromUtf8("label_168"))
        self.gridLayout_17.addWidget(self.label_168, 0, 3, 1, 1)
        self.label_90 = QtGui.QLabel(self.page)
        self.label_90.setMinimumSize(QtCore.QSize(150, 0))
        self.label_90.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_90.setIndent(10)
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.gridLayout_17.addWidget(self.label_90, 1, 0, 1, 1)
        self.label_171 = QtGui.QLabel(self.page)
        self.label_171.setMinimumSize(QtCore.QSize(50, 0))
        self.label_171.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_171.setObjectName(_fromUtf8("label_171"))
        self.gridLayout_17.addWidget(self.label_171, 1, 1, 1, 1)
        self.stackedWidgetType.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_18 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_98 = QtGui.QLabel(self.page_2)
        self.label_98.setMinimumSize(QtCore.QSize(150, 0))
        self.label_98.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_98.setIndent(10)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.gridLayout_18.addWidget(self.label_98, 0, 0, 1, 1)
        self.label_179 = QtGui.QLabel(self.page_2)
        self.label_179.setMinimumSize(QtCore.QSize(50, 0))
        self.label_179.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_179.setObjectName(_fromUtf8("label_179"))
        self.gridLayout_18.addWidget(self.label_179, 0, 1, 1, 1)
        self.doubleSpinBoxCircWidth = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBoxCircWidth.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxCircWidth.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCircWidth.setDecimals(3)
        self.doubleSpinBoxCircWidth.setMaximum(99999999.0)
        self.doubleSpinBoxCircWidth.setSingleStep(0.5)
        self.doubleSpinBoxCircWidth.setProperty("value", 1.0)
        self.doubleSpinBoxCircWidth.setObjectName(_fromUtf8("doubleSpinBoxCircWidth"))
        self.gridLayout_18.addWidget(self.doubleSpinBoxCircWidth, 0, 2, 1, 1)
        self.label_178 = QtGui.QLabel(self.page_2)
        self.label_178.setMinimumSize(QtCore.QSize(30, 0))
        self.label_178.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_178.setObjectName(_fromUtf8("label_178"))
        self.gridLayout_18.addWidget(self.label_178, 0, 3, 1, 1)
        self.label_96 = QtGui.QLabel(self.page_2)
        self.label_96.setMinimumSize(QtCore.QSize(150, 0))
        self.label_96.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_96.setIndent(10)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.gridLayout_18.addWidget(self.label_96, 1, 0, 1, 1)
        self.label_173 = QtGui.QLabel(self.page_2)
        self.label_173.setMinimumSize(QtCore.QSize(50, 0))
        self.label_173.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_173.setObjectName(_fromUtf8("label_173"))
        self.gridLayout_18.addWidget(self.label_173, 1, 1, 1, 1)
        self.doubleSpinBoxCircRadius = QtGui.QDoubleSpinBox(self.page_2)
        self.doubleSpinBoxCircRadius.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxCircRadius.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCircRadius.setDecimals(3)
        self.doubleSpinBoxCircRadius.setMaximum(99999999.0)
        self.doubleSpinBoxCircRadius.setSingleStep(0.1)
        self.doubleSpinBoxCircRadius.setProperty("value", 1.0)
        self.doubleSpinBoxCircRadius.setObjectName(_fromUtf8("doubleSpinBoxCircRadius"))
        self.gridLayout_18.addWidget(self.doubleSpinBoxCircRadius, 1, 2, 1, 1)
        self.label_174 = QtGui.QLabel(self.page_2)
        self.label_174.setMinimumSize(QtCore.QSize(30, 0))
        self.label_174.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_174.setObjectName(_fromUtf8("label_174"))
        self.gridLayout_18.addWidget(self.label_174, 1, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem9, 3, 0, 1, 5)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 0, 4, 3, 1)
        self.stackedWidgetType.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_20 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem11, 1, 4, 3, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem12, 4, 0, 1, 5)
        self.label_99 = QtGui.QLabel(self.page_3)
        self.label_99.setMinimumSize(QtCore.QSize(150, 0))
        self.label_99.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_99.setIndent(10)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.gridLayout_20.addWidget(self.label_99, 1, 0, 1, 1)
        self.label_181 = QtGui.QLabel(self.page_3)
        self.label_181.setMinimumSize(QtCore.QSize(50, 0))
        self.label_181.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_181.setObjectName(_fromUtf8("label_181"))
        self.gridLayout_20.addWidget(self.label_181, 1, 1, 1, 1)
        self.doubleSpinBoxParaWidth = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinBoxParaWidth.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxParaWidth.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxParaWidth.setDecimals(3)
        self.doubleSpinBoxParaWidth.setMaximum(99999999.0)
        self.doubleSpinBoxParaWidth.setSingleStep(0.5)
        self.doubleSpinBoxParaWidth.setProperty("value", 1.0)
        self.doubleSpinBoxParaWidth.setObjectName(_fromUtf8("doubleSpinBoxParaWidth"))
        self.gridLayout_20.addWidget(self.doubleSpinBoxParaWidth, 1, 2, 1, 1)
        self.label_183 = QtGui.QLabel(self.page_3)
        self.label_183.setMinimumSize(QtCore.QSize(30, 0))
        self.label_183.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_183.setObjectName(_fromUtf8("label_183"))
        self.gridLayout_20.addWidget(self.label_183, 1, 3, 1, 1)
        self.label_101 = QtGui.QLabel(self.page_3)
        self.label_101.setMinimumSize(QtCore.QSize(150, 0))
        self.label_101.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_101.setIndent(10)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.gridLayout_20.addWidget(self.label_101, 2, 0, 1, 1)
        self.label_185 = QtGui.QLabel(self.page_3)
        self.label_185.setMinimumSize(QtCore.QSize(50, 0))
        self.label_185.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_185.setObjectName(_fromUtf8("label_185"))
        self.gridLayout_20.addWidget(self.label_185, 2, 1, 1, 1)
        self.doubleSpinBoxParaHeight = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinBoxParaHeight.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxParaHeight.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxParaHeight.setDecimals(3)
        self.doubleSpinBoxParaHeight.setMaximum(99999999.0)
        self.doubleSpinBoxParaHeight.setSingleStep(0.1)
        self.doubleSpinBoxParaHeight.setProperty("value", 1.0)
        self.doubleSpinBoxParaHeight.setObjectName(_fromUtf8("doubleSpinBoxParaHeight"))
        self.gridLayout_20.addWidget(self.doubleSpinBoxParaHeight, 2, 2, 1, 1)
        self.label_186 = QtGui.QLabel(self.page_3)
        self.label_186.setMinimumSize(QtCore.QSize(30, 0))
        self.label_186.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_186.setObjectName(_fromUtf8("label_186"))
        self.gridLayout_20.addWidget(self.label_186, 2, 3, 1, 1)
        self.stackedWidgetType.addWidget(self.page_3)
        self.gridLayout_4.addWidget(self.stackedWidgetType, 3, 0, 1, 2)
        spacerItem13 = QtGui.QSpacerItem(498, 27, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 5, 1, 1, 1)
        self.label_150 = QtGui.QLabel(HyDesign)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_150.setFont(font)
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.gridLayout_4.addWidget(self.label_150, 6, 0, 1, 2)
        self.widget_3 = QtGui.QWidget(HyDesign)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget_3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBoxTypeXSection = QtGui.QComboBox(self.widget_3)
        self.comboBoxTypeXSection.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBoxTypeXSection.setObjectName(_fromUtf8("comboBoxTypeXSection"))
        self.gridLayout_2.addWidget(self.comboBoxTypeXSection, 0, 1, 1, 1)
        self.label_79 = QtGui.QLabel(self.widget_3)
        self.label_79.setMinimumSize(QtCore.QSize(150, 0))
        self.label_79.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_79.setIndent(10)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_2.addWidget(self.label_79, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 2, 0, 1, 2)

        self.retranslateUi(HyDesign)
        self.stackedWidgetType.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(HyDesign)

    def retranslateUi(self, HyDesign):
        HyDesign.setWindowTitle(_translate("HyDesign", "Form", None))
        self.label_85.setText(_translate("HyDesign", "Discharge:", None))
        self.labelDischarge_2.setText(_translate("HyDesign", "Q =", None))
        self.label_83.setText(_translate("HyDesign", "Srickler-Roughness:", None))
        self.label_156.setText(_translate("HyDesign", "kst =", None))
        self.label_155.setText(_translate("HyDesign", "m^(1/3)/s", None))
        self.label_84.setText(_translate("HyDesign", "Bottom slope:", None))
        self.label_158.setText(_translate("HyDesign", "I =", None))
        self.label_157.setText(_translate("HyDesign", "%", None))
        self.label_149.setText(_translate("HyDesign", "Inputs:", None))
        self.label_80.setText(_translate("HyDesign", "Top width:", None))
        self.label_143.setText(_translate("HyDesign", "b =", None))
        self.label_147.setText(_translate("HyDesign", "m", None))
        self.label_81.setText(_translate("HyDesign", "Height:", None))
        self.label_151.setText(_translate("HyDesign", "h =", None))
        self.label_152.setText(_translate("HyDesign", "m", None))
        self.label_163.setText(_translate("HyDesign", "-", None))
        self.label_145.setText(_translate("HyDesign", "h =", None))
        self.label_87.setText(_translate("HyDesign", "Height:", None))
        self.label_148.setText(_translate("HyDesign", "m", None))
        self.label_144.setText(_translate("HyDesign", "b =", None))
        self.label_86.setText(_translate("HyDesign", "Top width:", None))
        self.label_159.setText(_translate("HyDesign", "m", None))
        self.label_89.setText(_translate("HyDesign", "Left slope:", None))
        self.label_162.setText(_translate("HyDesign", "sl = 1 :", None))
        self.label_161.setText(_translate("HyDesign", "-", None))
        self.label_91.setText(_translate("HyDesign", "Right slope:", None))
        self.label_164.setText(_translate("HyDesign", "sr = 1 :", None))
        self.label_165.setText(_translate("HyDesign", "-", None))
        self.label_94.setText(_translate("HyDesign", "Right slope:", None))
        self.label_167.setText(_translate("HyDesign", "sr = 1 :", None))
        self.label_166.setText(_translate("HyDesign", "-", None))
        self.label_93.setText(_translate("HyDesign", "Height:", None))
        self.label_169.setText(_translate("HyDesign", "h =", None))
        self.label_168.setText(_translate("HyDesign", "m", None))
        self.label_90.setText(_translate("HyDesign", "Left slope:", None))
        self.label_171.setText(_translate("HyDesign", "sl = 1 :", None))
        self.label_98.setText(_translate("HyDesign", "Top width:", None))
        self.label_179.setText(_translate("HyDesign", "b =", None))
        self.label_178.setText(_translate("HyDesign", "m", None))
        self.label_96.setText(_translate("HyDesign", "Radius:", None))
        self.label_173.setText(_translate("HyDesign", "r =", None))
        self.label_174.setText(_translate("HyDesign", "m", None))
        self.label_99.setText(_translate("HyDesign", "Top width:", None))
        self.label_181.setText(_translate("HyDesign", "b =", None))
        self.label_183.setText(_translate("HyDesign", "m", None))
        self.label_101.setText(_translate("HyDesign", "Height:", None))
        self.label_185.setText(_translate("HyDesign", "h =", None))
        self.label_186.setText(_translate("HyDesign", "m", None))
        self.label_150.setText(_translate("HyDesign", "Outputs:", None))
        self.label_79.setText(_translate("HyDesign", "Type of cross section:", None))

