# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMergeMesh.ui'
#
# Created: Sat May 06 14:50:47 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MergeMesh(object):
    def setupUi(self, MergeMesh):
        MergeMesh.setObjectName(_fromUtf8("MergeMesh"))
        MergeMesh.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(MergeMesh)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_106 = QtGui.QLabel(MergeMesh)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_106.setFont(font)
        self.label_106.setIndent(-4)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout.addWidget(self.label_106, 0, 0, 1, 1)
        self.label_105 = QtGui.QLabel(MergeMesh)
        self.label_105.setIndent(18)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout.addWidget(self.label_105, 1, 0, 1, 1)
        self.pushButtonInputMesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonInputMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputMesh.setObjectName(_fromUtf8("pushButtonInputMesh"))
        self.gridLayout.addWidget(self.pushButtonInputMesh, 1, 1, 1, 1)
        self.lineEditInputMesh = QtGui.QLineEdit(MergeMesh)
        self.lineEditInputMesh.setObjectName(_fromUtf8("lineEditInputMesh"))
        self.gridLayout.addWidget(self.lineEditInputMesh, 1, 2, 1, 2)
        self.label_117 = QtGui.QLabel(MergeMesh)
        self.label_117.setIndent(18)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout.addWidget(self.label_117, 2, 0, 1, 1)
        self.doubleSpinBoxOffset = QtGui.QDoubleSpinBox(MergeMesh)
        self.doubleSpinBoxOffset.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBoxOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxOffset.setMaximum(999999.0)
        self.doubleSpinBoxOffset.setProperty("value", 0.0)
        self.doubleSpinBoxOffset.setObjectName(_fromUtf8("doubleSpinBoxOffset"))
        self.gridLayout.addWidget(self.doubleSpinBoxOffset, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_60 = QtGui.QLabel(MergeMesh)
        self.label_60.setMinimumSize(QtCore.QSize(170, 0))
        self.label_60.setIndent(18)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout.addWidget(self.label_60)
        self.pushButtonAdd = QtGui.QPushButton(MergeMesh)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonAdd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonAdd.setObjectName(_fromUtf8("pushButtonAdd"))
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonDelete = QtGui.QPushButton(MergeMesh)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDelete.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDelete.setObjectName(_fromUtf8("pushButtonDelete"))
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonUp = QtGui.QPushButton(MergeMesh)
        self.pushButtonUp.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonUp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.horizontalLayout.addWidget(self.pushButtonUp)
        self.pushButtonDown = QtGui.QPushButton(MergeMesh)
        self.pushButtonDown.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDown.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDown.setObjectName(_fromUtf8("pushButtonDown"))
        self.horizontalLayout.addWidget(self.pushButtonDown)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonInputSubmesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonInputSubmesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputSubmesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputSubmesh.setObjectName(_fromUtf8("pushButtonInputSubmesh"))
        self.horizontalLayout.addWidget(self.pushButtonInputSubmesh)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 4)
        self.tableWidget = QtGui.QTableWidget(MergeMesh)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 5, 0, 1, 4)
        spacerItem2 = QtGui.QSpacerItem(500, 227, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 4)
        self.label_104 = QtGui.QLabel(MergeMesh)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_104.setFont(font)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout.addWidget(self.label_104, 7, 0, 1, 1)
        self.checkBoxOutputTotalMesh = QtGui.QCheckBox(MergeMesh)
        self.checkBoxOutputTotalMesh.setChecked(True)
        self.checkBoxOutputTotalMesh.setObjectName(_fromUtf8("checkBoxOutputTotalMesh"))
        self.gridLayout.addWidget(self.checkBoxOutputTotalMesh, 8, 0, 1, 1)
        self.pushButtonOutputTotalMesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonOutputTotalMesh.setEnabled(True)
        self.pushButtonOutputTotalMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputTotalMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputTotalMesh.setObjectName(_fromUtf8("pushButtonOutputTotalMesh"))
        self.gridLayout.addWidget(self.pushButtonOutputTotalMesh, 8, 1, 1, 1)
        self.lineEditOutputTotalMesh = QtGui.QLineEdit(MergeMesh)
        self.lineEditOutputTotalMesh.setEnabled(True)
        self.lineEditOutputTotalMesh.setObjectName(_fromUtf8("lineEditOutputTotalMesh"))
        self.gridLayout.addWidget(self.lineEditOutputTotalMesh, 8, 2, 1, 2)
        self.checkBoxOutputIntersectionMesh = QtGui.QCheckBox(MergeMesh)
        self.checkBoxOutputIntersectionMesh.setObjectName(_fromUtf8("checkBoxOutputIntersectionMesh"))
        self.gridLayout.addWidget(self.checkBoxOutputIntersectionMesh, 9, 0, 1, 1)
        self.pushButtonOutputIntersectionMesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonOutputIntersectionMesh.setEnabled(False)
        self.pushButtonOutputIntersectionMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputIntersectionMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputIntersectionMesh.setObjectName(_fromUtf8("pushButtonOutputIntersectionMesh"))
        self.gridLayout.addWidget(self.pushButtonOutputIntersectionMesh, 9, 1, 1, 1)
        self.lineEditOutputIntersectionMesh = QtGui.QLineEdit(MergeMesh)
        self.lineEditOutputIntersectionMesh.setEnabled(False)
        self.lineEditOutputIntersectionMesh.setObjectName(_fromUtf8("lineEditOutputIntersectionMesh"))
        self.gridLayout.addWidget(self.lineEditOutputIntersectionMesh, 9, 2, 1, 2)
        self.checkBoxOutputInnerMesh = QtGui.QCheckBox(MergeMesh)
        self.checkBoxOutputInnerMesh.setObjectName(_fromUtf8("checkBoxOutputInnerMesh"))
        self.gridLayout.addWidget(self.checkBoxOutputInnerMesh, 10, 0, 1, 1)
        self.pushButtonOutputInnerMesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonOutputInnerMesh.setEnabled(False)
        self.pushButtonOutputInnerMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputInnerMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputInnerMesh.setObjectName(_fromUtf8("pushButtonOutputInnerMesh"))
        self.gridLayout.addWidget(self.pushButtonOutputInnerMesh, 10, 1, 1, 1)
        self.lineEditOutputInnerMesh = QtGui.QLineEdit(MergeMesh)
        self.lineEditOutputInnerMesh.setEnabled(False)
        self.lineEditOutputInnerMesh.setObjectName(_fromUtf8("lineEditOutputInnerMesh"))
        self.gridLayout.addWidget(self.lineEditOutputInnerMesh, 10, 2, 1, 2)
        self.checkBoxOutputOuterMesh = QtGui.QCheckBox(MergeMesh)
        self.checkBoxOutputOuterMesh.setObjectName(_fromUtf8("checkBoxOutputOuterMesh"))
        self.gridLayout.addWidget(self.checkBoxOutputOuterMesh, 11, 0, 1, 1)
        self.pushButtonOutputOuterMesh = QtGui.QPushButton(MergeMesh)
        self.pushButtonOutputOuterMesh.setEnabled(False)
        self.pushButtonOutputOuterMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputOuterMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputOuterMesh.setObjectName(_fromUtf8("pushButtonOutputOuterMesh"))
        self.gridLayout.addWidget(self.pushButtonOutputOuterMesh, 11, 1, 1, 1)
        self.lineEditOutputOuterMesh = QtGui.QLineEdit(MergeMesh)
        self.lineEditOutputOuterMesh.setEnabled(False)
        self.lineEditOutputOuterMesh.setObjectName(_fromUtf8("lineEditOutputOuterMesh"))
        self.gridLayout.addWidget(self.lineEditOutputOuterMesh, 11, 2, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(609, 255, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 12, 0, 1, 4)
        self.pushButtonCreate = QtGui.QPushButton(MergeMesh)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 13, 0, 1, 4)
        spacerItem4 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 4)

        self.retranslateUi(MergeMesh)
        QtCore.QMetaObject.connectSlotsByName(MergeMesh)

    def retranslateUi(self, MergeMesh):
        MergeMesh.setWindowTitle(_translate("MergeMesh", "Form", None))
        self.label_106.setText(_translate("MergeMesh", "Inputs:", None))
        self.label_105.setText(_translate("MergeMesh", "Mesh:", None))
        self.pushButtonInputMesh.setText(_translate("MergeMesh", "...", None))
        self.label_117.setText(_translate("MergeMesh", "Intersection offset:", None))
        self.label_60.setText(_translate("MergeMesh", "Submeshes:", None))
        self.pushButtonAdd.setToolTip(_translate("MergeMesh", "add layer to table", None))
        self.pushButtonAdd.setText(_translate("MergeMesh", "add", None))
        self.pushButtonDelete.setToolTip(_translate("MergeMesh", "delete selected layer from table", None))
        self.pushButtonDelete.setText(_translate("MergeMesh", "delete", None))
        self.pushButtonUp.setToolTip(_translate("MergeMesh", "set colour for selected level", None))
        self.pushButtonUp.setText(_translate("MergeMesh", "up", None))
        self.pushButtonDown.setToolTip(_translate("MergeMesh", "set colour for selected level", None))
        self.pushButtonDown.setText(_translate("MergeMesh", "down", None))
        self.pushButtonInputSubmesh.setText(_translate("MergeMesh", "...", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MergeMesh", "Submesh", None))
        self.label_104.setText(_translate("MergeMesh", "Outputs:", None))
        self.checkBoxOutputTotalMesh.setText(_translate("MergeMesh", "Total mesh:", None))
        self.pushButtonOutputTotalMesh.setText(_translate("MergeMesh", "...", None))
        self.checkBoxOutputIntersectionMesh.setText(_translate("MergeMesh", "Intersection mesh:", None))
        self.pushButtonOutputIntersectionMesh.setText(_translate("MergeMesh", "...", None))
        self.checkBoxOutputInnerMesh.setText(_translate("MergeMesh", "Inner mesh:", None))
        self.pushButtonOutputInnerMesh.setText(_translate("MergeMesh", "...", None))
        self.checkBoxOutputOuterMesh.setText(_translate("MergeMesh", "Outer mesh:", None))
        self.pushButtonOutputOuterMesh.setText(_translate("MergeMesh", "...", None))
        self.pushButtonCreate.setText(_translate("MergeMesh", "Let\'s go!", None))

