# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiMesh.ui'
#
# Created: Wed Nov 02 20:57:58 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mesh(object):
    def setupUi(self, Mesh):
        Mesh.setObjectName(_fromUtf8("Mesh"))
        Mesh.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(Mesh)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonRBL = QtGui.QPushButton(Mesh)
        self.pushButtonRBL.setEnabled(False)
        self.pushButtonRBL.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonRBL.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonRBL.setObjectName(_fromUtf8("pushButtonRBL"))
        self.gridLayout.addWidget(self.pushButtonRBL, 4, 3, 1, 1)
        self.pushButtonWS = QtGui.QPushButton(Mesh)
        self.pushButtonWS.setEnabled(False)
        self.pushButtonWS.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonWS.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonWS.setObjectName(_fromUtf8("pushButtonWS"))
        self.gridLayout.addWidget(self.pushButtonWS, 21, 3, 1, 1)
        self.lineEditOL = QtGui.QLineEdit(Mesh)
        self.lineEditOL.setEnabled(False)
        self.lineEditOL.setObjectName(_fromUtf8("lineEditOL"))
        self.gridLayout.addWidget(self.lineEditOL, 20, 4, 1, 1)
        self.checkBoxLBO = QtGui.QCheckBox(Mesh)
        self.checkBoxLBO.setObjectName(_fromUtf8("checkBoxLBO"))
        self.gridLayout.addWidget(self.checkBoxLBO, 5, 0, 1, 3)
        self.lineEditWS = QtGui.QLineEdit(Mesh)
        self.lineEditWS.setEnabled(False)
        self.lineEditWS.setObjectName(_fromUtf8("lineEditWS"))
        self.gridLayout.addWidget(self.lineEditWS, 21, 4, 1, 1)
        self.label_4 = QtGui.QLabel(Mesh)
        self.label_4.setIndent(18)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 11, 0, 1, 4)
        self.checkBoxMesh = QtGui.QCheckBox(Mesh)
        self.checkBoxMesh.setChecked(True)
        self.checkBoxMesh.setObjectName(_fromUtf8("checkBoxMesh"))
        self.gridLayout.addWidget(self.checkBoxMesh, 16, 0, 1, 3)
        self.checkBoxLE = QtGui.QCheckBox(Mesh)
        self.checkBoxLE.setObjectName(_fromUtf8("checkBoxLE"))
        self.gridLayout.addWidget(self.checkBoxLE, 18, 0, 1, 3)
        self.checkBoxRBO = QtGui.QCheckBox(Mesh)
        self.checkBoxRBO.setObjectName(_fromUtf8("checkBoxRBO"))
        self.gridLayout.addWidget(self.checkBoxRBO, 6, 0, 1, 3)
        self.lineEditReach = QtGui.QLineEdit(Mesh)
        self.lineEditReach.setObjectName(_fromUtf8("lineEditReach"))
        self.gridLayout.addWidget(self.lineEditReach, 2, 4, 1, 1)
        self.checkBoxRE = QtGui.QCheckBox(Mesh)
        self.checkBoxRE.setObjectName(_fromUtf8("checkBoxRE"))
        self.gridLayout.addWidget(self.checkBoxRE, 19, 0, 1, 3)
        self.checkBoxOL = QtGui.QCheckBox(Mesh)
        self.checkBoxOL.setObjectName(_fromUtf8("checkBoxOL"))
        self.gridLayout.addWidget(self.checkBoxOL, 20, 0, 1, 3)
        self.pushButtonRBO = QtGui.QPushButton(Mesh)
        self.pushButtonRBO.setEnabled(False)
        self.pushButtonRBO.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonRBO.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonRBO.setObjectName(_fromUtf8("pushButtonRBO"))
        self.gridLayout.addWidget(self.pushButtonRBO, 6, 3, 1, 1)
        self.lineEditLE = QtGui.QLineEdit(Mesh)
        self.lineEditLE.setEnabled(False)
        self.lineEditLE.setObjectName(_fromUtf8("lineEditLE"))
        self.gridLayout.addWidget(self.lineEditLE, 18, 4, 1, 1)
        self.lineEditRBL = QtGui.QLineEdit(Mesh)
        self.lineEditRBL.setEnabled(False)
        self.lineEditRBL.setObjectName(_fromUtf8("lineEditRBL"))
        self.gridLayout.addWidget(self.lineEditRBL, 4, 4, 1, 1)
        self.lineEditLBL = QtGui.QLineEdit(Mesh)
        self.lineEditLBL.setEnabled(False)
        self.lineEditLBL.setObjectName(_fromUtf8("lineEditLBL"))
        self.gridLayout.addWidget(self.lineEditLBL, 3, 4, 1, 1)
        self.lineEditIP = QtGui.QLineEdit(Mesh)
        self.lineEditIP.setEnabled(False)
        self.lineEditIP.setObjectName(_fromUtf8("lineEditIP"))
        self.gridLayout.addWidget(self.lineEditIP, 17, 4, 1, 1)
        self.lineEditRBO = QtGui.QLineEdit(Mesh)
        self.lineEditRBO.setEnabled(False)
        self.lineEditRBO.setObjectName(_fromUtf8("lineEditRBO"))
        self.gridLayout.addWidget(self.lineEditRBO, 6, 4, 1, 1)
        self.pushButtonLE = QtGui.QPushButton(Mesh)
        self.pushButtonLE.setEnabled(False)
        self.pushButtonLE.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonLE.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonLE.setObjectName(_fromUtf8("pushButtonLE"))
        self.gridLayout.addWidget(self.pushButtonLE, 18, 3, 1, 1)
        self.label = QtGui.QLabel(Mesh)
        self.label.setIndent(18)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 3)
        self.lineEditMesh = QtGui.QLineEdit(Mesh)
        self.lineEditMesh.setObjectName(_fromUtf8("lineEditMesh"))
        self.gridLayout.addWidget(self.lineEditMesh, 16, 4, 1, 1)
        self.label_6 = QtGui.QLabel(Mesh)
        self.label_6.setIndent(18)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 4)
        self.pushButtonRE = QtGui.QPushButton(Mesh)
        self.pushButtonRE.setEnabled(False)
        self.pushButtonRE.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonRE.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonRE.setObjectName(_fromUtf8("pushButtonRE"))
        self.gridLayout.addWidget(self.pushButtonRE, 19, 3, 1, 1)
        self.lineEditLBO = QtGui.QLineEdit(Mesh)
        self.lineEditLBO.setEnabled(False)
        self.lineEditLBO.setObjectName(_fromUtf8("lineEditLBO"))
        self.gridLayout.addWidget(self.lineEditLBO, 5, 4, 1, 1)
        self.checkBoxEC = QtGui.QCheckBox(Mesh)
        self.checkBoxEC.setObjectName(_fromUtf8("checkBoxEC"))
        self.gridLayout.addWidget(self.checkBoxEC, 7, 0, 1, 3)
        self.pushButtonProfiles = QtGui.QPushButton(Mesh)
        self.pushButtonProfiles.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonProfiles.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonProfiles.setObjectName(_fromUtf8("pushButtonProfiles"))
        self.gridLayout.addWidget(self.pushButtonProfiles, 1, 3, 1, 1)
        self.checkBoxWS = QtGui.QCheckBox(Mesh)
        self.checkBoxWS.setObjectName(_fromUtf8("checkBoxWS"))
        self.gridLayout.addWidget(self.checkBoxWS, 21, 0, 1, 3)
        self.label_5 = QtGui.QLabel(Mesh)
        self.label_5.setIndent(18)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 3)
        self.checkBoxLBL = QtGui.QCheckBox(Mesh)
        self.checkBoxLBL.setObjectName(_fromUtf8("checkBoxLBL"))
        self.gridLayout.addWidget(self.checkBoxLBL, 3, 0, 1, 3)
        self.pushButtonIP = QtGui.QPushButton(Mesh)
        self.pushButtonIP.setEnabled(False)
        self.pushButtonIP.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonIP.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonIP.setObjectName(_fromUtf8("pushButtonIP"))
        self.gridLayout.addWidget(self.pushButtonIP, 17, 3, 1, 1)
        self.label_3 = QtGui.QLabel(Mesh)
        self.label_3.setIndent(18)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.checkBoxRBL = QtGui.QCheckBox(Mesh)
        self.checkBoxRBL.setObjectName(_fromUtf8("checkBoxRBL"))
        self.gridLayout.addWidget(self.checkBoxRBL, 4, 0, 1, 3)
        self.lineEditProfiles = QtGui.QLineEdit(Mesh)
        self.lineEditProfiles.setObjectName(_fromUtf8("lineEditProfiles"))
        self.gridLayout.addWidget(self.lineEditProfiles, 1, 4, 1, 1)
        self.spinBoxNNC = QtGui.QSpinBox(Mesh)
        self.spinBoxNNC.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxNNC.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxNNC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNNC.setMinimum(2)
        self.spinBoxNNC.setMaximum(500)
        self.spinBoxNNC.setObjectName(_fromUtf8("spinBoxNNC"))
        self.gridLayout.addWidget(self.spinBoxNNC, 10, 4, 1, 1)
        self.doubleSpinBoxEL = QtGui.QDoubleSpinBox(Mesh)
        self.doubleSpinBoxEL.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxEL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxEL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxEL.setDecimals(3)
        self.doubleSpinBoxEL.setMaximum(99999999.0)
        self.doubleSpinBoxEL.setSingleStep(0.5)
        self.doubleSpinBoxEL.setProperty("value", 5.0)
        self.doubleSpinBoxEL.setObjectName(_fromUtf8("doubleSpinBoxEL"))
        self.gridLayout.addWidget(self.doubleSpinBoxEL, 8, 4, 1, 1)
        self.label_8 = QtGui.QLabel(Mesh)
        self.label_8.setIndent(18)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 3)
        self.checkBoxIP = QtGui.QCheckBox(Mesh)
        self.checkBoxIP.setObjectName(_fromUtf8("checkBoxIP"))
        self.gridLayout.addWidget(self.checkBoxIP, 17, 0, 1, 3)
        self.pushButtonMesh = QtGui.QPushButton(Mesh)
        self.pushButtonMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonMesh.setObjectName(_fromUtf8("pushButtonMesh"))
        self.gridLayout.addWidget(self.pushButtonMesh, 16, 3, 1, 1)
        self.label_2 = QtGui.QLabel(Mesh)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setIndent(-4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.label_7 = QtGui.QLabel(Mesh)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 13, 0, 1, 1)
        self.spinBoxNNL = QtGui.QSpinBox(Mesh)
        self.spinBoxNNL.setEnabled(False)
        self.spinBoxNNL.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxNNL.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxNNL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNNL.setMinimum(2)
        self.spinBoxNNL.setMaximum(500)
        self.spinBoxNNL.setObjectName(_fromUtf8("spinBoxNNL"))
        self.gridLayout.addWidget(self.spinBoxNNL, 9, 4, 1, 1)
        self.lineEditRE = QtGui.QLineEdit(Mesh)
        self.lineEditRE.setEnabled(False)
        self.lineEditRE.setObjectName(_fromUtf8("lineEditRE"))
        self.gridLayout.addWidget(self.lineEditRE, 19, 4, 1, 1)
        self.pushButtonOL = QtGui.QPushButton(Mesh)
        self.pushButtonOL.setEnabled(False)
        self.pushButtonOL.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOL.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOL.setObjectName(_fromUtf8("pushButtonOL"))
        self.gridLayout.addWidget(self.pushButtonOL, 20, 3, 1, 1)
        self.pushButtonReach = QtGui.QPushButton(Mesh)
        self.pushButtonReach.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonReach.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonReach.setObjectName(_fromUtf8("pushButtonReach"))
        self.gridLayout.addWidget(self.pushButtonReach, 2, 3, 1, 1)
        self.pushButtonLBO = QtGui.QPushButton(Mesh)
        self.pushButtonLBO.setEnabled(False)
        self.pushButtonLBO.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonLBO.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonLBO.setObjectName(_fromUtf8("pushButtonLBO"))
        self.gridLayout.addWidget(self.pushButtonLBO, 5, 3, 1, 1)
        self.spinBoxNNR = QtGui.QSpinBox(Mesh)
        self.spinBoxNNR.setEnabled(False)
        self.spinBoxNNR.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxNNR.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxNNR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxNNR.setMinimum(2)
        self.spinBoxNNR.setMaximum(500)
        self.spinBoxNNR.setObjectName(_fromUtf8("spinBoxNNR"))
        self.gridLayout.addWidget(self.spinBoxNNR, 11, 4, 1, 1)
        self.pushButtonLBL = QtGui.QPushButton(Mesh)
        self.pushButtonLBL.setEnabled(False)
        self.pushButtonLBL.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonLBL.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonLBL.setObjectName(_fromUtf8("pushButtonLBL"))
        self.gridLayout.addWidget(self.pushButtonLBL, 3, 3, 1, 1)
        self.pushButtonCreate = QtGui.QPushButton(Mesh)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 23, 0, 1, 5)
        spacerItem = QtGui.QSpacerItem(618, 6, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 22, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(20, 14, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 14, 0, 1, 5)
        spacerItem2 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 0, 1, 5)

        self.retranslateUi(Mesh)
        QtCore.QMetaObject.connectSlotsByName(Mesh)

    def retranslateUi(self, Mesh):
        Mesh.setWindowTitle(_translate("Mesh", "Form", None))
        self.pushButtonRBL.setText(_translate("Mesh", "...", None))
        self.pushButtonWS.setText(_translate("Mesh", "...", None))
        self.checkBoxLBO.setText(_translate("Mesh", "Left boundary file:", None))
        self.label_4.setText(_translate("Mesh", "Number of right overbank nodes:", None))
        self.checkBoxMesh.setText(_translate("Mesh", "Mesh file:", None))
        self.checkBoxLE.setText(_translate("Mesh", "Left edge file:", None))
        self.checkBoxRBO.setText(_translate("Mesh", "Right boundary file:", None))
        self.checkBoxRE.setText(_translate("Mesh", "Right edge file:", None))
        self.checkBoxOL.setText(_translate("Mesh", "Outline file:", None))
        self.pushButtonRBO.setText(_translate("Mesh", "...", None))
        self.pushButtonLE.setText(_translate("Mesh", "...", None))
        self.label.setText(_translate("Mesh", "Channel profiles file:", None))
        self.label_6.setText(_translate("Mesh", "Number of left overbank nodes:", None))
        self.pushButtonRE.setText(_translate("Mesh", "...", None))
        self.checkBoxEC.setText(_translate("Mesh", "Elevation correction", None))
        self.pushButtonProfiles.setText(_translate("Mesh", "...", None))
        self.checkBoxWS.setText(_translate("Mesh", "Blue Kenue Workspace file:", None))
        self.label_5.setText(_translate("Mesh", "Number of channel nodes:", None))
        self.checkBoxLBL.setText(_translate("Mesh", "Left breakline file:", None))
        self.pushButtonIP.setText(_translate("Mesh", "...", None))
        self.label_3.setText(_translate("Mesh", "Channel reach file:", None))
        self.checkBoxRBL.setText(_translate("Mesh", "Right breakline file:", None))
        self.spinBoxNNC.setToolTip(_translate("Mesh", "cross channel node count", None))
        self.doubleSpinBoxEL.setToolTip(_translate("Mesh", "approximate along channel interval", None))
        self.label_8.setText(_translate("Mesh", "Element length:", None))
        self.checkBoxIP.setText(_translate("Mesh", "Interpolated profiles file:", None))
        self.pushButtonMesh.setText(_translate("Mesh", "...", None))
        self.label_2.setText(_translate("Mesh", "Inputs:", None))
        self.label_7.setText(_translate("Mesh", "Outputs:", None))
        self.spinBoxNNL.setToolTip(_translate("Mesh", "cross left overbank node count", None))
        self.pushButtonOL.setText(_translate("Mesh", "...", None))
        self.pushButtonReach.setText(_translate("Mesh", "...", None))
        self.pushButtonLBO.setText(_translate("Mesh", "...", None))
        self.spinBoxNNR.setToolTip(_translate("Mesh", "cross right overbank node count", None))
        self.pushButtonLBL.setText(_translate("Mesh", "...", None))
        self.pushButtonCreate.setText(_translate("Mesh", "Let\'s go!", None))

