# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\uiProfileSettings.ui'
#
# Created: Sat Nov 19 18:33:07 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProfileSettings(object):
    def setupUi(self, ProfileSettings):
        ProfileSettings.setObjectName(_fromUtf8("ProfileSettings"))
        ProfileSettings.resize(562, 267)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../resource/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProfileSettings.setWindowIcon(icon)
        self.gridLayout_2 = QtGui.QGridLayout(ProfileSettings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(ProfileSettings)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxFrame = QtGui.QCheckBox(self.widget)
        self.checkBoxFrame.setChecked(True)
        self.checkBoxFrame.setObjectName(_fromUtf8("checkBoxFrame"))
        self.gridLayout.addWidget(self.checkBoxFrame, 0, 0, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 2, 8, 1)
        self.label_110 = QtGui.QLabel(self.widget)
        self.label_110.setIndent(18)
        self.label_110.setObjectName(_fromUtf8("label_110"))
        self.gridLayout.addWidget(self.label_110, 0, 3, 1, 1)
        self.spinBoxDecimal = QtGui.QSpinBox(self.widget)
        self.spinBoxDecimal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxDecimal.setMaximum(6)
        self.spinBoxDecimal.setProperty("value", 0)
        self.spinBoxDecimal.setObjectName(_fromUtf8("spinBoxDecimal"))
        self.gridLayout.addWidget(self.spinBoxDecimal, 0, 4, 1, 1)
        self.checkBoxBand = QtGui.QCheckBox(self.widget)
        self.checkBoxBand.setChecked(True)
        self.checkBoxBand.setObjectName(_fromUtf8("checkBoxBand"))
        self.gridLayout.addWidget(self.checkBoxBand, 1, 0, 1, 1)
        self.label_115 = QtGui.QLabel(self.widget)
        self.label_115.setIndent(18)
        self.label_115.setObjectName(_fromUtf8("label_115"))
        self.gridLayout.addWidget(self.label_115, 1, 3, 1, 1)
        self.doubleSpinBoxOffsetX = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxOffsetX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxOffsetX.setMaximum(99999999.0)
        self.doubleSpinBoxOffsetX.setProperty("value", 0.0)
        self.doubleSpinBoxOffsetX.setObjectName(_fromUtf8("doubleSpinBoxOffsetX"))
        self.gridLayout.addWidget(self.doubleSpinBoxOffsetX, 1, 4, 1, 1)
        self.label_122 = QtGui.QLabel(self.widget)
        self.label_122.setIndent(18)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout.addWidget(self.label_122, 2, 0, 1, 1)
        self.lineEditInputProfileName = QtGui.QLineEdit(self.widget)
        self.lineEditInputProfileName.setText(_fromUtf8(""))
        self.lineEditInputProfileName.setObjectName(_fromUtf8("lineEditInputProfileName"))
        self.gridLayout.addWidget(self.lineEditInputProfileName, 2, 1, 1, 1)
        self.label_116 = QtGui.QLabel(self.widget)
        self.label_116.setIndent(18)
        self.label_116.setObjectName(_fromUtf8("label_116"))
        self.gridLayout.addWidget(self.label_116, 2, 3, 1, 1)
        self.doubleSpinBoxOffsetZ = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxOffsetZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxOffsetZ.setMaximum(99999999.0)
        self.doubleSpinBoxOffsetZ.setProperty("value", 0.0)
        self.doubleSpinBoxOffsetZ.setObjectName(_fromUtf8("doubleSpinBoxOffsetZ"))
        self.gridLayout.addWidget(self.doubleSpinBoxOffsetZ, 2, 4, 1, 1)
        self.label_123 = QtGui.QLabel(self.widget)
        self.label_123.setIndent(18)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout.addWidget(self.label_123, 3, 0, 1, 1)
        self.lineEditInputReachStation = QtGui.QLineEdit(self.widget)
        self.lineEditInputReachStation.setText(_fromUtf8(""))
        self.lineEditInputReachStation.setObjectName(_fromUtf8("lineEditInputReachStation"))
        self.gridLayout.addWidget(self.lineEditInputReachStation, 3, 1, 1, 1)
        self.label_117 = QtGui.QLabel(self.widget)
        self.label_117.setIndent(18)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout.addWidget(self.label_117, 3, 3, 1, 1)
        self.doubleSpinBoxBandHeight = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxBandHeight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxBandHeight.setMaximum(99999999.0)
        self.doubleSpinBoxBandHeight.setProperty("value", 0.0)
        self.doubleSpinBoxBandHeight.setObjectName(_fromUtf8("doubleSpinBoxBandHeight"))
        self.gridLayout.addWidget(self.doubleSpinBoxBandHeight, 3, 4, 1, 1)
        self.label_124 = QtGui.QLabel(self.widget)
        self.label_124.setIndent(18)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.gridLayout.addWidget(self.label_124, 4, 0, 1, 1)
        self.lineEditInputScaleFactor = QtGui.QLineEdit(self.widget)
        self.lineEditInputScaleFactor.setText(_fromUtf8(""))
        self.lineEditInputScaleFactor.setObjectName(_fromUtf8("lineEditInputScaleFactor"))
        self.gridLayout.addWidget(self.lineEditInputScaleFactor, 4, 1, 1, 1)
        self.label_118 = QtGui.QLabel(self.widget)
        self.label_118.setIndent(18)
        self.label_118.setObjectName(_fromUtf8("label_118"))
        self.gridLayout.addWidget(self.label_118, 4, 3, 1, 1)
        self.doubleSpinBoxTextSizeBandTitle = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxTextSizeBandTitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTextSizeBandTitle.setMaximum(99999999.0)
        self.doubleSpinBoxTextSizeBandTitle.setProperty("value", 0.0)
        self.doubleSpinBoxTextSizeBandTitle.setObjectName(_fromUtf8("doubleSpinBoxTextSizeBandTitle"))
        self.gridLayout.addWidget(self.doubleSpinBoxTextSizeBandTitle, 4, 4, 1, 1)
        self.label_125 = QtGui.QLabel(self.widget)
        self.label_125.setIndent(18)
        self.label_125.setObjectName(_fromUtf8("label_125"))
        self.gridLayout.addWidget(self.label_125, 5, 0, 1, 1)
        self.lineEditInputReferenceLevel = QtGui.QLineEdit(self.widget)
        self.lineEditInputReferenceLevel.setText(_fromUtf8(""))
        self.lineEditInputReferenceLevel.setObjectName(_fromUtf8("lineEditInputReferenceLevel"))
        self.gridLayout.addWidget(self.lineEditInputReferenceLevel, 5, 1, 1, 1)
        self.label_119 = QtGui.QLabel(self.widget)
        self.label_119.setIndent(18)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.gridLayout.addWidget(self.label_119, 5, 3, 1, 1)
        self.doubleSpinBoxTextSizeBand = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxTextSizeBand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxTextSizeBand.setMaximum(99999999.0)
        self.doubleSpinBoxTextSizeBand.setProperty("value", 0.0)
        self.doubleSpinBoxTextSizeBand.setObjectName(_fromUtf8("doubleSpinBoxTextSizeBand"))
        self.gridLayout.addWidget(self.doubleSpinBoxTextSizeBand, 5, 4, 1, 1)
        self.label_113 = QtGui.QLabel(self.widget)
        self.label_113.setIndent(18)
        self.label_113.setObjectName(_fromUtf8("label_113"))
        self.gridLayout.addWidget(self.label_113, 6, 0, 1, 1)
        self.lineEditInputBandTitleStationing = QtGui.QLineEdit(self.widget)
        self.lineEditInputBandTitleStationing.setText(_fromUtf8(""))
        self.lineEditInputBandTitleStationing.setObjectName(_fromUtf8("lineEditInputBandTitleStationing"))
        self.gridLayout.addWidget(self.lineEditInputBandTitleStationing, 6, 1, 1, 1)
        self.label_120 = QtGui.QLabel(self.widget)
        self.label_120.setIndent(18)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.gridLayout.addWidget(self.label_120, 6, 3, 1, 1)
        self.doubleSpinBoxMarkerSize = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxMarkerSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxMarkerSize.setMaximum(99999999.0)
        self.doubleSpinBoxMarkerSize.setProperty("value", 0.0)
        self.doubleSpinBoxMarkerSize.setObjectName(_fromUtf8("doubleSpinBoxMarkerSize"))
        self.gridLayout.addWidget(self.doubleSpinBoxMarkerSize, 6, 4, 1, 1)
        self.label_114 = QtGui.QLabel(self.widget)
        self.label_114.setIndent(18)
        self.label_114.setObjectName(_fromUtf8("label_114"))
        self.gridLayout.addWidget(self.label_114, 7, 0, 1, 1)
        self.lineEditInputBandTitleElevation = QtGui.QLineEdit(self.widget)
        self.lineEditInputBandTitleElevation.setText(_fromUtf8(""))
        self.lineEditInputBandTitleElevation.setObjectName(_fromUtf8("lineEditInputBandTitleElevation"))
        self.gridLayout.addWidget(self.lineEditInputBandTitleElevation, 7, 1, 1, 1)
        self.label_121 = QtGui.QLabel(self.widget)
        self.label_121.setIndent(18)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout.addWidget(self.label_121, 7, 3, 1, 1)
        self.doubleSpinBoxCleanValues = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxCleanValues.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxCleanValues.setMaximum(99999999.0)
        self.doubleSpinBoxCleanValues.setProperty("value", 0.0)
        self.doubleSpinBoxCleanValues.setObjectName(_fromUtf8("doubleSpinBoxCleanValues"))
        self.gridLayout.addWidget(self.doubleSpinBoxCleanValues, 7, 4, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ProfileSettings)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(ProfileSettings)
        QtCore.QMetaObject.connectSlotsByName(ProfileSettings)

    def retranslateUi(self, ProfileSettings):
        ProfileSettings.setWindowTitle(_translate("ProfileSettings", "Profile settings", None))
        self.checkBoxFrame.setText(_translate("ProfileSettings", "Draw frame", None))
        self.label_110.setText(_translate("ProfileSettings", "Decimal places:", None))
        self.checkBoxBand.setText(_translate("ProfileSettings", "Draw band", None))
        self.label_115.setText(_translate("ProfileSettings", "Horizontal band offset:", None))
        self.label_122.setText(_translate("ProfileSettings", "Profile name prefix:", None))
        self.label_116.setText(_translate("ProfileSettings", "Vertical band offset:", None))
        self.label_123.setText(_translate("ProfileSettings", "Reach station prefix:", None))
        self.label_117.setText(_translate("ProfileSettings", "Band height:", None))
        self.label_124.setText(_translate("ProfileSettings", "Scale factor prefix:", None))
        self.label_118.setText(_translate("ProfileSettings", "Text size band title:", None))
        self.label_125.setText(_translate("ProfileSettings", "Reference level prefix:", None))
        self.label_119.setText(_translate("ProfileSettings", "Text size band:", None))
        self.label_113.setText(_translate("ProfileSettings", "Band title stationing:", None))
        self.label_120.setText(_translate("ProfileSettings", "Makrer size:", None))
        self.label_114.setText(_translate("ProfileSettings", "Band title elevation:", None))
        self.label_121.setText(_translate("ProfileSettings", "Clean values:", None))

