# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiScalarDXF.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScalarDXF(object):
    def setupUi(self, ScalarDXF):
        ScalarDXF.setObjectName(_fromUtf8("ScalarDXF"))
        ScalarDXF.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(ScalarDXF)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radioButtonCross = QtGui.QRadioButton(ScalarDXF)
        self.radioButtonCross.setObjectName(_fromUtf8("radioButtonCross"))
        self.gridLayout.addWidget(self.radioButtonCross, 12, 2, 1, 1)
        self.label_26 = QtGui.QLabel(ScalarDXF)
        self.label_26.setIndent(18)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.doubleSpinBoxSMax = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxSMax.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSMax.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSMax.setDecimals(3)
        self.doubleSpinBoxSMax.setMinimum(-99999999.0)
        self.doubleSpinBoxSMax.setMaximum(99999999.0)
        self.doubleSpinBoxSMax.setSingleStep(1.0)
        self.doubleSpinBoxSMax.setProperty("value", 100.0)
        self.doubleSpinBoxSMax.setObjectName(_fromUtf8("doubleSpinBoxSMax"))
        self.gridLayout.addWidget(self.doubleSpinBoxSMax, 3, 3, 1, 1)
        self.doubleSpinBoxLessThan = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxLessThan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxLessThan.setDecimals(3)
        self.doubleSpinBoxLessThan.setMaximum(99999999.0)
        self.doubleSpinBoxLessThan.setSingleStep(0.005)
        self.doubleSpinBoxLessThan.setProperty("value", 0.01)
        self.doubleSpinBoxLessThan.setObjectName(_fromUtf8("doubleSpinBoxLessThan"))
        self.gridLayout.addWidget(self.doubleSpinBoxLessThan, 4, 2, 1, 1)
        self.doubleSpinBoxDY = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxDY.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxDY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxDY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxDY.setDecimals(3)
        self.doubleSpinBoxDY.setMaximum(99999999.0)
        self.doubleSpinBoxDY.setSingleStep(1.0)
        self.doubleSpinBoxDY.setProperty("value", 10.0)
        self.doubleSpinBoxDY.setObjectName(_fromUtf8("doubleSpinBoxDY"))
        self.gridLayout.addWidget(self.doubleSpinBoxDY, 8, 2, 1, 1)
        self.doubleSpinBoxSizeFactor = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxSizeFactor.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSizeFactor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSizeFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSizeFactor.setDecimals(3)
        self.doubleSpinBoxSizeFactor.setMinimum(0.0)
        self.doubleSpinBoxSizeFactor.setMaximum(99999999.0)
        self.doubleSpinBoxSizeFactor.setSingleStep(0.5)
        self.doubleSpinBoxSizeFactor.setProperty("value", 1.5)
        self.doubleSpinBoxSizeFactor.setObjectName(_fromUtf8("doubleSpinBoxSizeFactor"))
        self.gridLayout.addWidget(self.doubleSpinBoxSizeFactor, 6, 2, 1, 1)
        self.pushButtonInputT3SMinor = QtGui.QPushButton(ScalarDXF)
        self.pushButtonInputT3SMinor.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputT3SMinor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputT3SMinor.setObjectName(_fromUtf8("pushButtonInputT3SMinor"))
        self.gridLayout.addWidget(self.pushButtonInputT3SMinor, 2, 1, 1, 1)
        self.spinBoxScale = QtGui.QSpinBox(ScalarDXF)
        self.spinBoxScale.setMinimumSize(QtCore.QSize(100, 0))
        self.spinBoxScale.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxScale.setMaximum(100000)
        self.spinBoxScale.setProperty("value", 1000)
        self.spinBoxScale.setObjectName(_fromUtf8("spinBoxScale"))
        self.gridLayout.addWidget(self.spinBoxScale, 5, 2, 1, 1)
        self.radioButtonCircle = QtGui.QRadioButton(ScalarDXF)
        self.radioButtonCircle.setChecked(True)
        self.radioButtonCircle.setObjectName(_fromUtf8("radioButtonCircle"))
        self.gridLayout.addWidget(self.radioButtonCircle, 10, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(618, 82, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 5)
        self.label_22 = QtGui.QLabel(ScalarDXF)
        self.label_22.setIndent(18)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.pushButtonInputT3SMajor = QtGui.QPushButton(ScalarDXF)
        self.pushButtonInputT3SMajor.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputT3SMajor.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputT3SMajor.setObjectName(_fromUtf8("pushButtonInputT3SMajor"))
        self.gridLayout.addWidget(self.pushButtonInputT3SMajor, 1, 1, 1, 1)
        self.doubleSpinBoxDX = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxDX.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxDX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxDX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxDX.setDecimals(3)
        self.doubleSpinBoxDX.setMaximum(99999999.0)
        self.doubleSpinBoxDX.setSingleStep(1.0)
        self.doubleSpinBoxDX.setProperty("value", 10.0)
        self.doubleSpinBoxDX.setObjectName(_fromUtf8("doubleSpinBoxDX"))
        self.gridLayout.addWidget(self.doubleSpinBoxDX, 7, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(618, 83, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 5)
        self.label_24 = QtGui.QLabel(ScalarDXF)
        self.label_24.setIndent(18)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 7, 0, 1, 1)
        self.label_30 = QtGui.QLabel(ScalarDXF)
        self.label_30.setIndent(18)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 17, 0, 1, 1)
        self.doubleSpinBoxSMin = QtGui.QDoubleSpinBox(ScalarDXF)
        self.doubleSpinBoxSMin.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBoxSMin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxSMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSMin.setDecimals(3)
        self.doubleSpinBoxSMin.setMinimum(-99999999.0)
        self.doubleSpinBoxSMin.setMaximum(99999999.0)
        self.doubleSpinBoxSMin.setSingleStep(1.0)
        self.doubleSpinBoxSMin.setProperty("value", -100.0)
        self.doubleSpinBoxSMin.setObjectName(_fromUtf8("doubleSpinBoxSMin"))
        self.gridLayout.addWidget(self.doubleSpinBoxSMin, 3, 2, 1, 1)
        self.pushButtonCreate = QtGui.QPushButton(ScalarDXF)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 19, 0, 1, 5)
        self.label_34 = QtGui.QLabel(ScalarDXF)
        self.label_34.setIndent(18)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 2, 0, 1, 1)
        self.label_32 = QtGui.QLabel(ScalarDXF)
        self.label_32.setIndent(18)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 6, 0, 1, 1)
        self.label_21 = QtGui.QLabel(ScalarDXF)
        self.label_21.setIndent(18)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(ScalarDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 16, 0, 1, 1)
        self.label_25 = QtGui.QLabel(ScalarDXF)
        self.label_25.setIndent(18)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 8, 0, 1, 1)
        self.label_35 = QtGui.QLabel(ScalarDXF)
        self.label_35.setIndent(18)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 5, 0, 1, 1)
        self.checkBoxMonochrome = QtGui.QCheckBox(ScalarDXF)
        self.checkBoxMonochrome.setChecked(True)
        self.checkBoxMonochrome.setObjectName(_fromUtf8("checkBoxMonochrome"))
        self.gridLayout.addWidget(self.checkBoxMonochrome, 9, 0, 1, 1)
        self.label_23 = QtGui.QLabel(ScalarDXF)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_23.setFont(font)
        self.label_23.setIndent(-4)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(ScalarDXF)
        self.label_33.setIndent(18)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 10, 0, 1, 1)
        self.radioButtonCrosshairs = QtGui.QRadioButton(ScalarDXF)
        self.radioButtonCrosshairs.setObjectName(_fromUtf8("radioButtonCrosshairs"))
        self.gridLayout.addWidget(self.radioButtonCrosshairs, 13, 2, 1, 1)
        self.radioButtonNone = QtGui.QRadioButton(ScalarDXF)
        self.radioButtonNone.setObjectName(_fromUtf8("radioButtonNone"))
        self.gridLayout.addWidget(self.radioButtonNone, 14, 2, 1, 1)
        self.pushButtonOutput = QtGui.QPushButton(ScalarDXF)
        self.pushButtonOutput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.gridLayout.addWidget(self.pushButtonOutput, 17, 1, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(ScalarDXF)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayout.addWidget(self.lineEditOutput, 17, 2, 1, 3)
        self.lineEditInputT3SMinor = QtGui.QLineEdit(ScalarDXF)
        self.lineEditInputT3SMinor.setObjectName(_fromUtf8("lineEditInputT3SMinor"))
        self.gridLayout.addWidget(self.lineEditInputT3SMinor, 2, 2, 1, 3)
        self.lineEditInputT3SMajor = QtGui.QLineEdit(ScalarDXF)
        self.lineEditInputT3SMajor.setObjectName(_fromUtf8("lineEditInputT3SMajor"))
        self.gridLayout.addWidget(self.lineEditInputT3SMajor, 1, 2, 1, 3)

        self.retranslateUi(ScalarDXF)
        QtCore.QMetaObject.connectSlotsByName(ScalarDXF)

    def retranslateUi(self, ScalarDXF):
        ScalarDXF.setWindowTitle(_translate("ScalarDXF", "Form", None))
        self.radioButtonCross.setText(_translate("ScalarDXF", "Cross", None))
        self.label_26.setText(_translate("ScalarDXF", "Minimum and maximum value of scalar:", None))
        self.doubleSpinBoxSMax.setToolTip(_translate("ScalarDXF", "higher values are ignored", None))
        self.doubleSpinBoxLessThan.setToolTip(_translate("ScalarDXF", "ignore values less than given difference from zero", None))
        self.doubleSpinBoxDY.setToolTip(_translate("ScalarDXF", "grid interval in y-direction", None))
        self.doubleSpinBoxSizeFactor.setToolTip(_translate("ScalarDXF", "text size", None))
        self.pushButtonInputT3SMinor.setText(_translate("ScalarDXF", "...", None))
        self.spinBoxScale.setToolTip(_translate("ScalarDXF", "text size", None))
        self.radioButtonCircle.setText(_translate("ScalarDXF", "Circle", None))
        self.label_22.setText(_translate("ScalarDXF", "Ignore values less than (±):", None))
        self.pushButtonInputT3SMajor.setText(_translate("ScalarDXF", "...", None))
        self.doubleSpinBoxDX.setToolTip(_translate("ScalarDXF", "grid interval in x-direction", None))
        self.label_24.setText(_translate("ScalarDXF", "X-Spacing:", None))
        self.label_30.setText(_translate("ScalarDXF", "DXF grid file:", None))
        self.doubleSpinBoxSMin.setToolTip(_translate("ScalarDXF", "lower values are ignored", None))
        self.pushButtonCreate.setText(_translate("ScalarDXF", "Let\'s go!", None))
        self.label_34.setText(_translate("ScalarDXF", "Minor 2D T3 Scalar Mesh:", None))
        self.label_32.setText(_translate("ScalarDXF", "Size factor:", None))
        self.label_21.setText(_translate("ScalarDXF", "Major 2D T3 Scalar Mesh:", None))
        self.label_29.setText(_translate("ScalarDXF", "Outputs:", None))
        self.label_25.setText(_translate("ScalarDXF", "Y-Spacing:", None))
        self.label_35.setText(_translate("ScalarDXF", "Scale:", None))
        self.checkBoxMonochrome.setToolTip(_translate("ScalarDXF", "monochrome symbols and values, otherwise red for positive values and green for negative values", None))
        self.checkBoxMonochrome.setText(_translate("ScalarDXF", "Use monochrome colors", None))
        self.label_23.setText(_translate("ScalarDXF", "Inputs:", None))
        self.label_33.setText(_translate("ScalarDXF", "Symbol for grid points:", None))
        self.radioButtonCrosshairs.setText(_translate("ScalarDXF", "Crosshairs", None))
        self.radioButtonNone.setText(_translate("ScalarDXF", "None", None))
        self.pushButtonOutput.setText(_translate("ScalarDXF", "...", None))

