# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiTube.ui'
#
# Created: Sat Nov 05 23:03:01 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Tube(object):
    def setupUi(self, Tube):
        Tube.setObjectName(_fromUtf8("Tube"))
        Tube.resize(639, 600)
        self.gridLayout = QtGui.QGridLayout(Tube)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_67 = QtGui.QLabel(Tube)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_67.setFont(font)
        self.label_67.setIndent(-4)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout.addWidget(self.label_67, 0, 0, 1, 1)
        self.label_64 = QtGui.QLabel(Tube)
        self.label_64.setIndent(18)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout.addWidget(self.label_64, 1, 0, 1, 2)
        self.pushButtonInputMesh = QtGui.QPushButton(Tube)
        self.pushButtonInputMesh.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputMesh.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputMesh.setObjectName(_fromUtf8("pushButtonInputMesh"))
        self.gridLayout.addWidget(self.pushButtonInputMesh, 1, 2, 1, 1)
        self.lineEditInputMesh = QtGui.QLineEdit(Tube)
        self.lineEditInputMesh.setObjectName(_fromUtf8("lineEditInputMesh"))
        self.gridLayout.addWidget(self.lineEditInputMesh, 1, 3, 1, 1)
        self.label_68 = QtGui.QLabel(Tube)
        self.label_68.setIndent(18)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout.addWidget(self.label_68, 2, 0, 1, 2)
        self.pushButtonInputLineSet = QtGui.QPushButton(Tube)
        self.pushButtonInputLineSet.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputLineSet.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputLineSet.setObjectName(_fromUtf8("pushButtonInputLineSet"))
        self.gridLayout.addWidget(self.pushButtonInputLineSet, 2, 2, 1, 1)
        self.lineEditInputLineSet = QtGui.QLineEdit(Tube)
        self.lineEditInputLineSet.setObjectName(_fromUtf8("lineEditInputLineSet"))
        self.gridLayout.addWidget(self.lineEditInputLineSet, 2, 3, 1, 1)
        self.label_69 = QtGui.QLabel(Tube)
        self.label_69.setIndent(18)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout.addWidget(self.label_69, 3, 0, 1, 2)
        self.label_78 = QtGui.QLabel(Tube)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout.addWidget(self.label_78, 3, 2, 1, 1)
        self.doubleSpinBoxRel = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxRel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxRel.setMaximum(1.0)
        self.doubleSpinBoxRel.setSingleStep(0.01)
        self.doubleSpinBoxRel.setProperty("value", 0.05)
        self.doubleSpinBoxRel.setObjectName(_fromUtf8("doubleSpinBoxRel"))
        self.gridLayout.addWidget(self.doubleSpinBoxRel, 3, 3, 1, 1)
        self.label_70 = QtGui.QLabel(Tube)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout.addWidget(self.label_70, 4, 2, 1, 1)
        self.doubleSpinBoxCe1 = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxCe1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCe1.setMaximum(999999.0)
        self.doubleSpinBoxCe1.setSingleStep(0.01)
        self.doubleSpinBoxCe1.setProperty("value", 0.5)
        self.doubleSpinBoxCe1.setObjectName(_fromUtf8("doubleSpinBoxCe1"))
        self.gridLayout.addWidget(self.doubleSpinBoxCe1, 4, 3, 1, 1)
        self.label_71 = QtGui.QLabel(Tube)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout.addWidget(self.label_71, 5, 2, 1, 1)
        self.doubleSpinBoxCe2 = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxCe2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCe2.setMaximum(999999.0)
        self.doubleSpinBoxCe2.setSingleStep(0.01)
        self.doubleSpinBoxCe2.setProperty("value", 0.5)
        self.doubleSpinBoxCe2.setObjectName(_fromUtf8("doubleSpinBoxCe2"))
        self.gridLayout.addWidget(self.doubleSpinBoxCe2, 5, 3, 1, 1)
        self.label_72 = QtGui.QLabel(Tube)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout.addWidget(self.label_72, 6, 2, 1, 1)
        self.doubleSpinBoxCs1 = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxCs1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCs1.setMaximum(999999.0)
        self.doubleSpinBoxCs1.setSingleStep(0.01)
        self.doubleSpinBoxCs1.setProperty("value", 1.0)
        self.doubleSpinBoxCs1.setObjectName(_fromUtf8("doubleSpinBoxCs1"))
        self.gridLayout.addWidget(self.doubleSpinBoxCs1, 6, 3, 1, 1)
        self.label_73 = QtGui.QLabel(Tube)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout.addWidget(self.label_73, 7, 2, 1, 1)
        self.doubleSpinBoxCs2 = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxCs2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxCs2.setMaximum(999999.0)
        self.doubleSpinBoxCs2.setSingleStep(0.01)
        self.doubleSpinBoxCs2.setProperty("value", 1.0)
        self.doubleSpinBoxCs2.setObjectName(_fromUtf8("doubleSpinBoxCs2"))
        self.gridLayout.addWidget(self.doubleSpinBoxCs2, 7, 3, 1, 1)
        self.label_74 = QtGui.QLabel(Tube)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout.addWidget(self.label_74, 8, 2, 1, 1)
        self.doubleSpinBoxLrg = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxLrg.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxLrg.setMaximum(999999.0)
        self.doubleSpinBoxLrg.setSingleStep(0.01)
        self.doubleSpinBoxLrg.setProperty("value", 2.0)
        self.doubleSpinBoxLrg.setObjectName(_fromUtf8("doubleSpinBoxLrg"))
        self.gridLayout.addWidget(self.doubleSpinBoxLrg, 8, 3, 1, 1)
        self.label_75 = QtGui.QLabel(Tube)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout.addWidget(self.label_75, 9, 2, 1, 1)
        self.doubleSpinBoxHau = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxHau.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxHau.setMaximum(999999.0)
        self.doubleSpinBoxHau.setSingleStep(0.01)
        self.doubleSpinBoxHau.setProperty("value", 1.5)
        self.doubleSpinBoxHau.setObjectName(_fromUtf8("doubleSpinBoxHau"))
        self.gridLayout.addWidget(self.doubleSpinBoxHau, 9, 3, 1, 1)
        self.label_76 = QtGui.QLabel(Tube)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout.addWidget(self.label_76, 10, 2, 1, 1)
        self.spinBoxClp = QtGui.QSpinBox(Tube)
        self.spinBoxClp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxClp.setMaximum(3)
        self.spinBoxClp.setObjectName(_fromUtf8("spinBoxClp"))
        self.gridLayout.addWidget(self.spinBoxClp, 10, 3, 1, 1)
        self.label_77 = QtGui.QLabel(Tube)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout.addWidget(self.label_77, 11, 2, 1, 1)
        self.doubleSpinBoxL12 = QtGui.QDoubleSpinBox(Tube)
        self.doubleSpinBoxL12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.doubleSpinBoxL12.setMaximum(999999.0)
        self.doubleSpinBoxL12.setSingleStep(0.01)
        self.doubleSpinBoxL12.setProperty("value", 0.2)
        self.doubleSpinBoxL12.setObjectName(_fromUtf8("doubleSpinBoxL12"))
        self.gridLayout.addWidget(self.doubleSpinBoxL12, 11, 3, 1, 1)
        self.label_65 = QtGui.QLabel(Tube)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout.addWidget(self.label_65, 13, 0, 1, 1)
        self.label_66 = QtGui.QLabel(Tube)
        self.label_66.setIndent(18)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout.addWidget(self.label_66, 14, 0, 1, 2)
        self.pushButtonOutput = QtGui.QPushButton(Tube)
        self.pushButtonOutput.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutput.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutput.setObjectName(_fromUtf8("pushButtonOutput"))
        self.gridLayout.addWidget(self.pushButtonOutput, 14, 2, 1, 1)
        self.lineEditOutput = QtGui.QLineEdit(Tube)
        self.lineEditOutput.setObjectName(_fromUtf8("lineEditOutput"))
        self.gridLayout.addWidget(self.lineEditOutput, 14, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(618, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 12, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(618, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 15, 0, 1, 4)
        self.pushButtonCreate = QtGui.QPushButton(Tube)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 16, 0, 1, 4)

        self.retranslateUi(Tube)
        QtCore.QMetaObject.connectSlotsByName(Tube)

    def retranslateUi(self, Tube):
        Tube.setWindowTitle(_translate("Tube", "Form", None))
        self.label_67.setText(_translate("Tube", "Inputs:", None))
        self.label_64.setText(_translate("Tube", "2D T3 Scalar Mesh:", None))
        self.pushButtonInputMesh.setText(_translate("Tube", "...", None))
        self.label_68.setText(_translate("Tube", "Line Set:", None))
        self.pushButtonInputLineSet.setText(_translate("Tube", "...", None))
        self.label_69.setText(_translate("Tube", "Default values:", None))
        self.label_78.setText(_translate("Tube", "Rel =", None))
        self.label_70.setText(_translate("Tube", "Ce1 =", None))
        self.label_71.setText(_translate("Tube", "Ce2 =", None))
        self.label_72.setText(_translate("Tube", "Cs1 =", None))
        self.label_73.setText(_translate("Tube", "Cs2 =", None))
        self.label_74.setText(_translate("Tube", "Lrg =", None))
        self.label_75.setText(_translate("Tube", "Hau =", None))
        self.label_76.setText(_translate("Tube", "Clp =", None))
        self.label_77.setText(_translate("Tube", "L12 =", None))
        self.label_65.setText(_translate("Tube", "Outputs:", None))
        self.label_66.setText(_translate("Tube", "Textfile:", None))
        self.pushButtonOutput.setText(_translate("Tube", "...", None))
        self.pushButtonCreate.setText(_translate("Tube", "Let\'s go!", None))

