# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\uiXYZ2Profiles.ui'
#
# Created: Sat Nov 19 17:58:29 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_XYZ2Profiles(object):
    def setupUi(self, XYZ2Profiles):
        XYZ2Profiles.setObjectName(_fromUtf8("XYZ2Profiles"))
        XYZ2Profiles.resize(627, 759)
        self.gridLayout = QtGui.QGridLayout(XYZ2Profiles)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonInputProfiles = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonInputProfiles.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputProfiles.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputProfiles.setObjectName(_fromUtf8("pushButtonInputProfiles"))
        self.gridLayout.addWidget(self.pushButtonInputProfiles, 1, 1, 1, 1)
        self.lineEditOutputDXF = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditOutputDXF.setEnabled(False)
        self.lineEditOutputDXF.setObjectName(_fromUtf8("lineEditOutputDXF"))
        self.gridLayout.addWidget(self.lineEditOutputDXF, 11, 2, 1, 3)
        self.lineEditOutputHECRAS = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditOutputHECRAS.setEnabled(False)
        self.lineEditOutputHECRAS.setObjectName(_fromUtf8("lineEditOutputHECRAS"))
        self.gridLayout.addWidget(self.lineEditOutputHECRAS, 12, 2, 1, 3)
        self.label_106 = QtGui.QLabel(XYZ2Profiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_106.setFont(font)
        self.label_106.setIndent(-4)
        self.label_106.setObjectName(_fromUtf8("label_106"))
        self.gridLayout.addWidget(self.label_106, 0, 0, 1, 1)
        self.checkBoxOutputHECRAS = QtGui.QCheckBox(XYZ2Profiles)
        self.checkBoxOutputHECRAS.setObjectName(_fromUtf8("checkBoxOutputHECRAS"))
        self.gridLayout.addWidget(self.checkBoxOutputHECRAS, 12, 0, 1, 1)
        self.label_117 = QtGui.QLabel(XYZ2Profiles)
        self.label_117.setIndent(18)
        self.label_117.setObjectName(_fromUtf8("label_117"))
        self.gridLayout.addWidget(self.label_117, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(500, 227, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 5)
        self.pushButtonProfileSettings = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonProfileSettings.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButtonProfileSettings.setObjectName(_fromUtf8("pushButtonProfileSettings"))
        self.gridLayout.addWidget(self.pushButtonProfileSettings, 7, 2, 1, 1)
        self.comboBoxDefault = QtGui.QComboBox(XYZ2Profiles)
        self.comboBoxDefault.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBoxDefault.setObjectName(_fromUtf8("comboBoxDefault"))
        self.gridLayout.addWidget(self.comboBoxDefault, 7, 3, 1, 1)
        self.pushButtonOutputTextfile = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonOutputTextfile.setEnabled(False)
        self.pushButtonOutputTextfile.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputTextfile.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputTextfile.setObjectName(_fromUtf8("pushButtonOutputTextfile"))
        self.gridLayout.addWidget(self.pushButtonOutputTextfile, 10, 1, 1, 1)
        self.pushButtonCreate = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonCreate.setObjectName(_fromUtf8("pushButtonCreate"))
        self.gridLayout.addWidget(self.pushButtonCreate, 14, 0, 1, 5)
        self.label_104 = QtGui.QLabel(XYZ2Profiles)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.label_104.setFont(font)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.gridLayout.addWidget(self.label_104, 9, 0, 1, 1)
        self.pushButtonDefault = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonDefault.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButtonDefault.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonDefault.setObjectName(_fromUtf8("pushButtonDefault"))
        self.gridLayout.addWidget(self.pushButtonDefault, 7, 4, 1, 1)
        self.label_103 = QtGui.QLabel(XYZ2Profiles)
        self.label_103.setIndent(18)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.gridLayout.addWidget(self.label_103, 2, 0, 1, 1)
        self.lineEditInputReachName = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditInputReachName.setObjectName(_fromUtf8("lineEditInputReachName"))
        self.gridLayout.addWidget(self.lineEditInputReachName, 4, 2, 1, 3)
        self.pushButtonInputReach = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonInputReach.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputReach.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputReach.setObjectName(_fromUtf8("pushButtonInputReach"))
        self.gridLayout.addWidget(self.pushButtonInputReach, 2, 1, 1, 1)
        self.lineEditOutputTextfile = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditOutputTextfile.setEnabled(False)
        self.lineEditOutputTextfile.setObjectName(_fromUtf8("lineEditOutputTextfile"))
        self.gridLayout.addWidget(self.lineEditOutputTextfile, 10, 2, 1, 3)
        self.lineEditInputReach = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditInputReach.setObjectName(_fromUtf8("lineEditInputReach"))
        self.gridLayout.addWidget(self.lineEditInputReach, 2, 2, 1, 3)
        self.doubleSpinBoxSuperelevation = QtGui.QDoubleSpinBox(XYZ2Profiles)
        self.doubleSpinBoxSuperelevation.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBoxSuperelevation.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSuperelevation.setMinimum(0.01)
        self.doubleSpinBoxSuperelevation.setMaximum(99999.99)
        self.doubleSpinBoxSuperelevation.setProperty("value", 1.0)
        self.doubleSpinBoxSuperelevation.setObjectName(_fromUtf8("doubleSpinBoxSuperelevation"))
        self.gridLayout.addWidget(self.doubleSpinBoxSuperelevation, 6, 2, 1, 1)
        self.lineEditInputProfiles = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditInputProfiles.setObjectName(_fromUtf8("lineEditInputProfiles"))
        self.gridLayout.addWidget(self.lineEditInputProfiles, 1, 2, 1, 3)
        self.label_59 = QtGui.QLabel(XYZ2Profiles)
        self.label_59.setMinimumSize(QtCore.QSize(70, 0))
        self.label_59.setIndent(18)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout.addWidget(self.label_59, 7, 0, 1, 1)
        self.lineEditInputPoints = QtGui.QLineEdit(XYZ2Profiles)
        self.lineEditInputPoints.setObjectName(_fromUtf8("lineEditInputPoints"))
        self.gridLayout.addWidget(self.lineEditInputPoints, 3, 2, 1, 3)
        self.label_105 = QtGui.QLabel(XYZ2Profiles)
        self.label_105.setIndent(18)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.gridLayout.addWidget(self.label_105, 1, 0, 1, 1)
        self.checkBoxOutputTextfile = QtGui.QCheckBox(XYZ2Profiles)
        self.checkBoxOutputTextfile.setObjectName(_fromUtf8("checkBoxOutputTextfile"))
        self.gridLayout.addWidget(self.checkBoxOutputTextfile, 10, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(609, 255, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 13, 0, 1, 5)
        self.spinBoxScale = QtGui.QSpinBox(XYZ2Profiles)
        self.spinBoxScale.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBoxScale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxScale.setMaximum(9999999)
        self.spinBoxScale.setProperty("value", 100)
        self.spinBoxScale.setObjectName(_fromUtf8("spinBoxScale"))
        self.gridLayout.addWidget(self.spinBoxScale, 5, 2, 1, 1)
        self.label_109 = QtGui.QLabel(XYZ2Profiles)
        self.label_109.setIndent(18)
        self.label_109.setObjectName(_fromUtf8("label_109"))
        self.gridLayout.addWidget(self.label_109, 4, 0, 1, 1)
        self.checkBoxOutputDXF = QtGui.QCheckBox(XYZ2Profiles)
        self.checkBoxOutputDXF.setObjectName(_fromUtf8("checkBoxOutputDXF"))
        self.gridLayout.addWidget(self.checkBoxOutputDXF, 11, 0, 1, 1)
        self.pushButtonOutputDXF = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonOutputDXF.setEnabled(False)
        self.pushButtonOutputDXF.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputDXF.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputDXF.setObjectName(_fromUtf8("pushButtonOutputDXF"))
        self.gridLayout.addWidget(self.pushButtonOutputDXF, 11, 1, 1, 1)
        self.pushButtonOutputHECRAS = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonOutputHECRAS.setEnabled(False)
        self.pushButtonOutputHECRAS.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonOutputHECRAS.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonOutputHECRAS.setObjectName(_fromUtf8("pushButtonOutputHECRAS"))
        self.gridLayout.addWidget(self.pushButtonOutputHECRAS, 12, 1, 1, 1)
        self.label_107 = QtGui.QLabel(XYZ2Profiles)
        self.label_107.setIndent(18)
        self.label_107.setObjectName(_fromUtf8("label_107"))
        self.gridLayout.addWidget(self.label_107, 3, 0, 1, 1)
        self.pushButtonInputPoints = QtGui.QPushButton(XYZ2Profiles)
        self.pushButtonInputPoints.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButtonInputPoints.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButtonInputPoints.setObjectName(_fromUtf8("pushButtonInputPoints"))
        self.gridLayout.addWidget(self.pushButtonInputPoints, 3, 1, 1, 1)
        self.label_122 = QtGui.QLabel(XYZ2Profiles)
        self.label_122.setIndent(18)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout.addWidget(self.label_122, 6, 0, 1, 1)

        self.retranslateUi(XYZ2Profiles)
        QtCore.QMetaObject.connectSlotsByName(XYZ2Profiles)

    def retranslateUi(self, XYZ2Profiles):
        XYZ2Profiles.setWindowTitle(_translate("XYZ2Profiles", "Form", None))
        self.pushButtonInputProfiles.setText(_translate("XYZ2Profiles", "...", None))
        self.label_106.setText(_translate("XYZ2Profiles", "Inputs:", None))
        self.checkBoxOutputHECRAS.setText(_translate("XYZ2Profiles", "HEC-RAS Gemetry Data file:", None))
        self.label_117.setText(_translate("XYZ2Profiles", "Scale factor:", None))
        self.pushButtonProfileSettings.setText(_translate("XYZ2Profiles", "output settings", None))
        self.pushButtonOutputTextfile.setText(_translate("XYZ2Profiles", "...", None))
        self.pushButtonCreate.setText(_translate("XYZ2Profiles", "Let\'s go!", None))
        self.label_104.setText(_translate("XYZ2Profiles", "Outputs:", None))
        self.pushButtonDefault.setToolTip(_translate("XYZ2Profiles", "set default legend", None))
        self.pushButtonDefault.setText(_translate("XYZ2Profiles", "set default", None))
        self.label_103.setText(_translate("XYZ2Profiles", "Channel reach file:", None))
        self.pushButtonInputReach.setText(_translate("XYZ2Profiles", "...", None))
        self.label_59.setText(_translate("XYZ2Profiles", "Output settings:", None))
        self.label_105.setText(_translate("XYZ2Profiles", "Channel profiles file:", None))
        self.checkBoxOutputTextfile.setText(_translate("XYZ2Profiles", "Textfile:", None))
        self.label_109.setText(_translate("XYZ2Profiles", "Reach name:", None))
        self.checkBoxOutputDXF.setText(_translate("XYZ2Profiles", "DXF file:", None))
        self.pushButtonOutputDXF.setText(_translate("XYZ2Profiles", "...", None))
        self.pushButtonOutputHECRAS.setText(_translate("XYZ2Profiles", "...", None))
        self.label_107.setText(_translate("XYZ2Profiles", "Points file:", None))
        self.pushButtonInputPoints.setText(_translate("XYZ2Profiles", "...", None))
        self.label_122.setText(_translate("XYZ2Profiles", "Superelevation factor:", None))

